### ISSUE TITLE
[FR] Allow setting default MTU in installer

### ISSUE THREAD

**Issue by ymarkus** [pivpn/pivpn#1019]
I was always having issues with large packets (length 1452) not arriving on my clients. This issue is resolved when setting the MTU to `1280` (or another lower value) in the client config.

I would like an option to set the default MTU in the installer, as it would be easier than always doing it by hand.

An example of a packet that doesn't arrive with the higher MTU:
`08:15:15.986951 IP [SERVERIP].[PORT] > [CLIENT-IP].[PORT]: UDP, length 1452`
Example after changing MTU (this smaller packet arrives):
`08:22:18.304041 IP [SERVERIP].[PORT] > [CLIENT-IP].[PORT]: UDP, length 1312`

**Comment by orazioedoardo** [comment]
I'm a bit against adding to much options and complexity to the installation process, MTU could go to the wiki, you may not know that you need to change the MTU before installing. I'm adding an information tag for now.

**Comment by DerDanilo** [comment]
Also mentioned in https://github.com/pivpn/pivpn/issues/282

This is an absolute must have for the configuration. Other wg installation script even go so far to set the default MTU to 1280 since this seems the best value with the least problems.

It is fine for me to configure the MTU manually in the server settings. The problem is that the mtu then is not configured in the generated client config which is the real problem.

Hence the scripts should check for a configured value in the wg0.conf (server conf with whatever interface is used) and then put it into the client config files.

**Comment by DerDanilo** [comment]
@orazioedoardo @redfast00 Ping. 

I am happy to help, please point me in the right direction. I would also appreciate it if someone could help with the GUI part since I've no experience with the tools that are used for that.

Also we could directly add setupVAR support alltogether with #1273 to get that sorted out as well.

**Comment by orazioedoardo** [comment]
My vote is to add support for custom MTU when using unattended mode and on the client.conf files. Here's how unattended is managed: https://github.com/pivpn/pivpn/blob/d7771c251418fa443869397d46f93c5b0c197558/auto_install/install.sh#L1109-L1138 and  how a client is created: https://github.com/pivpn/pivpn/blob/d7771c251418fa443869397d46f93c5b0c197558/scripts/wireguard/makeCONF.sh#L97-L114

**Comment by DerDanilo** [comment]
Thanks. 

- And where is the server conf generated? The MTU vars should then go there. Or is this part already dynamic?
- Does the `makeCONF.sh`  script query the setupvars under `/etc/pivpn` every time it is called?

**Comment by orazioedoardo** [comment]
> * And where is the server conf generated? The MTU vars should then go there. Or is this part already dynamic?

Generated [here](https://github.com/pivpn/pivpn/blob/d7771c251418fa443869397d46f93c5b0c197558/auto_install/install.sh#L2047-L2051).

> * Does the `makeCONF.sh`  script source the setupvars under `/etc/pivpn` every time it is called?

Yes it does.

**Comment by 4s3ti** [comment]
> My vote is to add support for custom MTU when using unattended mode and on the client.conf files. Here's how unattended is managed:


In addition to this, i'd say it should use the default value when not provided in the configuration file

**Comment by DerDanilo** [comment]
Please correct me if I'm wrong but the following vars in the setupVARs wireguard example file have no meaning and can therefore be removed. Right?

```
IPv4addr=192.168.23.211/24
IPv4gw=192.168.23.1
dhcpReserv=0
```

**Comment by DerDanilo** [comment]
Here we go.
https://github.com/pivpn/pivpn/pull/1278

> 
> 
> Please correct me if I'm wrong but the following vars in the setupVARs wireguard example file have no meaning and can therefore be removed. Right?
> 
> ```
> IPv4addr=192.168.23.211/24
> IPv4gw=192.168.23.1
> dhcpReserv=0
> ```

I could include this in the merge request but noone confirmed it yet. Can also be cleaned up later.
