### ISSUE TITLE
[Support] Add Wireguard to existing pivpn openvpn configuration

### ISSUE THREAD

**Issue by mattimac** [pivpn/pivpn#1033]
Assume one is running pivpn instance on raspberry pi4 that already have openvpn configuration.
What should be done to add wireguard support without touching/breaking openvpn configuration? Wireguard option was not checked during first installation of pivpn on this host.

**Comment by shelleycat485** [comment]
See the pull request #1030, which is currently open.  This allows a dual install of the protocols, and I would welcome any testing of that.  You should be able to clone the repository the pull request came from.  Any help, come back to me because I am interested, I'll be around after about 12:00 today 26.

**Comment by mattimac** [comment]
@shelleycat485  do you suggest that using both openvpn and wireguard is currently not supported in pivpn?

**Comment by shelleycat485** [comment]
Its being worked on and is in the pivpn/pivpn test branch,

Both wireguard and openvpn can be installed together (Issue #968) #1048

Second protocol can be installed by doing another install, and selecting the protocol…

**Comment by mattimac** [comment]
> Second protocol can be installed by doing another install, and selecting the protocol…
Is it possible to install wiregueard to the existing openvpn-only installation without risk of altering openvpn config or affecting it's operation? This is what the issue is all about. If that is possible - how exactly one should perform it?

**Comment by shelleycat485** [comment]
No, I don't think you can do that. 
What you can do is go with the 1st solution I did, which should work. Its an automation of what I did with a running pivpn (openvpn), to get a wireguard onto it. It managed it and kept the configurations with a reboot.   That was basically two installations, with the first being a standard pivpn and the second as a separate pivpnY command.  To do that now, I would
1  Take a backup of your existing configuration.
2  use repository shelleycat485/pivpn branch altcommand_version.  Clone this to your target.  Check you have the right branch.
3  edit the install script so that the repository is your local one on the target (you have to do this becuase altcommand_version was intended for a pull request so it points at pivpn/pivpn repository).
4  Copy or make a link to the install script and run with --altcommand wg
5  I;m happy to help with more questions - I would test this on something local before trying the remote stuff if you have the hardware.
