### ISSUE TITLE
[FR] Provide a choice during install for Allowed IPs/Ranges

### ISSUE THREAD

**Issue by t0m5k1** [pivpn/pivpn#1041]
It would be really nice if the script gave us a choice for the Allowed IPs of each client to be 0.0.0.0 ::0 (ALL/full VPN) or the internal range provided by the VPN (10.6.10.0/24) this way it would allow those of us who use this with pihole to easily have split tunnel only for DNS traffic.

Perhaps the script could run a little check to see if pihole is present on the system and then offer this up as a choice during installation.

**Comment by orazioedoardo** [comment]
I don't really like having too much options, PiVPN is supposed to be an installer to help people get started with a fully functional VPN, not an an abstraction for every functionality, expecially when the change is very easy: https://github.com/pivpn/pivpn/wiki/WireGuard#how-do-i-allow-clients-access-to-my-home-network-but-not-the-internet-through-my-pivpn

**Comment by t0m5k1** [comment]
Thanks for the response.
Whilst I understand what your saying this is a fundamental choice when implementing any VPN:
Do I want a split tunnel or not?

Adding this into the script won't add clutter but allow the installer to think of this fundamental question right from the get go and stop any confusion when deploying it as well as removing the need to edit every single file by hand which let's face it can be tedious with a large amount of clients.

You could also adding this as a command switch or part of the process for when we add a client with pivpn -a, Once it has asked you to input a title for the client it could simply ask if this is split tunnel or not, if yes just add the subnet used by wireguard instead of 0.0.0.0/0 ::0 

Personally I think it would be cleaner, Don't you?

**Comment by 4s3ti** [comment]
this seems to me an edge case and a specific usage for power users ... those who want that kind of setup can do it themselves ... I kind of agree with @orazioedoardo ... the priority here is the common user who knows pretty much nothing! 

I'd like to have certain kind of features (like this one) out of reach of common users because ... well ... users will be users and able to do the most weird things happen .. and who has to deal with their recurring issues? 

I know it can be tedious for you ... but well ... PiVPN is not really meant to Manage a big number of users either ... otherwise it would be an enterprise solution :)

**Comment by t0m5k1** [comment]
With a name like pivpn many users will come from pihole meaning all we want
is DNS going down the VPN.

If that's an enterprise use case I'll shut up and continue to tell them
their use case is not catered for as it's far too advanced for a noob.
Cheers

**Comment by orazioedoardo** [comment]
@t0m5k1 No, split tunnel is not too advanced for a noob, however I think the user should be encouraged to learn the inner workings instead of having an option for everything.

**Comment by orazioedoardo** [comment]
Lately I was reconsidering making openvpn and wireguard steps equal, while providing "advanced options" for these additional features.

**Comment by 4s3ti** [comment]
@t0m5k1 Sorry if i wasn't clear enough ... when i mentioned the enterprise solution was regarding the amount of users to manage with PiVPN. not about the feature itself :)

**Comment by klooj** [comment]
i am grateful for this repo and do not have anything to tilt scales in this (stale) conversation.  

but i think it's worth framing our notions of "noobs" and "common users" vs "power users" among pivpn users as people who are nonetheless on the command line, making them a rare creatures at large. they have already taken the plunge into tedious complexity.

an uncommon need for control paired with a high tolerance for problem solving is the very reason that an otherwise rational person finds themselves cloning an open source repo onto a linux machine in order to leverage the functionality of their the personal dns service.

top to bottom, these people are not lambs; i think "encouraged to learn the inner workings" brought them here in the first place.

**Comment by klooj** [comment]
commit [b5ec995](https://github.com/pivpn/pivpn/commit/b5ec995f68fbae2eb30b50e1b6a4350f96316f2e) all but closes this?

**Comment by 4s3ti** [comment]
This is now allowed via unattended setup. 

https://github.com/pivpn/pivpn/pull/1279 

Guess this can now be closed. 
If you believe this has not been endorsed and therefore I am wrongfully closing this issue, please feel free to re-open.
