### ISSUE TITLE
[Support] <Your Issue here>

### ISSUE THREAD

**Issue by clipse2004** [pivpn/pivpn#1049]
Hi first nice projekt!

but i have a problem, after installing pivpn to my raspberry and running "sudo apt update / sudo apt upgrade" i get always same message like: 

Die folgenden Pakete werden durch eine ÄLTERE VERSION ERSETZT (Downgrade):
  python3-pgzero

this package will replaced by older one. i click yes and it installed but after a retry for apt update / upgrade same message shows up. 

Any help for this?

**Comment by 4s3ti** [comment]
Dear user, even though we love the fact you are using pivpn, the maintainers of this project keep answering the same thing over and over again.

They keep spending time not only on the project that makes your life so great but also on documentation that you not to read at all therefore this issue is being closed. 

Don't know why your issue got closed? 

You can start by reading here: https://www.pivpn.io/#contrib
And here: https://github.com/pivpn/pivpn/blob/master/README.md
And here: https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md

and the first lines on the issue template that appeared after you have pressed all those green buttons to open up this issue: 

```
<!-- 
# PiVPN Issue Template
PLEASE READ THIS TEMPLATE CAREFULLY BEFORE OPENING AN ISSUE! 
Any Issue opened that doesn't follow this template will be removed.
```

Still not happy? 

Feel free to express yourself but most likely our position won't change, and hopefully you have now learned how to open an issue anywhere in the opensource community! 


Wish you a great day, feel free to reopen this issue but this time make sure it follows the rules!

**Comment by TD540** [comment]
How absolutely arrogant.

**Comment by clipse2004** [comment]
> How absolutely arrogant.

Me?

**Comment by Andrononow** [comment]
I have the same question.

**Comment by TD540** [comment]
try `sudo apt remove python3-pgzero`

**Comment by amandamana** [comment]
I also get the python3-pgzero DOWNGRADE message from apt upgrade after installing pivpn on Raspbian 10.4

The message persists as the downgrade seems to fail:
`Get:1 http://archive.raspberrypi.org/debian buster/main armhf python3-pgzero all 1.2.post4+dfsg-2 [72.3 kB]
Fetched 72.3 kB in 1s (86.2 kB/s)       
(Reading database ... 188123 files and directories currently installed.)
Preparing to unpack .../python3-pgzero_1.2.post4+dfsg-2_all.deb ...
Unpacking python3-pgzero (1.2.post4+dfsg-2) over (1.2.post4+dfsg-2) ...
Setting up python3-pgzero (1.2.post4+dfsg-2) ...
Processing triggers for man-db (2.8.5-2) ...
Error: Timeout was reached`

I don't seemed to have anything installed that officially depends on python3-pgzero, but guess that's it used by a pivpn script, so am reluctant to remove it.

**Comment by sak171** [comment]
I don’t have proven script I believe my iOS has been taken over by a developer

**Comment by TD540** [comment]
It really is the strangest thing: that everyone keeps ending up here 🤪 while there isn't any info or discussion what so ever to be found about downgrading python3-pgzero here or on their subreddit, yet @4s3ti claims everyone keeps asking maintainers about it...

I just went ahead and _apt remove_'d it. I don't need Pygame on my pivpn machine.

**Comment by SodaWithoutSparkles** [comment]
Same here.
```
sudo apt remove python3-pyzero
```
PiVPN went just fine.

**Comment by fedekrum** [comment]
Same issue here. 
@4s3ti, if true, please give us the "multiple replay's URLs" for us to read the solution, as you did not provide any solution at all.

**Comment by 4s3ti** [comment]
@fedekrum don't hijack close treads and tag ppl on them! 

Please open your own with the accurate data requested in the form!
