### ISSUE TITLE
[FR] <Email information for successful and unsuccessful VPN connections>

### ISSUE THREAD

**Issue by ovz93br43v7** [pivpn/pivpn#1057]
**Is your feature request related to a problem? Please describe.**
I successfully installed PiVPN wireguard yesterday and everything is working fine. But I'm confused that the VPN connection is not secured by any kind of second factor (password, PIN, token...)

**Describe the solution you'd like**
I would like to have an email information for all successful and unsuccessful VPN connections.

**Describe alternatives you've considered**
Nothing until now.

**Additional context**
I used this guide (german only: https://www.thomas-krenn.com/de/wiki/Absicherung_eines_Debian_Servers) to set up a email information for SSH connections and thought that this could be useful also for successful and unsuccessful VPN connections.
But I have no idea how to make this on my own for PiVPN / wireguard.

**Comment by 4s3ti** [comment]
Don't think this is a PiVPN feature to implement ... 

The way I look at it ... its a feature completely out of PiVPN Scope and sounds more a feature that should be supported by OpenVPN and Wireguard, and even there i still have my reservations ... 


However ... Its not entirely true that there is no Second factor authentication. 

As for OpenVPN .. Something you have (certificate) + Something you know (certificate password)

as for wireguard .. wireguard was built from the ground up and uses a completely different paradigm ... @orazioedoardo can explain way better than me why it doesn't use password on the certificates... 

but i'd say its easy to integrate with other authentication methods and upon authentication get a short living certificate ... which is completely out of scope of pivpn.

**Comment by ovz93br43v7** [comment]
Ok I understand. Sorry for opening this request.

**Comment by orazioedoardo** [comment]
@ovz93br43v7 Email notification on client connection is possible using the `client-connect cmd` directive in the OpenVPN server configuration.

> Run command cmd on client connection.cmd consists of a path to script (or executable program), optionally followed by arguments. The path and arguments may be single- or double-quoted and/or escaped using a backslash, and should be separated by one or more spaces.
>
> The command is passed the common name and IP address of the just-authenticated client as environmental variables (see environmental variable section below). The command is also passed the pathname of a freshly created temporary file as the last argument (after any arguments specified in cmd ), to be used by the command to pass dynamically generated config file directives back to OpenVPN.

Not sure about unsuccessful connections, there are multiple points in time when a client can fail to authenticate. You could create some hacks like logging incoming connections with iptables and state that a client failed to connect if you see the incoming packet but you don't see a client connection in the openvpn log few seconds later.

Regarding wireguard, there is no conception of connections or disconnections: when a client needs to send something, it authenticates and starts sending. If the client has nothing to send, there is no timeout or disconnection, is just silent. In fact if you run `sudo wg show` or `pivpn -c`, you won't see connected, but last seen or last handshake.

Also there are not wireguard logs by default, if the kernel supports dynamic debugging you can [enable them](https://wiki.archlinux.org/index.php/WireGuard#Enable_debug_logs), but the raspbian kernel doesn't. Probably you can still get logs if you manually compile wireguard with the debug flag but then you loose the convenience of the package managers.

Wireguard has no password protected private keys because the developer thinks that key management is out of scope of the project, so If you want to protect configurations while moving them from one device to another you have to come up with something yourself.
