### ISSUE TITLE
Not detecting pi OS

### ISSUE THREAD

**Issue by kevinouw** [pivpn/pivpn#1099]
The new PI os is not been detected by the script and thinks I am on a :
  x                                                                    x
  x Since we think you are not using Raspbian, we will not configure a x
   x static IP for you.                                                 x
  x If you are in Amazon then you can not configure a static IP        x
  x anyway. Just ensure before this installer started you had set an   x
   x elastic IP on your instance.                                       x
  x        

Latest os from :

https://www.raspberrypi.org/downloads/raspberry-pi-os/

**Comment by orazioedoardo** [comment]
What's the output of `cat /etc/os-release`?

**Comment by Backes89** [comment]
same problem for me with the 64-bit version of raspbian.

Output of `cat /etc/os-release`:

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by orazioedoardo** [comment]
@Backes89 What about `dpkg --print-architecture`?

**Comment by Backes89** [comment]
Output of `dpkg --print-architecture`:

arm64

**Comment by kevinouw** [comment]
Sorry I had to roll back from the new os sadly cause of some issues other then the pi vpn :( my discord bot my "corp in eve use had some stable issues"

**Comment by Backes89** [comment]
@orazioedoardo 
I think in regard of other scripts which use a similiar detection of the os, a bug-report should be filled at the raspbian-team. The output ot the 32-bit version states:

`PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"`

I think this indicates a bug at their site due to misleading output of the OS-pretty-name. Will fill a bug-report later at their bug-tracker.

**Comment by orazioedoardo** [comment]
Apparently the 64-bit version advertises itself as Debian and WireGuard on that distribution is only available for x86 systems when using PiVPN.

**Comment by orazioedoardo** [comment]
I think the Raspbian team will revert to the original PRETTY_NAME when the 64-bit OS goes out of beta.

**Comment by kevinouw** [comment]
But I believe my PI version was 32 bit

**Comment by orazioedoardo** [comment]
> But I believe my PI version was 32 bit

I've just unpacked the _May 2020_ release of _Raspberry Pi OS (32-bit) Lite_ and confirmed that it correctly advertises itself as _Raspbian GNU/Linux_.

**Comment by Backes89** [comment]
Bug at the raspberry foundation got rejected with the reasen, that the 64-bit pi OS is not raspbian.

Here -> [Blog at raspberry Pi OS](https://www.raspberrypi.org/blog/latest-raspberry-pi-os-update-may-2020/) they are also stating, that the 64-bit version is just Debian with the raspbian-desktop.

So I would assume this bug can be closed because it's not a bug. The installer detectes it correctly.

**Comment by sunjam** [comment]
Detection fails on latest Pi OS `arm64 lite` from [official images here](https://downloads.raspberrypi.org/raspios_lite_arm64/images/)

$ dpkg --print-architecture
arm64

**Comment by orazioedoardo** [comment]
@sunjam 64 bit version of Raspberry Pi OS is not supported.
