### ISSUE TITLE
A feature to disable / enable single wireguard client configs would be very apreciated 

### ISSUE THREAD

**Issue by delight** [pivpn/pivpn#1111]
It would be very nice to be able to disable / enable a wireguard client configuration

In that way you can disable / enable an affiliated account as needed in a certain situation - resulting in more flexibility.

Possible applications:
- Give a client access on request
- Enable disable access on certain times only ( with a little crontab )
- ... I bet there is even more applications to this

**Comment by shelleycat485** [comment]
Starting to look at this.  My plan is to:
Code like the delete, but comment out lines for the user in configs, wg0.conf instead of delete.
Add a (new) log file to the configs directory giving a timestamp of when the disable or re-enable takes place.
Have the option of having the user on the command line, so that a cron job can easily enable/disable
Check the add user so that a commented out user is considered for clashes when adding a new user
Check the add user so that a commented out user address (10.6.0...) is not reused
Check the delete user so that a commented out user can also be deleted
Check the -c command so that disabled users are listed as well
Leave the .conf file for the client in place whether disabled or not.
If someone else is looking at this, please let me know.

**Comment by shelleycat485** [comment]
Still looking at this.  At the moment cannot test on AWS 20 or AWS 18 because cannot install - fails to find iptables-persistent package!.   I've tried installing from the test branch of pivpn directly, with no other changes, and I get the same.

**Comment by 4s3ti** [comment]
Merged into master: https://github.com/pivpn/pivpn/commit/b5ec995f68fbae2eb30b50e1b6a4350f96316f2e

**Comment by delight** [comment]
Is there going to be a new release and will it be necessary to reinstall?

Thnx

**Comment by 4s3ti** [comment]
@delight pivpn does not work with releases ... this is an installer and it has done its job after you have used it ... you can update PiVPN Scripts by running pivpn again and it will offer you to update them.

**Comment by delight** [comment]
Thank you for clarifying 👍🏻
