### ISSUE TITLE
[Support] I would manage the remote 4G router by first resolving the NAT with pivpn

### ISSUE THREAD

**Issue by githubbuc** [pivpn/pivpn#1150]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

I would like to manage the remote 4G router by solving the NAT with pivpn first.
my VPN is up and running!
Here is my network topology:

Client side:
-PC with OpenVPN Connect
-tunnel openvpn ip (Private ip) 10.8.0.2
-DHCP reservation ip 192.168.0.100

Server side
-Raspberry Pi with pivpn
-tunnel openvpn ip 10.8.0.1
-DHCP reservation ip 192.168.1.254

I successfully ping from PC (client) to IP 10.8.0.1 (server).
I successfully ping from PC (client) to IP 192.168.1.254 (server).

I successfully ping Raspberry Pi (server) to IP 10.8.0.2 (client).
I can not ping from Raspberry Pi (server) to IP 192.168.0.100 (client).

could you tell me what I can do?

**Comment by orazioedoardo** [comment]
> I would like to manage the remote 4G router by solving the NAT with pivpn first.

That's a bit too much a IT tech support request than a PiVPN support request. By the way if you have a 4G probably you don't have a public IP to connect to, only a shared one.

**Comment by githubbuc** [comment]
> > I would like to manage the remote 4G router by solving the NAT with pivpn first.
> 
> That's a bit too much a IT tech support request than a PiVPN support request. By the way if you have a 4G probably you don't have a public IP to connect to, only a shared one.

Thanks for the reply. 
I confirm, I don't have a public IP. 
ISP issues me a private ip.
I can reach ip OpenVPN Client Connect (10.8.0.2) which is an app on my PC so I go through the router.
Do you  think that I can do something to ping the router from the pivpn server?
Maybe I need to add another raspeberry asking him to define the server path in your opinion?
Thanks a lot orazioedoardo!

**Comment by orazioedoardo** [comment]
How can you connect remotely to the VPN if your ISP issues a private IP?

**Comment by githubbuc** [comment]
> How can you connect remotely to the VPN if your ISP issues a private IP?

I try to explain it, but I don't know the details.
If I connect to my router I see IP Address: 10.x.x.x (private)
if from my browser I connect to whatismyipaddress.com I see 151.y.y.y (public).

on this page it is very well explained in **scenario 3 sharad puplic ip**
https://www.devadmin.it/2018/07/24/ accesso-remoto-verso-router-3g-4g/

**Comment by orazioedoardo** [comment]
> Quindi sebbene il router possa accedere a Internet non sarà possibile raggiungerlo in quanto l’IP Pubblico è condiviso.

Indeed you can't connect directly, but you can do indirectly through another host which is publicly accessible, for example a cloud server o another raspberry pi within a network with public IP.

1: Remote client
2: publicly accessible PiVPN
3: NATed PiVPN
4: private network

1 ---> 2 ---> 3 ---> 4

You would install PiVPN on both Pis and have 3 connect via VPN to 2 and setup some routing and forwarding rules such that the remote client (connected to 2), can access 4 using 2 as gateway.

**Comment by githubbuc** [comment]
> > Quindi sebbene il router possa accedere a Internet non sarà possibile raggiungerlo in quanto l’IP Pubblico è condiviso.
> 
> Indeed you can't connect directly, but you can do indirectly through another host which is publicly accessible, for example a cloud server o another raspberry pi within a network with public IP.
> 
> 1: Remote client
> 2: publicly accessible PiVPN
> 3: NATed PiVPN
> 4: private network
> 
> 1 ---> 2 ---> 3 ---> 4
> 
> You would install PiVPN on both Pis and have 3 connect via VPN to 2 and setup some routing and forwarding rules such that 1 (connected to 2), can access 3 and 4 using 2 as gateway.

Ok. 
The only PiVPN I have for now is the one where I have an ISP with public IP (ISP 1).
My 4G router, on the other side, is with another ISP giving me a private  IP into router  
therefore shared public IP (ISP 2).
Now I try a second raspberry to put together your suggestions.
**Will I have to set the routing and forwarding rules in second NATed PiVPN?**
Thank you very much for the ideas you gave me.

**Comment by githubbuc** [comment]
I gave myself the second raspberry.
But now I lack some knowledge.
Should I configure "PiVPN NATed" the same as "PiVPN publicly accessible"?
How do I configure "PiVPN NAT" so that its gateway is "PiVPN publicly accessible"?
Thank you

**Comment by orazioedoardo** [comment]
So you should install PiVPN normally on the public Raspberry and WireGuard manually on the natted Raspberry (I'm using WireGuard because it's easier, check out the PiVPN install script for steps). The natted Raspberry will be a client.

- Generate a config on the public Raspberry with PiVPN.
- Copy the config to `/etc/wireguard/wg0.conf` on the natted Pi. Change it's allowed IP to the range of the public Raspberry LAN, also add the [persistent keepalive flag](https://www.wireguard.com/quickstart/#nat-and-firewall-traversal-persistence), so the nattted Pi will keep an open connection to the public Pi indefinitely.
- On the public Pi, add the range of the natted Raspberry LAN to the `/etc/wireguard/wg0.conf.

WireGuard is configured. Now firewall and routing.

- On the public Pi, we don't need NAT, since we will use routing to direct traffic: https://github.com/pivpn/pivpn/issues/1014
```
sudo -i
# Clear the NAT table
iptables -t nat -F
# Save the configuration
iptables-save > /etc/iptables/rules.v4
exit
```
- On the router of the public Pi LAN, add the following static route:
Destination: natted Pi LAN
Gateway: LAN IP of the public PI
- On the router of the natted Pi LAN, add the following static route:
Destination: public Pi LAN
Gateway: LAN IP of the natted PI

- Restart WireGuard on both Pis with `sudo systemctl restart wg-quick@wg0`

If I'm not missing anything, you should now have bidirectional traffic between both networks. For example, if you have a PC in the natted network, you can access another PC in the other network where you have the public Pi (an vice versa).

PC -> natted Pi -> internet -> public Pi -> PC.

**Comment by orazioedoardo** [comment]
Closing as unrelated and inactive, but may be useful for some user, so will add the information badge
