### ISSUE TITLE
Lost connection in the middle of the install

### ISSUE THREAD

**Issue by planetahuevo** [pivpn/pivpn#12]
Is there anyway to run the installer from when it stopped? 
I lost connection after the 2048 key was generated, because of this I need to start over and again wait for the 2048 key to be generated again.
Would be possible to run the config setup when the keys are already generated so it only ask for the other config data?

Thanks

**Comment by 0-kaladin** [comment]
Not from the installer.  If you have an unstable connection to your pi I'd recommend you do anything from a 'screen' session.
`apt-get install screen`.
 
you can follow [this](https://www.howtoforge.com/linux_screen) little tutorial.  Then if you get disconnected all you have to do is re-attach to the screen session.

**Comment by planetahuevo** [comment]
The problem is that I am accesing it from another network (in another city in fact), so sometimes my internet is the one failing. 
Screen seems a very good solution. 

Thanks!

**Comment by 0-kaladin** [comment]
Yea even if I have a solid connection, if i'm doing something I really want to ensure it won't get interrupted, I'll run it in a screen session.  I could add a resume after key generation since that can be long but I don't know of a very easy way to add this in (i can think of mediocre ways) so not sure worth it for how many would find it helpful.  Esp since there are other solutions (ie screen).
