### ISSUE TITLE
[BUG] UPDATE_PKG_CACHE seems to not work

### ISSUE THREAD

**Issue by 4s3ti** [pivpn/pivpn#1204]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

@orazioedoardo First of all i am sorry i am raising duplicated stuff that has been talked before, but as you know been in Lurk mode, but seen this happening quite often, and with all the testing i am trying maybe it will be possible to find some clues on how to fix this. 

**Describe the bug**

Has we have seen in the past, some users complain that the script fails then they run apt udpate and it works, 
During testing i stumbled upon this scenario, on ubuntu 18.04, 
2 different systems, same distro, one is a VPS that i spun up for some manual testing, the another one is the VM that travis spins up to run the testing. 
on the VPS the script worked straight away, 
on Travis I need to add `apt update` as first step of the script, otherwise `iptables-persistent` would fail to install 
This doesn't seem to have happened in any scenario on ubuntu 16.04 so far. 

```
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for iptables-persistent... not installed!
:::    Failed to install iptables-persistent!
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package iptables-persistent
```

**To Reproduce**
Not sure how to reproduce and on which conditions this happens.

**Expected behavior**
PiVPN should update package cache which seems to not happen in some situations

**Additional context**

Some questions that it brings me... 

Is `updatePackageCache()` really working all the time? what could cause it not to work some times?

**Possible solution 1**

change [UPDATE_PKG_CACHE](https://github.com/pivpn/pivpn/blob/master/auto_install/install.sh#L35) to `${PKG_MANAGER} update -y` 
and ignore this: https://github.com/pivpn/pivpn/blob/master/auto_install/install.sh#L408-L417 and make it run every time the install script runs? 

I would say that the logic behind of that  is nice, but nowadays there are so many factors that can probably trigger false positive when it tests if apt update was already executed or not. 

**Possible solution 2**
simply not run it, and let users now that they should run it prior to install, this could be added to "how to install" section 

```
sudo apt update && sudo apt upgrade && curl -L https://install.pivpn.io | bash
```

**Comment by shelleycat485** [comment]
Same behavior seen on AWS Ubuntu 20.04.  Perhaps run it anyway?

**Comment by 4s3ti** [comment]
Replicated also on AWS Ubuntu 16.04 .. marking as bug

**Comment by 4s3ti** [comment]
Where is why it fails: 

```
ubuntu@ip-172-31-44-17:~$ bash pkcachetest 
stat: missing operand
Try 'stat --help' for more information.
date: invalid date ‘@’
:::
::: apt-get update has not been run today. Running now...
pkcachetest: line 20: spinner: command not found
 done!
```

**Comment by 4s3ti** [comment]
hmm well the function is clearly somewhat broken

```
ubuntu@ip-172-31-44-17:~$ sudo bash pkcachetest 
stat: missing operand
Try 'stat --help' for more information.
date: invalid date ‘@’
:::
::: apt-get update has not been run today. Running now...
Hit:1 http://eu-north-1.ec2.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://eu-north-1.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:3 http://eu-north-1.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease
Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]
Fetched 109 kB in 0s (188 kB/s)                              
Reading package lists... Done
 done!
ubuntu@ip-172-31-44-17:~$ 
ubuntu@ip-172-31-44-17:~$ 
ubuntu@ip-172-31-44-17:~$ sudo bash pkcachetest 
stat: missing operand
Try 'stat --help' for more information.
date: invalid date ‘@’
\:::
::: apt-get update has not been run today. Running now...
Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:2 http://eu-north-1.ec2.archive.ubuntu.com/ubuntu xenial InRelease
Hit:3 http://eu-north-1.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:4 http://eu-north-1.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease
Reading package lists... Done                     
 done!
ubuntu@ip-172-31-44-17:~$ sudo bash pkcachetest 
stat: missing operand
Try 'stat --help' for more information.
date: invalid date ‘@’
:::
::: apt-get update has not been run today. Running now...
Hit:1 http://eu-north-1.ec2.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://eu-north-1.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease                       
Hit:3 http://eu-north-1.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease                     
Hit:4 http://security.ubuntu.com/ubuntu xenial-security InRelease
Reading package lists... Done                     
 done!
```

All were run one after another .. it Runs tough! running script after running that exact same function worked as well ...

**Comment by 4s3ti** [comment]
Removed the redirection to dev/null

```
ubuntu@ip-172-31-47-78:~/pivpn/auto_install$ ./install.sh 
:::
::: sudo will be used for the install.
::: Hostname length OK
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for wget... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for apt-transport-https... already installed!
:::    Checking for iptables-persistent... not installed!
:::    Failed to install iptables-persistent!
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package iptables-persistent
```

For some reason the apt-get update is not running at all and not even sending any output

Deleted the `if` condition and as i suspected the apt update ran without any issues, 

```
updatePackageCache(){
        #Running apt-get update/upgrade with minimal output can cause some issues with
        #requiring user input

        #Check to see if apt-get update has already been run today
        #it needs to have been run at least once on new installs!
        timestamp=$(stat -c %Y ${PKG_CACHE})
        timestampAsDate=$(date -d @"${timestamp}" "+%b %e")
        today=$(date "+%b %e")


        $SUDO ${UPDATE_PKG_CACHE}
}
```
Reuslt:

```
ubuntu@ip-172-31-47-78:~/pivpn/auto_install$ ./install.sh 
:::
::: sudo will be used for the install.
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]
Hit:2 http://eu-north-1.ec2.archive.ubuntu.com/ubuntu xenial InRelease                               
Get:3 http://eu-north-1.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]              
Get:4 http://eu-north-1.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
Get:5 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [1504 kB]
Get:6 http://eu-north-1.ec2.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [7532 kB]
Get:7 http://security.ubuntu.com/ubuntu xenial-security/main Translation-en [356 kB]       
Get:8 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [781 kB]        
Get:9 http://security.ubuntu.com/ubuntu xenial-security/universe Translation-en [222 kB]  
Get:10 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [8232 B] 
Get:11 http://security.ubuntu.com/ubuntu xenial-security/multiverse Translation-en [2888 B]
Get:12 http://eu-north-1.ec2.archive.ubuntu.com/ubuntu xenial/universe Translation-en [4354 kB]
Get:13 http://eu-north-1.ec2.archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages [144 kB]
Get:14 http://eu-north-1.ec2.archive.ubuntu.com/ubuntu xenial/multiverse Translation-en [106 kB]
Get:15 http://eu-north-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [1907 kB]
Get:16 http://eu-north-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/main Translation-en [459 kB]
Get:17 http://eu-north-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [1208 kB]
Get:18 http://eu-north-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/universe Translation-en [352 kB]
Get:19 http://eu-north-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [23.0 kB]
Get:20 http://eu-north-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/multiverse Translation-en [8632 B]
Get:21 http://eu-north-1.ec2.archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [9812 B]
Get:22 http://eu-north-1.ec2.archive.ubuntu.com/ubuntu xenial-backports/main Translation-en [4456 B]
Get:23 http://eu-north-1.ec2.archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [11.3 kB]
Get:24 http://eu-north-1.ec2.archive.ubuntu.com/ubuntu xenial-backports/universe Translation-en [4476 B]
Fetched 19.3 MB in 3s (5859 kB/s)                                 
Reading package lists... Done
::: Hostname length OK
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: There are 49 updates available for your system!
::: We recommend you update your OS after installing PiVPN! 
:::
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for wget... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for apt-transport-https... already installed!
:::    Checking for iptables-persistent... not installed!
:::    Package iptables-persistent successfully installed!
::: Cancel selected, exiting....

```

to be honest i don't think it is worth spending time trying to understand why the if statement fails ... rather just run the `apt-get update` regardless

**Comment by 4s3ti** [comment]
@orazioedoardo any takes about this?

**Comment by TinCanTech** [comment]
Just a hunch:

The `if` condition you removed may be effected by this, from `man apt-get`:

```
-s, --simulate, --just-print, --dry-run, --recon, --no-act
           No action; perform a simulation of events that would occur based on the current system state but do not actually change the system.
           Locking will be disabled (Debug::NoLocking) **so the system state could change** while apt-get is running.
```
** Added emphasis.

As your date stamp is testing the age of the apt directory `PKG_CACHE="/var/lib/apt/lists/"` is it possible that this:
https://github.com/pivpn/pivpn/blob/13f0fe7cbdcdb31537b3fd0e2eb34652e886cc1b/auto_install/install.sh#L428
is updating the directory time stamp ?

**Comment by shelleycat485** [comment]
Since the problem is not when the cache is updated, it is whether the package is available, would this be a solution.  I have only seen the problem with iptables-persistent, so test for that package:

`#!/bin/bash`
`apt-cache show iptables-persistent`
`if [ $? = 100 ]; then`
`        echo "not available, needs apt-get"`
`        sudo apt-get update`
`        apt-cache show iptables-persistent`
`        if [ $? = 0 ]; then`
`                echo "ok, its available now"`
`        fi`
`fi`

**Comment by orazioedoardo** [comment]
@TinCanTech However `notifyPackageUpdatesAvailable()` runs after `updatePackageCache()`.

@4s3ti @shelleycat485 Can you check the timestamp of `stat -c %Y /var/lib/apt/lists/` on a clean install?

**Comment by TinCanTech** [comment]
> @TinCanTech However `notifyPackageUpdatesAvailable()` runs after `updatePackageCache()`.

Yes, as per this log:
> Removed the redirection to dev/null
> 
> ```
> ubuntu@ip-172-31-47-78:~/pivpn/auto_install$ ./install.sh 
> :::
> ::: sudo will be used for the install.
> ::: Hostname length OK
> ::: Verifying free disk space...
> :::
> ::: **Checking apt-get for upgraded packages.... done!**
> :::
> ::: **Your system is up to date! Continuing with PiVPN installation...**
> :::    Checking for git... already installed!
> :::    Checking for tar... already installed!
> :::    Checking for wget... already installed!
> :::    Checking for curl... already installed!
> :::    Checking for grep... already installed!
> :::    Checking for dnsutils... already installed!
> :::    Checking for whiptail... already installed!
> :::    Checking for net-tools... already installed!
> :::    Checking for bsdmainutils... already installed!
> :::    Checking for apt-transport-https... already installed!
> :::    Checking for iptables-persistent... not installed!
> :::    Failed to install iptables-persistent!
> Reading package lists...
> Building dependency tree...
> Reading state information...
> E: Unable to locate package iptables-persistent
> ```
> 
> For some reason the apt-get update is not running at all and not even sending any output
> 
> Deleted the `if` condition and as i suspected the apt update ran without any issues,

 `if [ ! "${today}" == "${timestampAsDate}" ]; then`
	
The `if` condition evaluates that `${today}"` is equal to `"${timestampAsDate}"`

`today=$(date "+%b %e")` -- This is correctly evaluated to today in the form: `Jan 1'
timestampAsDate=$(date -d @"${timestamp}" "+%b %e")` -- This is correctly evaluated to the date of the directory in the form: `Jan 1`
`timestamp=$(stat -c %Y ${PKG_CACHE})` -- This returns the correct value for the date stamp of the directory in the form: `seconds since epoch`

However, from the log above:
`::: **Checking apt-get for upgraded packages.... done!**`
This does the following:
`updatesToInstall=$(eval "${PKG_COUNT}")`
This does the following:
`PKG_COUNT="${PKG_MANAGER} -s -o Debug::NoLocking=true upgrade | grep -c ^Inst || true"`
Which effectively runs:
`apt-get -s -o Debug::NoLocking=true upgrade`
And `man apt-get` we find:
```
-s, --simulate, --just-print, --dry-run, --recon, --no-act
           No action; perform a simulation of events that would occur based on the current system state but do not actually change the system.
           Locking will be disabled (Debug::NoLocking) **so the system state could change** while apt-get is running.
```
Clearly, if the two dates of ${TODAY} and "${timestampAsDate}" are equal then `apt-get` has been run. However, it has not been run correctly, it has only been simulated but that simulated run was enough to update the directory time stamp and therefore fool the script into deciding that `apt-get` has been run today to completion when, in fact, it has not.

**Comment by shelleycat485** [comment]
On AWS Ubuntu 20.04, new install
-s does not seem to work at all with update which means it does nothing:  The directory tiemstamp does not change under these conditions

`ubuntu@ip-10-66-0-170:~$ stat -c %Y /var/lib/apt/lists/`
`1608222458`
`ubuntu@ip-10-66-0-170:~$ sudo apt-get -s update`
`E: Command line option 's' [from -s] is not understood in combination with the other options.`
`ubuntu@ip-10-66-0-170:~$ sudo apt-get --dry-run update`
`E: Command line option --dry-run is not understood in combination with the other options`
`ubuntu@ip-10-66-0-170:~$ sudo apt-get -s upgrade`
`Reading package lists... Done`
`Building dependency tree`
`Reading state information... Done`
`Calculating upgrade... Done`
`0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`
`ubuntu@ip-10-66-0-170:~$ stat -c %Y /var/lib/apt/lists/`
`1608222458`
`ubuntu@ip-10-66-0-170:~$ `

**Comment by TinCanTech** [comment]
> On AWS Ubuntu 20.04, new install
> -s does not seem to work at all with update which means it does nothing: The directory tiemstamp does not change under these conditions

AWS may simply disable this on account of bandwidth, etc.

**Comment by rjblake** [comment]
Similar/same problem occurs trying to install in Ubuntu 20.04.1 LTS 64-bit running on Raspberry Pi4. Manually installed a number of the packages (starting with the iptables-persistent failure). It does install to completion, but still has a number of errors (unfortunately didn't capture the details/log). I may do a fresh install as busy setting up for various requirements.

**Comment by orazioedoardo** [comment]
@rjblake The test branch properly shows the apt/dpkg error log on ubuntu, you should try that.

**Comment by rjblake** [comment]
@orazioedoardo - I checked the /var/log/apt files and nothing of use there. I may have a log from the terminal, as the errors came later in the install process. Also, once the GUI section appeared, other issues. Best to do uninstall and try do it all again perhaps for full info

**Comment by 4s3ti** [comment]
Submitting MR with fix for this in a while

**Comment by rjblake** [comment]
Found the details from a previous session I had saved. Including here in case relevant (can't sort formatting, sorry)
`ubuntu@ubuntu:~$ sudo apt update && sudo apt upgrade && curl -L https://install.pivpn.io | bash
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease                    
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease                                                   
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease                                                    
Hit:5 https://download.docker.com/linux/ubuntu focal InRelease                                   
Ign:6 https://ookla.bintray.com/debian generic InRelease                                         
Get:7 https://ookla.bintray.com/debian generic Release [4389 B]
Fetched 4389 B in 2s (1995 B/s)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0   1012      0 --:--:-- --:--:-- --:--:--  1012
100 83088  100 83088    0     0   221k      0 --:--:-- --:--:-- --:--:--  221k
:::
::: sudo will be used for the install.
::: Hostname length OK
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for wget... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... not installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for iptables-persistent... already installed!
/usr/bin/debconf-apt-progress: can't open /tmp/tmp.v4UQEpaILw: Permission denied at /usr/bin/debconf-apt-progress line 249, <STDIN> line 3.
                                                                                                                                           :::    Failed to install dnsutils!
ubuntu@ubuntu:~$ sudo apt install dnsutils
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  dnsutils
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 2752 B of archives.
After this operation, 46.1 kB of additional disk space will be used.
Get:1 http://ports.ubuntu.com/ubuntu-ports focal-updates/universe arm64 dnsutils all 1:9.16.1-0ubuntu2.4 [2752 B]
Fetched 2752 B in 0s (26.0 kB/s)   
Selecting previously unselected package dnsutils.
(Reading database ... 106196 files and directories currently installed.)
Preparing to unpack .../dnsutils_1%3a9.16.1-0ubuntu2.4_all.deb ...
Unpacking dnsutils (1:9.16.1-0ubuntu2.4) ...
Setting up dnsutils (1:9.16.1-0ubuntu2.4) ...
ubuntu@ubuntu:~$ curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    993      0 --:--:-- --:--:-- --:--:--  1000
100 83088  100 83088    0     0   222k      0 --:--:-- --:--:-- --:--:--  222k
:::
::: sudo will be used for the install.
::: Hostname length OK
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for wget... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for iptables-persistent... already installed!
/usr/bin/debconf-apt-progress: can't open /tmp/tmp.UQxNanszOg: Permission denied at /usr/bin/debconf-apt-progress line 249, <STDIN> line 3.
                                                                                                                                           ::: Using User: ubuntu
:::
::: Checking for existing base files...
:::    Checking /usr/local/src/pivpn is a repo...:::    Cloning https://github.com/pivpn/pivpn.git into /usr/local/src/pivpn... done!
::: Using VPN: WireGuard
::: Installing WireGuard... 
:::    Checking for wireguard-tools... already installed!
:::    Checking for qrencode... not installed!
/usr/bin/debconf-apt-progress: can't open /tmp/tmp.OEuoxfCQ1c: Permission denied at /usr/bin/debconf-apt-progress line 249, <STDIN> line 3.
                                                                                                                                           :::    Failed to install qrencode!
ubuntu@ubuntu:~$ sudo apt install qrencode
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libqrencode4
The following NEW packages will be installed:
  libqrencode4 qrencode
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 46.1 kB of archives.
After this operation, 129 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://ports.ubuntu.com/ubuntu-ports focal/universe arm64 libqrencode4 arm64 4.0.2-2 [23.0 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports focal/universe arm64 qrencode arm64 4.0.2-2 [23.1 kB]
Fetched 46.1 kB in 0s (289 kB/s)   
Selecting previously unselected package libqrencode4:arm64.
(Reading database ... 106200 files and directories currently installed.)
Preparing to unpack .../libqrencode4_4.0.2-2_arm64.deb ...
Unpacking libqrencode4:arm64 (4.0.2-2) ...
Selecting previously unselected package qrencode.
Preparing to unpack .../qrencode_4.0.2-2_arm64.deb ...
Unpacking qrencode (4.0.2-2) ...
Setting up libqrencode4:arm64 (4.0.2-2) ...
Setting up qrencode (4.0.2-2) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.1) ...
ubuntu@ubuntu:~$ curl -L https://install.pivpn.io | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    936      0 --:--:-- --:--:-- --:--:--   931
100 83088  100 83088    0     0   173k      0 --:--:-- --:--:-- --:--:--  173k
:::
::: sudo will be used for the install.
::: Hostname length OK
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
:::    Checking for git... already installed!
:::    Checking for tar... already installed!
:::    Checking for wget... already installed!
:::    Checking for curl... already installed!
:::    Checking for grep... already installed!
:::    Checking for dnsutils... already installed!
:::    Checking for whiptail... already installed!
:::    Checking for net-tools... already installed!
:::    Checking for bsdmainutils... already installed!
:::    Checking for iptables-persistent... already installed!
/usr/bin/debconf-apt-progress: can't open /tmp/tmp.QgrIcDgz3c: Permission denied at /usr/bin/debconf-apt-progress line 249, <STDIN> line 3.
                                                                                                                                           ::: Using User: ubuntu
:::
::: Checking for existing base files...
:::    Checking /usr/local/src/pivpn is a repo... OK!
:::     Updating repo in /usr/local/src/pivpn... done!
::: Using VPN: WireGuard
::: Installing WireGuard... 
:::    Checking for wireguard-tools... already installed!
:::    Checking for qrencode... already installed!
/usr/bin/debconf-apt-progress: can't open /tmp/tmp.9yD6h6aveG: Permission denied at /usr/bin/debconf-apt-progress line 249, <STDIN> line 3.
                                                                                                                                           ::: Using CloudFlare servers.
::: Adding additional reload job type for wg-quick unit
::: Backing up the wireguard folder to /etc/wireguard_2021-01-12-005727.tar.gz
::: Server Keys have been generated.
::: Server config generated.
::: Install Complete...
::: Restarting services...
Job for wg-quick@wg0.service failed because the control process exited with error code.
See "systemctl status wg-quick@wg0.service" and "journalctl -xe" for details.
:::    Checking for unattended-upgrades... already installed!
/usr/bin/debconf-apt-progress: can't open /tmp/tmp.YCpKllvrU8: Permission denied at /usr/bin/debconf-apt-progress line 249, <STDIN> line 3.
                                                                                                                                           ::: Setupfiles copied to /etc/pivpn/wireguard/setupVars.conf
::: Installing scripts to /opt/pivpn...
 done.
::: Flushing writes to disk...
::: done.
:::
`

Regards final errors, following:
`Jan 13 00:57:34 ubuntu systemd-resolved[1625]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.
Jan 13 00:57:34 ubuntu systemd-resolved[1625]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.
Jan 13 00:57:34 ubuntu sudo[55388]:   ubuntu : TTY=pts/1 ; PWD=/home/ubuntu ; USER=root ; COMMAND=/usr/bin/systemctl status wg-quick@wg0.service
Jan 13 00:57:34 ubuntu sudo[55388]: pam_unix(sudo:session): session opened for user root by ubuntu(uid=0)
Jan 13 00:57:34 ubuntu sudo[55388]: pam_unix(sudo:session): session closed for user root
`

`Jan 12 00:57:33 ubuntu systemd[1]: Starting WireGuard via wg-quick(8) for wg0...
Jan 12 00:57:33 ubuntu wg-quick[49356]: wg-quick: `wg0' already exists
Jan 12 00:57:33 ubuntu systemd[1]: wg-quick@wg0.service: Main process exited, code=exited, status=1/FAILURE
Jan 12 00:57:33 ubuntu systemd[1]: wg-quick@wg0.service: Failed with result 'exit-code'.
Jan 12 00:57:33 ubuntu systemd[1]: Failed to start WireGuard via wg-quick(8) for wg0.
Jan 12 09:54:02 ubuntu systemd[1]: wg-quick@wg0.service: Unit cannot be reloaded because it is inactive.
Jan 12 09:56:11 ubuntu systemd[1]: wg-quick@wg0.service: Unit cannot be reloaded because it is inactive.`

**Comment by 4s3ti** [comment]
edited your comment and formated it .. was really painful to look at it :D

**Comment by 4s3ti** [comment]
Fixed, Merged into master: https://github.com/pivpn/pivpn/commit/b5ec995f68fbae2eb30b50e1b6a4350f96316f2e
