### ISSUE TITLE
[Support-Question] Security of config file Wireguard

### ISSUE THREAD

**Issue by Vannixxo** [pivpn/pivpn#1222]
Not quite a support request, but more of a question.
Given that WireGuard VPN relies on key exchange and not a username/password layer of added security, does this means that I would be better storing config file for clients in e.g. 1password and deleting them from anywhere else? (Pi itself, and iCloud Drive if I used it to import the config into iOS Wireguard app) As I suppose that anyone with the config file could connect into my local network?

Anyway thinking about switching to OpenVPN as I discovered that bridge mode is fundamental to access remote printers with AirPrint and samba shares (time machine), for the rest... thanks a lot for this amazing project as it is very straightforward and working beautifully!

**Comment by orazioedoardo** [comment]
> Given that WireGuard VPN relies on key exchange and not a username/password layer of added security

The WireGuard `PrivateKey` is much more secure than a username/password combo, the latter can be bruteforced.

> does this means that I would be better storing config file for clients in e.g. 1password and deleting them from anywhere else? 

Just configure every client and then delete any .conf laying around, except on the Pi itseft, since a compromised Pi can be used to generate new configurations. Note that to provision smartphone you can use `pivpn qrcode` instead of copying files.

**Comment by Vannixxo** [comment]
Thanks so much for the explanation!
