### ISSUE TITLE
can't ping client from server

### ISSUE THREAD

**Issue by drmarian** [pivpn/pivpn#123]
Hi, need help.
vpn works fine., client on Windows.
I'd like to see client from servers LAN side. How to do it?

Best regards

**Comment by redfast00** [comment]
@drmarian: what exactly do you want? A list of connected clients? Connecting to ports on the client machine?

**Comment by drmarian** [comment]
I would like to use Samba share  installed on "VPN Client" from "VPN server" side LAN.

**Comment by redfast00** [comment]
@drmarian: I'm not sure this is even possible with OpenVPN.

**Comment by cfcolaco** [comment]
@redfast00 @0-kaladin 

Getting back to housekeeping! =) 

Theoretically is possible to do it from the server side, so from the client side it should be also possible, this is the kind of thing that might require some tweaking to work. 

As this issue is almost doing one here without any new update in it. I am going to close it, however, Here are some references for us in the feature if any similar issue appears. 

https://askubuntu.com/questions/751034/how-do-i-share-samba-via-open-vpn-is-that-possible
https://askubuntu.com/questions/743105/samba-over-openvpn
https://ubuntuforums.org/showthread.php?t=1819072

This is also the kind of thing that I might have the answer for in a couple of months since I am rebuilding all my home network and "cloud" infrastructure!
