### ISSUE TITLE
problem with .ovpn file 

### ISSUE THREAD

**Issue by davideser** [pivpn/pivpn#1286]
Hi, I installed pivpn on my raspberry.e pi 4, I don't understand why it doesn't generate the .ovpn file for me but just the config file.

<img width="767" alt="Schermata 2021-03-26 alle 01 21 23" src="https://user-images.githubusercontent.com/47193260/112560053-9e18b500-8dd2-11eb-85a5-8a76b37a18bf.png">

**Comment by 4s3ti** [comment]
Hi, I'd suggest you to read the documentation at https://docs.pivpn.io/ to me it seems clearly that you haven't read any! 

lease be more clear when opening an issue and provide as much details as you can! 

1 - What are you really trying to accomplish? 
2 - That message suggests me that you have installed wireguard instead of openvpn and wireguard works with config files, which in your case is being added at /home/pi/configs.

This being said i am closing the issue, 
Feel free to reopen it following the instructions provided. 

Kind regards.

**Comment by davideser** [comment]
I want to use my raspberry as a private VPN. I followed the documentation, but at the end of the process I get only .conf, no ..ovpn file

**Comment by 4s3ti** [comment]
as i say .. seems to me you installed Wireguard instead of OpenVPN ... please fill the issue template for support cases and reopen the issue.

**Comment by davideser** [comment]
Thank you guys for the support.I solved my mistake.
