### ISSUE TITLE
[Support] How to renew a expired certificate or how to delete a client

### ISSUE THREAD

**Issue by GeanyBezna** [pivpn/pivpn#1311]
Unfortunately I was unable to find a method on how to completely delete a client from the server or how to renew a certificate

Would you be so kind to provide me with the necessary steps to renew a expired certificate? Or at least, how to completely delete a client from the VPN Server?

**Comment by shelleycat485** [comment]
If you are using wireguard; "pivpn remove"  appears to delete the client config.  After that, the client cannot connect to the server.

Using ovpn, the only way I know of renewing an expired certificate is to generate a new certificate, then apply that in the client.  Again, remove should remove the older expired configuration - since it was expired it is not going to work anyway.

**Comment by orazioedoardo** [comment]
Adding to what @shelleycat485 said, you make the server forget about an expired or revoked client because the server needs to know that such client must not be allowed to connect.

**Comment by orazioedoardo** [comment]
No responses in a while, closing...
