### ISSUE TITLE
[BUG] <choosing user error>

### ISSUE THREAD

**Issue by Tyreese01** [pivpn/pivpn#1319]
I seem to be having a problem when choosing a user to run the vpn on. I am following a youtube tutorial and this is the part where I get stuck (I will put the link to the video with additional context). 
I have tried it twice, then updated my raspberry pi' os. Then I tried again after the update and it still didn't work.

Additional context: 
https://www.youtube.com/watch?v=15VjDVCISj0

**Comment by 4s3ti** [comment]
Dear user, That video is from March 2019, over 2 years now and a few things have changed since!

Even though we love the fact you are using pivpn, the maintainers of this project keep answering the same thing over and over again.

This might feel a bit rude or not friendly, but we keep spending time not only on the project that makes your life so great but also on documentation that you seemed to have not read at all therefore this issue is being closed. 

Don't know why your issue got closed? 

You can start by reading here: https://docs.pivpn.io 
And here: https://www.pivpn.io/#contrib
And here: https://github.com/pivpn/pivpn/blob/master/README.md
And here: https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md

and the first lines on the issue template that appeared after you have pressed all those green buttons to open up this issue: 

```
<!-- 
# PiVPN Issue Template
PLEASE READ THIS TEMPLATE CAREFULLY BEFORE OPENING AN ISSUE! 
Any Issue opened that doesn't follow this template will be removed.
```

Still not happy? 

Feel free to express yourself but most likely our position won't change, and hopefully you have now learned how to open an issue anywhere in the opensource community! 


Wish you a great day, feel free to reopen this issue but this time make sure it follows the rules!
