### ISSUE TITLE
[BUG] Wireguard - "unable to import tunnel. Unknown section in config"

### ISSUE THREAD

**Issue by timdonovanuk** [pivpn/pivpn#1323]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**

- Clean basic install. 
- Add wireguard config. 
- Use qr command to show QR.
- Scan using QR code on Android app. 
- WireGuard client reports "unable to import tunnel. Unknown section in cofig"

**Screenshots**

**Smartphone (please complete the following information):**

 - Device: Samsung S20

**Additional context**

Here is my client config:

![image](https://user-images.githubusercontent.com/8156439/121747872-f624a500-caff-11eb-95ae-e96a6bf36d72.png)

For what it's worth, here is another client config from using another tool to generate a known working and good config that worked on my phone:

![image](https://user-images.githubusercontent.com/8156439/121748012-3126d880-cb00-11eb-836e-df71cf053dbf.png)

**Comment by timdonovanuk** [comment]
OK yep that was it. Kinda sucks had to install an ssh-server just to correctly output the QR code (wireguard endpoint sits on a bastion server so the less services the better!) but I can understand why!

**Comment by timdonovanuk** [comment]
Okay also a default debian install doesn't come with iptables in the system $PATH so this entire thing doesnt work! Only once you add it to the system path and run pivpn -d does it fix things...

**Comment by asantoni** [comment]
This error message can also be caused by incorrect usage of the qrencode command. If you're like me and just you spent the last 30 minutes hitting your head against the wall, it's because you ran:

`qrencode -t ansiutf8 client.conf`

when you should have actually run:

`qrencode -t ansiutf8 < client.conf`

The first one is incorrectly generating a QR code of just the filename itself, which is why the Wireguard Android and iOS apps give an error message. The latter (correct) command encodes the contents of the file, and should give you a much larger looking QR code that works! 

I'm leaving this comment here because this pretty much the only search result on Google for "unknown section in config", which is the error message you get. (and this might have been OP's actual mistake) Hope this helps someone.
