### ISSUE TITLE
osmc implementation

### ISSUE THREAD

**Issue by luckymedog** [pivpn/pivpn#139]
How difficult would it be to adjust this script to install in OSMC.

**Comment by redfast00** [comment]
@luckymedog we currently don't support OSMC since it's a media center. It's based on Debian, so it shouldn't be too hard to port this over (you will probably have to bypass the OS checks [here](https://github.com/pivpn/pivpn/blob/master/auto_install/install.sh#L57) ). Let me know if you succeed :smiley:
