### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by Tsutsukakushi** [pivpn/pivpn#16]
Please for the love of god don't claim any kind of security if your recommended installing method is `curl -L http://install.pivpn.io | bash`.

Even a retard would know that's a stupid thing to do.

**Comment by 0-kaladin** [comment]
Not sure where your problem is with it but I have responses no matter what angle you are coming from.  If you have an issue with the url not being over SSL, then that is a temporary trade off I'm making to keep the [site hosted](https://github.com/pivpn/pivpn.github.io) on github.  I'm not a web guy and spent about 2 minutes getting that up and would welcome contributions.  Github can't do SSL so for the time being its an http URL.  
However, I don't believe that was the crux of your problem, my guess is just curling any script you have an issue with.  You do know that you can run
`curl -v http://install.pivpn.io` without piping through bash to see what the curl command is grabbing?  If you knew that then you might have also discovered it is a 302 redirect to `https://raw.githubusercontent.com/pivpn/pivpn/master/auto_install/install.sh`
which as it happens is available for you to look at and inspect right here.  So if you can see exactly what the command you will run is executing and the contents of that script, then no, it is not a stupid thing to do.  
Further, the only security I claimed is what is gained when you are not technical enough to get openvpn running on your own but because of a freely available script that you can execute, are now able to run secured connections to your tunnel endpoint.  
I'm not going to slander anyone with any disabilities but the only thing going on that is by definition retarded, is the logic you are using in your statements.

**Comment by Tsutsukakushi** [comment]
> You do know that you can run `curl -v http://install.pivpn.io` without piping through bash to see what the curl command is grabbing?

Yes. I know that, however that won't do much good if it's run automatically. You shouldn't encourage people to automatically run any scripts from the internet.

> Further, the only security I claimed is what is gained when you are not technical enough to get openvpn running on your

You are lessening the security of these people, not strenghtening it.
