### ISSUE TITLE
Request: Always offer to download DH param from 2ton.com.au

### ISSUE THREAD

**Issue by fyellin** [pivpn/pivpn#169]
Small request.

Building the DH prime, even for 2048 bits, is very slow, and sometimes takes more than 30minutes.  Downloading a shared DH prime that is only going to be used by a few sites is more than enough safety for most cases.    The existing bug is that the same prime is used by *millions* of sites.

The user is given the option of not creating their own DH prime for 4096 bits (or greater, if that is ever supported.)  I'd like to change this to "always".

**Comment by 0-kaladin** [comment]
I don't like the idea of downloading at all.  I have 2 main goals for this project, one is simplicity, and the second is offering the install and resultant openvpn server with the highest grade of security/hardening.  Generally you are installing ONCE and then will have this server for a long time.  Sitting around for a half hour to generate your own DH prime isn't a big deal to me or a large ask of the user vs potential risks of downloading one.  When a user is installing we don't know how safe/secure their network is, I don't fully trust the site we are downloading the primes from ,etc.  The option is there for 4096 only and with the disclaimer message for those reasons.
I really don't intend on changing that.  
I do understand we can argue how safe/secure it is, my point is that there is no reason to even take that risk no matter how minimal in this case.  Mainly because, you are doing this once.  Take the time.

**Comment by redfast00** [comment]
@fyellin: if you really want this, you can clone this repo, change it in the code and then curl your version of PiVPN. We probably won't accept a PR that includes this though.

**Comment by fyellin** [comment]
You answered my question.

I've been manually modifying the .sh script by hand.  I purposely opened
the issue because I wanted to know if the change would be accepted.  The
answer is "no", and I completely understand why.    I've either been
downloading the DH key, or generating it on a more powerful machine and
scp-ing it over.

I thought the reason was that somehow you didn't trust a DH key that was
also used by someone else.  There a millions of sites all using the same
1024-bit DH key, and if that key has been broken, it's been by the NSA or
another state actor.  But not trusting the site you're getting the key from
makes a lot more sense.

Perhaps a different change that needs to be made is if the user *does*
download, then also run:
       openssl dhparam -check -in /etc/openvpn/easy-rsa/pki/dh${ENCRYPT}.pem
to do the basic sanity check.

In any case, thanks for the quick response.  And the great product.

**Comment by 0-kaladin** [comment]
check is a good suggestion.  Not helpful for security really but since we are downloading would ensure no corruption on downloaded file since it checks for valid p and g.

**Comment by 0-kaladin** [comment]
...also per the original comments, if you know you don't want to take the time to generate a dh prime, then just pick the 4096 option and download that one.  since downloading is instant in any case why download the 2048 vs 4096.  unless you feel the performance impact will be noticeable.

**Comment by redfast00** [comment]
Ehm, I read something in the 2ton website that verifying might not work. Am on mobile, so will link it later.

**Comment by fyellin** [comment]
You are correct.   2ton does say that verification may not work because of
a difference of opinion about quadratic residues.
