### ISSUE TITLE
Add ssl to pivpn.io

### ISSUE THREAD

**Issue by rothgar** [pivpn/pivpn#17]
Please use [Let's Encrypt](https://letsencrypt.org/) or similar service to pivpn.io so curling the script can be secure and not intercepted/modified when installing. Internet scripts are scary enough, doing it over http in plain text is very worrisome.

**Comment by 0-kaladin** [comment]
I completely agree and will do this.  But not yet.  
I wanted to host this off of github for some time because I'm not a front end web guy and I want some contributions there to make pivpn.io the best it can be.  You'll see it is just another project here in the pivpn organization https://github.com/pivpn/pivpn.github.io
Unfortunately when hosting it at github I can't get it over ssl.  
This isn't a a major deal, as the install.pivpn.io is redirected to https://raw.githubusercontent.com/pivpn/pivpn/master/auto_install/install.sh
so if you were concerned your traffic was being intercepted you could curl that instead.  Remember I assume this is being run from people's homes, where if their traffic is being intercepted and modified they have larger issues (such as all their logins to sites).  IE, this isn't being run from a public hotspot.  

Excuses aside, I completely agree as this was a design goal from the start I just want some web design person to contribute ;)

So I'll leave this issue open until I move the site to one of my server where I'll setup the root of the site to maybe be the master branch of the github that i can git pull to update.  I can create a test branch that maybe has a host at test.pivpn.io.  All on the todo list and when i set it up, it'll get an A+ from SSL Labs.

**Comment by DavidOliver** [comment]
Hi! I'm no expert, but I'm not seeing the logic behind delaying securing of the transport of the site and install redirecter until a web page is further designed.

Separate to that, even if you happen to be right about the install script never being run when traffic is being intercepted and/or about people going looking for the TLS-secured Github page, it would simply give a better impression to those who look out for such things.

Anyway, thanks for making pivpn available! I hope to try it out soonish.

What are you looking for in the way of the website - tweaking what's there or something new?

**Comment by 0-kaladin** [comment]
Stop making sense... it's making me do more things.

**Comment by 0-kaladin** [comment]
RE: What are you looking for for the website - tweaking what's there or something new?
Anything really.  Tweaking what's there with better verbiage, some nice assets, etc. or entirely something new, I'm open!

**Comment by 0-kaladin** [comment]
oh and for now I still didn't move the hosting of the site. pivpn.io is still hosted at github.  I just have install.pivpn.io on one of my servers so I could get a cert and do the redirect myself (instead of via registrar).

**Comment by DavidOliver** [comment]
Sweet!

Re. site, good to know. I'm away from my desk for a week but will have another look after I've tried PiVPN out in case I can help. I've been thinking I'd like to do a site for an open source project for a while.
