### ISSUE TITLE
4096 Diffie Hellman doesn't work on Android

### ISSUE THREAD

**Issue by pants78** [pivpn/pivpn#177]
Hello,

Love PIVPN. It's the bees knees. Works flawless with 4096 bit DH with Windows. My issue is it doesn't want to work on Android with the OpenVPN Connect app.  I have used the same config file with Windows and Android during testing.  Windows works, Android does not.  Error message from Android app:

PolarSSL: error parsing config private key : PK - Bad input parameters to function

A little Googling leads me to answers like "change to 2048" 
Just installed PIVPN 2 days ago Dec 25. 

Any suggestions?  
Thanks,
Pants

**Comment by 0-kaladin** [comment]
What about with the openvpn app from arne schwabe . That's the better one. Called openvpn for Android

**Comment by fyellin** [comment]
The OpenVPN wiki page on openvpn hardening claims:

> Up to 4096-bit is accepted by nearly all RSA systems (including OpenVPN,) but use of keys this large will dramatically increase generation time, TLS handshake delays, and CPU usage for TLS operations; the benefit beyond 2048-bit keys is small enough not to be of great use at the current time. It is often a larger benefit to consider lower validity times than more bits past 2048, but that is for you to decide. https://community.openvpn.net/openvpn/wiki/Hardening

Unless you suspect that the NSA or a similar government agency is after your network, 4096 bits is probably way beyond your security requirements.  If being able to use Android is really important to you, you may just have to use 2048 bits.  The current attacks are because millions of sites are all using the identical 1024-bit DH key.  You are not susceptible to this attack.

But like the text says, that's for you to decide.

Note also that once 4096-bit DH keys become available on Android, it'll be easy for you to replace your 2048-bit key with a 4096-bit key. The dh parameter used by the server is in `/etc/openvpn/easy-rsa/pki/dh<bits>.pem`.   Change the line in `/etc/openvpn/server.conf` that starts with "dh" and change it to point to your dh4096.pem file instead of your dh2048.pem file.  The client gets the dh info from the server, so client files don't require any change.

**Comment by pants78** [comment]
Thanks for the suggestion 0-kaladin .  OpenVPN for Andriod from Arne Schwabe works perfectly with my existing config.  It's not that I'm paranoid, doing anything I shouldn't, or being followed by a government agency (to my knowledge!) its simply what I chose during setup and I'm too lazy to want to try and change if I don't have to. 

I had no idea the Andriod apps would function differently, so I have learned something new and hopefully saved someone else a bit of a headache with this thread. 

Cheers!

**Comment by fyellin** [comment]
0-kaladin's solution is much better than mine!  

Swapping in new DH parameters is easy, though.  If you ever decide that the start-up time on the Android is too slow,  you can easily change the DH key without reinstalling openvpn or changing any client configurations.   Some people even choose 3072-bit keys as a reasonable compromise between security and speed.
