### ISSUE TITLE
dhcpcd5 dependency breaks Pi OS Bookworm

### ISSUE THREAD

**Issue by Soriiin** [pivpn/pivpn#1774]
### In raising this issue I confirm that

- [X] I have read the [documentation](https://docs.pivpn.io)
- [X] I have read and understood the [PiVPN General Guidelines](https://github.com/pivpn/pivpn/#general-guidelines)
- [X] I have read and understood the [PiVPN Troubleshooting Guidelines](https://docs.pivpn.io/faq/#how-do-i-troubleshoot-connection-issues)
- [X] The issue I am reporting isn't a duplicate, see [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen).
- [X] I have searched for similar issues and solutions
- [X] I can replicate the issue even after a clean OS installation

### Describe the issue

The latest release of Pi OS is based on Debian Bookworm. This version has switched from dhcpcd to network-manager: https://www.raspberrypi.com/news/bookworm-the-new-version-of-raspberry-pi-os/

The PiVPN installation of the base dependency dhcpcd5 (install.sh line 579: `BASE_DEPS+=(dhcpcd5)`) forces the removal of several core Pi OS packages: `pi-bluetooth piwiz raspberrypi-sys-mods raspberrypi-ui-mods rpd-plym-splash userconf-pi`

```
The following packages will be REMOVED:
  pi-bluetooth piwiz raspberrypi-sys-mods raspberrypi-ui-mods rpd-plym-splash userconf-pi
```

This breaks the normal functioning of the OS.

The script installs this dependency at line 786 by generating the command: `sudo apt-get --yes --no-install-recommends install dnsutils grepcidr bsdmainutils dhcpcd5 iptables-persistent` from `${SUDO} ${PKG_INSTALL} "${TO_INSTALL[@]}"`

Checking the dhcpcd5 package:
```
user@raspberrypi:~ $ sudo apt satisfy dhcpcd5
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 raspberrypi-sys-mods : Breaks: dhcpcd5 (< 1:8.1.2-1+rpt2) but 9.4.1-24~deb12u2 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

Removing dhcpcd5 from BASE_DEPS no longer targets those OS packages for removal but breaks the install.sh script.

### Expected behavior

The normal functioning of the OS must not be affected by the installation of PiVPN.

The script must support both the legacy distros and the new the Bookworm-based Raspberry Pi OS distro.

### Please describe the steps to replicate the issue

1) Create a bootable SD card with "Raspberry Pi OS Full (64-bit)" Released: 2023-10-10
2) Boot from the card and install the OS, along with all the updates
3) Open a terminal and run the standard PiVPN install script: `curl -L https://install.pivpn.io | bash`
4) Notice that the install script decides it will have to remove several core Pi OS packages, before it pops up the Welcome screen
5) Finish the PiVPN installation and reboot
6) Notice that the login screen is now no longer Pi OS themed and that your login is rejected

### Have you taken any steps towards solving your issue?

No quick solution is possible because the script is heavily reliant on dhcpcd.

### Screenshots

![bookworm_login](https://github.com/pivpn/pivpn/assets/37666374/3e1c7c36-cab1-4c32-87c3-719681f7304d)

### Where did you run pivpn?

Raspberry Pi 4 B 8GB

### Please provide your output from `uname -a`

`Linux raspberrypi 6.1.0-rpi4-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.54-1+rpt2 (2023-10-05) aarch64 GNU/Linux`

### Details about Operative System

```
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
### Installation

```
The following packages will be REMOVED:
  pi-bluetooth piwiz raspberrypi-sys-mods raspberrypi-ui-mods rpd-plym-splash userconf-pi
```

### Debug output

```
::: Generating Debug Output
::::            PiVPN debug              ::::
=============================================
::::            Latest commit            ::::
Branch: master
Commit: f9ae9662ecc49896d09cdb38e177d2efa90e7119
Author: camdenAR
Date: Thu Oct 19 18:56:19 2023 -0500
Summary: fix(scripts): Match full client name when disabling
=============================================
::::        Installation settings        ::::
PLAT=Debian
OSCN=bookworm
USING_UFW=0
IPv4dev=wlan0
IPv6dev=wlan0
dhcpReserv=1
IPv4addr=CENSORED
IPv4gw=CENSORED
install_user=CENSORED
install_home=/home/CENSORED
VPN=wireguard
pivpnPORT=CENSORED
pivpnDNS1=CENSORED
pivpnDNS2=CENSORED
pivpnHOST=REDACTED
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
INPUT_CHAIN_EDITEDv6=0
FORWARD_CHAIN_EDITEDv6=0
pivpnPROTO=udp
pivpnMTU=1420
pivpnDEV=wg0
pivpnNET=CENSORED
subnetClass=24
pivpnenableipv6=1
pivpnNETv6="CENSORED"
subnetClassv6=64
ALLOWED_IPS="0.0.0.0/0, ::0/0"
UNATTUPG=1
INSTALLED_PACKAGES=(dnsutils grepcidr bsdmainutils dhcpcd5 iptables-persistent wireguard-tools qrencode unattended-upgrades)
=============================================
::::  Server configuration shown below   ::::
[Interface]
PrivateKey = server_priv
Address = CENSORED,CENSORED
MTU = 1420
ListenPort = CENSORED
=============================================
::::  Client configuration shown below   ::::
::: There are no clients yet
=============================================
::::    Recursive list of files in       ::::
::::    /etc/wireguard shown below       ::::
/etc/wireguard:
configs
keys
wg0.conf

/etc/wireguard/configs:
clients.txt

/etc/wireguard/keys:
server_priv
server_pub
=============================================
::::            Self check               ::::
:: [OK] IP forwarding is enabled
:: [OK] Iptables MASQUERADE rule set
:: [OK] WireGuard is running
:: [OK] WireGuard is enabled
(it will automatically start on reboot)
:: [OK] WireGuard is listening on port CENSORED/udp
=============================================
:::: Having trouble connecting? Take a look at the FAQ:
:::: https://docs.pivpn.io/faq
=============================================
:::: WARNING: This script should have automatically masked sensitive       ::::
:::: information, however, still make sure that PrivateKey, PublicKey      ::::
:::: and PresharedKey are masked before reporting an issue. An example key ::::
:::: that you should NOT see in this log looks like this:                  ::::
:::: YIAoJVsdIeyvXfGGDDadHh6AxsMRymZTnnzZoAb9cxRe                          ::::
=============================================
::::            Debug complete           ::::
:::
::: Debug output completed above.
::: Copy saved to /tmp/debug.log
:::
```

**Comment by dziban303** [comment]
Well this is pretty critical.

**Comment by TheCakeGit** [comment]
Just happened to me, latest stable bookworm (64 bit) , Pi 3B. I had no choice but to wipe SD card and start again. I'll install again when it's fixed (this time I've backed up).

**Comment by dziban303** [comment]
If anyone really needs to stay on Bookworm for some reason but also needs Wireguard, wg-easy is a docker implementation that works. Note it's also quite slow compared to a bare metal WG install, like 75Mbps versus 750Mbps, but that may be good enough for some users until pivpn is fixed. If it's fixed.

**Comment by TheCakeGit** [comment]
I would suggest the script gets altered straight away to detect bookworm and abort until it is resolved.

**Comment by 4s3ti** [comment]
If I am going to put time I don't have to fix anything won't abort. 
if anyone has the time to make a pull request ill accept it

**Comment by 4s3ti** [comment]
This being said, next time you have a suggestion anywhere on a opensource project, better to make a valid one or maybe with some code. 

ill take a look at this if I have time during the weekend

**Comment by TheCakeGit** [comment]
I think it's a pretty good suggestion as it literally breaks raspbian (showstopper) and I wouldn't want it to happen to anybody else. At the very least a warning in big characters and getting somebody to press Yes to continue. i've been spending the day rebuilding my whole from scratch (I had other software which I found tricky to configure, and I don't regard myself as an expert). Lesson learned, keep backups up to date.

That being said thankyou for supplying/contributing to this and trying to sort it out. I know it's time consuming.

**Comment by 4s3ti** [comment]
Took a quick second to look at this now, and I am not so sure if this is at all a pivpn related issue .. .book worm is supported by pivpn since Jully 2.

```
commit ef6b0e825d30b43306af999fbb9af6119ea370db (tag: v4.4.0-test.1)
Author: 4s3ti <4s3ti@4s3ti.net>
Date:   Sun Jul 2 11:19:29 2023 +0200

    feat: Support debian 12(Bookworm)

```

The package `raspberrypi-sys-mods` that breaks dhcpcd5, which tells me that in the meantime something changed on that particular packaged ... or .. something should have changed in dhcpcd5 that didn't and causes this to break 

this being said it sounds very raspberry pi specific, not sure if I have one at hand at the moment I can use to test this out, but will see what I can do over the weekend.

**Comment by ArtJames** [comment]
Dhcpcd has been replaced by Networkmanager in all versions of RaspiOS bookworm.
I have tried to roll back to dhcpcd(5), but without success, so I'll stick with Bullseye for now.

**Comment by 4s3ti** [comment]
> Dhcpcd has been replaced by Networkmanager in all versions of RaspiOS bookworm.
I have tried to roll back to dhcpcd(5), but without success, so I'll stick with Bullseye for now.
 
 
 This doesn't seem to be the problem. 
 
 Unfortunately I cannot test and replicate the issue because raspbian os bookworm only runs on raspberry pi 4 or 5, and I currently don't own any of them to test. 
 
 The issue does not happen when running on pure Debian bookworm VMs, which confirms my suspicion of something weird going on with the Raspbian OS Version of it. 

So as it was suggested before "should just detect bookworm and exit" is not an option because Bookworm is effectively supported but raspbian os is breaking it and without a valid method of testing I can't either fix the issue or find a reliable way to exit, therefore, this will keep being an issue until someone decides to help and submit a PR to endorse this issue or until maybe I buy a rpi5 which is not really something where I wish to spend money at the moment. 


Maybe if someone send me the output of the following commands I can come with something up to give a warning and exit: 

*  `cat /etc/os-release`
* `lsb_release -si`
* `lsb_release -sc`

**Comment by TheCakeGit** [comment]
FYI 64 bit (and probably 33bit) Bookworm runs on Pi 3B+. With PI imager you need to select "no filtering".

**Comment by leimsiv** [comment]
Hei, I am not really expert, but I try to help you. 
I have a RPi4 with Bookworm 64but

> * `cat /etc/os-release`
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

> * `lsb_release -si`
No LSB modules are available.
Debian 

> * `lsb_release -sc`
No LSB modules are available.
bookworm

**Comment by 4s3ti** [comment]
> FYI 64 bit (and probably 32 bit) Bookworm runs on Pi 3B+. With PI imager you need to select "no filtering". Apparently it works with 3B and 3A+ models as well.

:facepalm:  yeah saw it now, got it working, and running tests. 


@leimsiv thanks! I managed to get it working on the rpi3  thanks to the @TheCakeGit tip. 

will run some tests and get  back soon

**Comment by 4s3ti** [comment]
There's a fix on the test branch, adding support for NetworkManager on Bookworm for devices where chaning the Ip address is a possibility. 

I am going to run some more tests before merging it to main branch, but if you guys are keen into trying and testing it too feel free.

**Comment by 4s3ti** [comment]
Fix is now on master branch and NetworkManager is now supported on bookworm running on Raspberry pi os. 
Pipelines are brokan (again) as travis ci likes to shut them down often. guess might be time for a change! 


Now the issue is out of the way, allow me to educate you a bit more and further clarify my previous reaction. 

English is not the first language of most people here, and the way we talk and write here matters a lot! 

Nothing demotivates me (and I believe many opensource project maintainers)  more than someone jumping into an issue stating what the maintainers should or should not do!  If you know what should be done, then let me tell you you should do it yourself! 

If you don't know anything about the code base and you have nothing to add then please refrain from adding useless suggestions, "shoulds" or "shouldnt's"! 

Opensource projects are more often than not maintained with the money and time from those who decide to invest on it, and very often that time is taken from spending time with family!  so next time you decide to comment on any github issue, pull request or to be honest, anywhere on the internet, pretty please don't go in with demands or empty suggestions. 

> I would suggest the script gets altered straight away to detect bookworm and abort until it is resolved.

Clearly shows that the commenter had nothing to add to the issue, and knew nothing about the code base, because bookworm was already being detected and supported since July 2! 

instead of such an observation , ext time you go into an opensource project try using a different approach, 

"Hi, I too was affected by this issue, and completely broke the normal functioning of my raspberry pi  and it seems it might affect a wider user base, is there anyone available to take a look at it? How may I help you to speed up the process?" 

This to me, sounds a much more polite way of making the contributors know that you too are affected and sounds a much more motivating message for anyone to actually tackle the issue!

Please all, be better Humans, and don't forget that on the other side there's always someone trying to to their best solving a problem so you don't have to! 


The conversation is going to be locked and if you find further issues, please feel free to open a Discussion or a new issue if relevant, and hopefully this time with a more Human attitude. 

Thank you all for using PiVPN,  <3
