### ISSUE TITLE
I cannot connect to my pivpn

### ISSUE THREAD

**Issue by scleslie** [pivpn/pivpn#188]
Hi I set up my pivpn yesterday and decided to try it out on my phone while at a coffee shop and it was working fine. Later that evening I was at my girlfriends house and wanted to show her my accomplishment, the openvpn app for android was stuck at waiting for server. Earlier that day the I needed to reboot my pi as I had to move it temporarily since then I cannot connect to the vpn. When I ping my pi I also get nothing, I am not sure what I need to do now.

**Comment by redfast00** [comment]
It might be because your Pi doesn't have a static IP on your local network, so when it rebooted,  the IP changed and your previously working portforward isn't valid anymore. Can you post some more details?

**Comment by scleslie** [comment]
So I have it set up with a static IP and the installation had no problems. I also opened the necessary port in my router. I can now ping my pi with no problems. Still cannot connect to the vpn though, still stuck at waiting for server.

**Comment by scleslie** [comment]
Incompatible router it turns out. I moved in with a friend who already had the interet up and running so I guess I am out of luck.

**Comment by 0-kaladin** [comment]
I don't believe there is a such thing as incompatible router. At the end of the day, if you can expose ANY port from that router your openvpn can listen there. And you can use Dyn dns if no static ip.

**Comment by ookangzheng** [comment]
some router will blocked vpn traffic and port also

**Comment by scleslie** [comment]
I tried both with a static ip for my pi as well as trying a ddns with noip both to no avail. So what I think happened was the only successful connection was blocked after I disconnected.

**Comment by teunbruijnen** [comment]
I'm having the same sort of problem, its been working fine for 24 hours. Last night I rebooted my pi and I'm pretty sure it actually didn't reboot, for I couldnt SSH into it. This morning I reconnected the power and I could SSH into my pi again. But, openvpn still doesnt connect! I'm not sure what to do, because I haven't seen this problem around!!

**Comment by cfcolaco** [comment]
@teunbruijnen this is an old issue and closed, if the mentioned solutions didn't work for you please open a new issue so we can to better track it.

meanwhile,check the following:
1 - if rapi has static IP
2 - if router has port properly forwarded
3 - If iptables rules were properly loaded at boot time
   3.1 - to do it simply do sudo iptables -S and check if you have something similar to this (might slightly differ if you used different ports and protocols):
           A INPUT -p udp -m udp --dport 1194 -j ACCEPT
           And sudo iptables -t nat -S 
           -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
           -A POSTROUTING -s 10.8.0.0/24 -o tun0 -j MASQUERADE

Then report back please.

**Comment by teunbruijnen** [comment]
Hi, thanks for your reply. 

I will wait with opening a new issue because it might be pihole conflicting with the ports or ip or something. I installed it a day after I said up the vpn, which was working fine.

 If you're willing to help me, thanks a lot!

1- I'm fairly certain my rapi has a static IP, I set it up in the install of pivpn. I checked ifconfig after rebooting a couple of times, it shows wlan0 has the same Address as before, the one I'm also using to ssh into my pi.

2- I checked the settings in the router, it's still as it is as before; screenshot: 

3- The output of iptables seems significantly different! I'm not sure what it means exactly, I'll google it later. Here's a picture of the output;


Thanks a lot for your answer, I appreciate it!

Teun
