### ISSUE TITLE
getting error running pivpn install script - how to get this working?

### ISSUE THREAD

**Issue by mchp92** [pivpn/pivpn#195]
# PiVPN Issue Template

## Console output of `curl install.pivpn.io | bash`
```
cp: cannot create regular fil /etc/pivpn/pivpnINTERFACE: No such file or directory
bash: line 286: nslookup: command not found
```

## Console output of `pivpn add` or `pivpn add nopass`
```

```

## Console output of `pivpn debug`
```

```

## Issue
I am running the pivpn install script on my fresh Raspi3. two things are buggin me.
(1) i cannot get the static IP dialog to keep my dhcp (as i use static leases in my router).
(2) after I have entered port number etc, and when the install script is about to generate DH keys, the script crashes as it cannot tar the easyrsa. When I look at the directory /etc, i notice that I do not have /etc/openvpn nor /etc/pivpn

and after all this, i seem to have lost all internet connectivity on my raspi.

what is going on here? i really need to have that openvpn server. i bought my pi for that sole purpose...

EDIT: updated the curl ... bash output in this issue

**Comment by mchp92** [comment]
update. after first doing a 'sudo apt-get update' and then 'sudo dnstools install' it now seems to at least generate DH keys (whih is taking quite some time now, but that seems good)

**Comment by 0-kaladin** [comment]
Oops. This is me. I'll fix this shortly.

**Comment by killermosi** [comment]
Apologies if this is unrelated, but I want to point out that I am also interested in a solution to the (1) issue described by mchp92, since I also have a static lease for my Pi.

I understand that forcing a static IP directly on the Pi does not hurt* in this scenario, but then again, why make a change if it is really not needed?

* except when you need to change the IP address of the Pi, like I did
