### ISSUE TITLE
change settings in setup

### ISSUE THREAD

**Issue by RemcoMulder2000** [pivpn/pivpn#232]
Hi all,

I try to install pivpn using TCP and testlevel encryption (1024) instead op UDP and 2048 bit encryption. In the setup I select the settings I want and then hit enter but it still uses the UDP and 2048 bit settings.

Enyone who knows an solution to this?

**Comment by cfcolaco** [comment]
Just finished running piVPN with the settings you mentioned and piVPN applied the options correctly. 

proto tcp
port 443
dh /etc/openvpn/easy-rsa/pi/dh1024.pem

probably you missed something during the setup
the easier solution I believe would be reinstall piVPN and check where you missed.
People usually highlight the new setting and don't press "space bar" to actually select it, could it be the case?

otherwise, and if I am not mistaken, you will have to generate all the certificates and encryption keys manually and place the correct path to the certificates in the the /etc/openvpn/server.conf file which is prone to harder to track mistakes. 

Hope this helps. if you try reinstalling please confirm back to us if it solved. 
thank you

**Comment by SloCompTech** [comment]
Hi, I have posibly same problem, I selected 4096bit key mode, but in setup shows using 2048bit key

**Comment by cfcolaco** [comment]
@SloCompTech  are you sure you really selected the right option??? 

Will close the issue, however, feel free to reopen it or ask to reopen it if needed! will be glad to help out!
