### ISSUE TITLE
No HTTPS on the site

### ISSUE THREAD

**Issue by rvoortman** [pivpn/pivpn#236]
I think the website should use a secure HTTPS connection for several reasons:

- Using a VPN is for the most users a way to stay secure on public connections. Allowing the website to be available through HTTPS gives a 'sign' to users that you can trust this.
- It will improve the SEO
- Browsers are going to mark HTTP sites as 'unsafe' in the near future, which will make it harder for users to use the website. 
- HTTPS Certificates are free, why not use it?

**Comment by 0-kaladin** [comment]
Currently the site is hosted at github (pivpn.github.io) i just have dns make it pivpn.io for better branding.  Github hosting of custom domains (pivpn.io) does not support https.  Otherwise I def would have done it.
What I will do is move the site to my own server so I can enforce https and have the root be the git cloned repo.  This way the site is still open sourced and contributable to as well as pivpn itself.
Not sure when i'll do this, it won't be hard for me to do, but there is your answer.

**Comment by rvoortman** [comment]
I'm satisfied with this. I will close this issue at the moment.

**Comment by 0-kaladin** [comment]
If it's closed I'll never do it.  Let's leave open, it'll force me to do sooner.

**Comment by InnovativeInventor** [comment]
Maybe Cloudflare's free plan might be useful

**Comment by 0-kaladin** [comment]
I can make it https. Don't need cloud flare.

**Comment by redfast00** [comment]
@0-kaladin: when you setup your HTTPS site, you can use Let's Encrypt for free certificates.

**Comment by 0-kaladin** [comment]
Yep that's my plan.

**Comment by jansensan** [comment]
@0-kaladin Thanks for being open about this issue. I was wondering why the site wasn't using HTTPS, and now I am reassured.

**Comment by cezar97** [comment]
@0-kaladin There's no more need for a self hosted server to get https on www.pivpn.io.
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by 4s3ti** [comment]
how are with this @0-kaladin? 

been referred already a couple of times #633, #636

do you need any help with this matter? 

I am using docker on my servers and I'd be more than happy to make a container and throw the website into my server, this way the site can still be open source and it can be easily automated when pushing changes.

**Comment by 4s3ti** [comment]
On those who keep coming back to this .. at the date of this comment was written i have tried to reach @0-kaladin a couple of times without any success .. so for the time being the website will keep without ssl certificate, its not that Concerning as its plain html website and no content is taken from there, the install link is using https so should be fine for now, however i agree it should be fixed

**Comment by rvoortman** [comment]
> its not that Concerning as its plain html website and no content is taken from there

No, I absolutely do NOT agree with this. There is no way for the end user to determine if the site is changed between the server and the browser, maybe there is a malicious MITM attack going on. Another reason is that it is publicly visible to any server that is sitting in between, for example a router or network sniffer. In the same way software is also able to inject stuff into the webpage. 

Let me make this clear: it's not acceptable for a site in 2019 to be HTTP only.

> the install link is using https so should be fine for now

At least that's something. But if you are already making the trouble in making that a HTTPS link, why not take the whole website with it? 

> however i agree it should be fixed

Why not do it? If it's a only a 'plain html website', it should be a very easy thing to set up. 

I might sound harsh here, but it's the basics we are talking about here. We should not have this discussion here.

**Comment by 4s3ti** [comment]
@rvoortman Let me be clear here! I 100% agree with you! however ... 

I am the only active maintainer in this project and i have absolutely no control and access to the domain & server where the website is running. 

The install link is https because its on Github... 

I completely understand the implications on not having the https on the website .. i don't even open sites that do not have https! however.. this situation .. i could clone the website .. put it on a container .. run it on my servers under a new domain .. no worries there .. but the main domain where it is running .. i have 0 control over it and i don't want suddenly change the domain we use. =/ 

lets ping @0-kaladin in hope one more e-mail drops in is blackhole mailbox and attends our prayers! =p

If i don't find any easy solution in the meanwhile to this .... I will probably buy a new domain with the same name .. pivpn.something .. and manage it myself.

**Comment by 4s3ti** [comment]
Closing this ticket. 
Main ticket here: 

https://github.com/pivpn/pivpn.github.io/issues/5

pivpn.io moving to https://pivpn.dev with https =)
