### ISSUE TITLE
Bug after add - ovpn files not making it to the "convenient" location

### ISSUE THREAD

**Issue by sixsixseven** [pivpn/pivpn#238]
## Console output of `pivpn add` or `pivpn add nopass`
```
root@DietPi:~# sudo pivpn add
Enter a Name for the Client:  SkynetMini
Enter the password for the client:  
Enter the password again to verify:  
spawn ./easyrsa build-client-full SkynetMini

Note: using Easy-RSA configuration from: ./vars
Generating a 2048 bit RSA private key
......++
...............+..................+++
writing new private key to '/etc/openvpn/easy-rsa/pki/private/SkynetMini.key.PXldii6MLr'
Enter PEM pass phrase: REMOVED

Verifying - Enter PEM pass phrase: REMOVED

-----
Using configuration from /etc/openvpn/easy-rsa/openssl-1.0.cnf
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'SkynetMini'
Certificate is to be certified until Apr  5 20:07:09 2027 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated
Client's cert found: SkynetMini.crt
Client's Private Key found: SkynetMini.key
CA public Key found: ca.crt
tls-auth Private Key found: ta.key
cp: cannot create regular file ‘/home/pihole/ovpns/SkynetMini.ovpn’: No such file or directory
chown: cannot access ‘/home/pihole/ovpns/SkynetMini.ovpn’: No such file or directory


========================================================
Done! SkynetMini.ovpn successfully created! 
SkynetMini.ovpn was copied to:
  /home/pihole/ovpns
for easy transfer.
========================================================

root@DietPi:~# cd /home/pihole/ovpns
-bash: cd: /home/pihole/ovpns: No such file or directory
```

## Console output of `pivpn debug`
```
::: Generating Debug Output
:::					:::
::		PiVPN Debug		 ::
:::					:::
::	Latest Commit			 ::
:::					:::
commit 6ce39bfec399d9a8203409a108ef27f2ee29327a
Author: 0-kaladin <0.kaladin@gmail.com>
Date:   Mon Feb 27 21:01:23 2017 -0500

    Update README for IRC channel
    
    Due to discontinuation of Google Spaces
:::					:::
::	Recursive list of files in	 ::
::	/etc/openvpn/easy-rsa/pki	 ::
:::					:::
/etc/openvpn/easy-rsa/pki/:
ca.crt
ChrisiPhone.ovpn
crl.pem
Default.txt
dh2048.pem
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
private
serial
serial.old
SkynetMini.ovpn
ta.key

/etc/openvpn/easy-rsa/pki/issued:
ChrisiPhone.crt
server.crt
SkynetMini.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
ChrisiPhone.key
server.key
SkynetMini.key
:::					:::
::	Output of /etc/pivpn/*		 ::
:::					:::
:: START /etc/pivpn/DET_PLATFORM ::
Raspbian
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
1194
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
pihole
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
eth0
:: END /etc/pivpn/pivpnINTERFACE ::
:: START /etc/pivpn/REVOKE_STATUS ::
1
:: END /etc/pivpn/REVOKE_STATUS ::
:::					:::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::					:::
client
dev tun
proto udp
remote REMOVED.ddns.net 1194
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server name
cipher AES-256-CBC
auth SHA256
comp-lzo
verb 1
:::					:::
::	Debug Output Complete		 ::
:::					:::
::: 
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
::: 

```

## Issue
Cannot find the files:
cp: cannot create regular file ‘/home/pihole/ovpns/SkynetMini.ovpn’: No such file or directory
chown: cannot access ‘/home/pihole/ovpns/SkynetMini.ovpn’: No such file or directory

**Comment by cfcolaco** [comment]
you defined pihole as the user to hold client files, and PiVPN is failing to place the files in pihole home dir.

Since you are running the script as root doesn't seems a permissions issue which makes me think that the user pihole possibly doesn't exist in the system or doesn't have home dir!

(to be honest i don't use pihole don't know how it is creating users, but is possible that if that user exists it has no home dir unless you've created it) 

please do **ls /home/**  and check if any pihole directory is listed. 

**if not** just chance /etc/pivpn/INSTALL_USER and replace the pihole user with an existing one which has home dir.

you can easly do that by doing 

echo "USER WITH HOME DIR" > /etc/pivpn/INSTALL_USER

Hope this helps you out!

**Comment by 0-kaladin** [comment]
I guess I'll have to check if the users we allow someone to pick have a home directory. I'll assume he picked a pihole user that does not.

**Comment by cfcolaco** [comment]
@0-kaladin maybe easier and less prone to errors if the setup presents a list of users with home dir, and then the users has to choose one.

**Comment by sixsixseven** [comment]
Ok - @cfcolaco **ls /home/** output:
````
root@DietPi:~# ls /home/
amiberry  pivpn
root@DietPi:~# 
````
I wasn't sure if that echo command was for me or for 0-kaladin.


@0-kaladin 
That would be neat - I just wasn't sure which one to pick since I had a couple of options. My line of thinking was to make it easier to "point" my OpenVPN configs to the piHole setup so I could pipe the OpenVPN sesh through piHole for the ad blocking.

**Comment by cfcolaco** [comment]
@sixsixseven the echo command is a way you have to fix the problem, it will replace the pihole user in the /etc/pivpn/INSTALL_USER file with the "USER WITH HOME DIR" after that after creating a new client file it should go right to the user home dir you selected. 

for example 

    echo "amiberry" > /etc/pivpn/INSTALL_USER

regarding the pivpn + pihole usage it is covered in the wiki

https://github.com/pivpn/pivpn/wiki/FAQ#installing-with-pi-hole

**Comment by e-m-m-a** [comment]
I have this problem. I'm logged in as root. 
if I run 
echo "root" > /etc/pivpn/pihole

Then I still get the error 
cp: cannot create regular file ‘/home/pihole/ovpns/think.ovpn’: No such file or directory
chown: cannot access ‘/home/pihole/ovpns/think.ovpn’: No such file or directory

No clue how to fix this. Please help.
(im tryint to setup pihoime and pi vnp on a digital ocean droplet on ubuntu 14.04

**Comment by hameau** [comment]
ISTM that there is a flaw in the way pivpn is checking for users. Pi-hole runs under its own user (pihole), but the UID is 999 and it has no login shell, nor home directory. The pivpn installation script (on a clean raspbian installation, with only pi-hole already installed) offers the choice of user for storing .ovpn files as:
```
[*] pihole
[ ] pi
```
Pihole is preselected, being first in the list. Perhaps only users with UID of 1000 or greater should be listed?

If user pi is selected, the .ovpn generation completes as expected and the file is in /home/pi/opvns/.

**Comment by hameau** [comment]
@e-m-m-a You must use an existing username that has a home directory under /home (i.e., not root).

**Comment by cfcolaco** [comment]
> I have this problem. I'm logged in as root.
if I run
echo "root" > /etc/pivpn/pihole
or
echo "root" > /etc/pivpn/INSTALL_USER
Then I still get the error
cp: cannot create regular file ‘/home/pihole/ovpns/think.ovpn’: No such file or directory
chown: cannot access ‘/home/pihole/ovpns/think.ovpn’: No such file or directory
No clue how to fix this. Please help.
(Im trying to setup pihoime and pi vnp on a digital ocean droplet on ubuntu 14.04

to fix you should only change the INSTALL_USER file, and you should use an ACTIVE user that has an home directory, and shell login.

Let's say that you have the default pi user that it's used to login in the raspberry pi

`echo "pi" > /etc/pivpn/INSTALL_USER` 

and it will replace all the content in INSTALL_USER file, in this case, the only content would be "pihole" which is going to be replaced with "pi"

Side note: 

if you are new to Linux an easy way to check which users have a home directory, is to `ls /home/ ` directly.

A good practice is to use the user you use to login to the raspberry pi, notice isn't a good practice to allow root SSH login, so, for example, you should `ssh pi@raspberypi` and then `su` or use `sudo` rather than `ssh root@raspberrypi.`

hope that @hameau reply and mine help you out. would be good if you provide any feedback regarding this.

**Comment by 4s3ti** [comment]
The way user is handled changed also the way home dir is detected as well .. so this thread can be closed as this is no longer a concern.
