### ISSUE TITLE
TLS key negotiation failed Unable to connect

### ISSUE THREAD

**Issue by fulvi0** [pivpn/pivpn#239]
Hi, I'm having some issue to connect through the VPN using the `.ovpn` profile generated by `pivpn`, where I got a time out connection from the client side.

Client Side log.

```log
Apr 08 12:49:01: Control Channel Authentication: using '/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/connection.en1JpH/ta.key' as a OpenVPN static key file
Apr 08 12:49:01: UDPv4 link local: [undef]
Apr 08 12:49:01: UDPv4 link remote: [AF_INET]148.xxx.xxx.xxx:11945
Apr 08 12:50:01: TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Apr 08 12:50:01: TLS Error: TLS handshake failed
Apr 08 12:50:01: SIGUSR1[soft,tls-error] received, process restarting
```
[pivpn_debug_log.txt](https://github.com/pivpn/pivpn/files/907667/pivpn_debug_log.txt)

Note: If I set up the **local IP** of mi VPN server in the client I'm able to connect.
```bash
╭─pivpn@raspberrypi ~
╰─$ pivpn -c

: NOTE : The output below is NOT real-time!
:      : It may be off by a few minutes.

::: Client Status List :::
							Bytes		Bytes
Name		Remote IP		Virtual IP	Received	Sent		Connected Since
rpi		192.168.1.195:53353	10.8.0.2	186932		238545		Apr 8 2017 -- 12:41:24
```

**Comment by jellemdekker** [comment]
Just making sure: did you forward port 11945 to your Raspberry Pi's local IP address in your router?

**Comment by christyler80** [comment]
I have the same problem. PiVPN did work fine when I set my Pi up a few months ago. However, I have now rebuild the Pi from scratch using what I believe to be identical settings, including DynDns via ddclient and I get this error, unless I specify the local IP address in the client 'ovpn' files, in which case it works. 

My router port forwarding forwarding looks OK and these settings haven't changed since I first installed PiPVN several months ago when PiVPN worked for me. The Pi IP address is static and the same as when I set it up first time around.

**Comment by christyler80** [comment]
I have the same problem. PiVPN did work fine when I set my Pi up a few months ago. However, I have now rebuild the Pi from scratch using what I believe to be identical settings, including DynDns via ddclient and I get this error, unless I specify the local IP address in the client 'ovpn' files, in which case it works.
My router port forwarding looks OK and these settings haven't changed since I first installed PiPVN several months ago when PiVPN worked for me. The Pi IP address is static and the same as when I set it up first time around.

**Comment by fulvi0** [comment]
@jellemdekker  @christyler80 , Hi, I solved the issue by setting my router at DMZ in the modem ISP configuration, I was trying with port forwarding setting in the modem but without any luck, after setting the router in the DMZ it's working properly.

```
Modem ISP / Huawei HG8245 Router --> Router / Linksys WRT1200ac --> OpenVPN Raspberry Pi/pivpn
                                  ------------------------------
                                                DMZ
```
