### ISSUE TITLE
Ip Range

### ISSUE THREAD

**Issue by rob0t17** [pivpn/pivpn#241]
I want to use PiVPN to access all kind of IP hardware on a remote LAN. Mainly to renew firmware and to update programs. The installation was a piece of cake. Great script!
But the ip range I get from the raspberry is not the ip-range that I want to access. I tried to change the range in the server.conf but that stopped everything. How can I adjust the ip-range? I have looked at the bridge mode but doesn't know if this applies to my problem.
thanks

# PiVPN Issue Template

## Console output of `curl install.pivpn.io | bash`
```

```

## Console output of `pivpn add` or `pivpn add nopass`
```

```

## Console output of `pivpn debug`
```

```

**Comment by cfcolaco** [comment]
Hello,  when opening issues would be of great use providing the info requested in the template it helps a lot any1 that tries to help you otherwise the troubleshooting would be more of a trial and error and guessing what could be wrong instead of looking to looking to the exact config lines and understand what's wrong. 

regarding the issue, it is not related to IP range! 

OpenVPN server needs to be aware of other subnets existence which is done in the setup unless you have set up something else. 

please check your server config file and pay special attention to this lines 

# your local subnet
push "route 192.168.1.0 255.255.255.0"

and confirm if they exist and if the IP addresses are properly set up! 

if it doesn't help, please provide the pivpn debug command output please!

**Comment by cfcolaco** [comment]
@redfast00 seems that this issue can be closed since there's no more answers/questions.
