### ISSUE TITLE
Configure RPis as clients. How !?

### ISSUE THREAD

**Issue by OMID-313** [pivpn/pivpn#247]
Hi,

Let's say I have 20 RPis in different cities, and I want to control and monitor them from my office.
How can I use pivpn to do so !?

All of your tutorials say how to configure RPi as server. But I think I need to configure 20 RPis as clients, and my office PC as the server. (Correct!?)

So, how can I do this using pivpn!?

Thanks.

**Comment by cfcolaco** [comment]
Hi, 

Setting up a client is not the objective of PIVPN, however,

to do that, you must set-up a VPN server which you can do using debian or ubuntu and pivpn and then in the server you have two options: 

1 -  create 20 client certificates
2 - change the OpenVPN settings to allow duplicate certificates and you can use the same cert for every client

and then set-up all the pis as clients, which can be fairly easy with only one certificate since you just have copy all the configs.

hope this helps you.

**Comment by OMID-313** [comment]
Thanks @cfcolaco for your answer.

So as I understand, I should use pivpn on an Ubuntu PC as a server (or maybe even on an RPI as server), following the tutorials, and create certificates for clients.
And then I should install openVPN on each of the 20 RPis as the clients (sudo apt-get install openvpn).

Correct !?

**Comment by redfast00** [comment]
Yup, that's pretty much it. What do you mean by 'control and monitor'?

**Comment by OMID-313** [comment]
@redfast00 
I mean to be able to see the logs, transfer files to/from them, take screen shots if necessary, enable/disable services remotely, etc.

**Comment by redfast00** [comment]
If you can forward a port on the Pi clients, setting up an ssh server on them  might be a better solution.

**Comment by OMID-313** [comment]
@redfast00
Which one is more secure?
VPN vs SSH vs Port Forwarding vs Tunneling vs ...
I think I need some sort of "show me the path" kind of help!

**Comment by redfast00** [comment]
So if you want to have a shell on the device: use SSH. You will need to portforward port 22. SSH is secure (Secure SHell), and if you want it to be extra secure, use your SSH key to login. Here's an excellent tutorial: https://www.digitalocean.com/community/tutorials/how-to-use-ssh-to-connect-to-a-remote-server-in-ubuntu

OpenVPN is something completely different: it doesn't allow you to execute commands on a server, but it allows clients to connect to the server in order to appear to be on the same network as the server. That process is called tunneling. 

Port forwarding is like punching a hole in the firewall: it allows for one/multiple ports to be routed to a server, without forwarding all ports to the server.

**Comment by OMID-313** [comment]
Thanks @redfast00 for your reply.

So you mean SSH is better than VPN for my situation (controlling, monitoring, and transferring files from/to 20 remote RPis in different cities from the office); right !?

**Comment by redfast00** [comment]
Yes
