### ISSUE TITLE
How can i lower the key's security????

### ISSUE THREAD

**Issue by ducarpit** [pivpn/pivpn#267]
Hi,
i installaed pivpn on my Raspberry Pi3 and all works but unfortunatly it's very slow.
Can i lower the key's security (for example from 1024 to 512 bit) to increase the connection speed?
Thank a lot

Chritsian

**Comment by ohdude** [comment]
remove -> reinstall

**Comment by redfast00** [comment]
Please don't do that. 1024 bits is already somewhat insecure, and 512 bits isn't even supported by PiVPN. The real bottleneck probably is your network, either inside your LAN or from the place you're using the VPN from.

**Comment by ducarpit** [comment]
Ok, thanks...unfortunatly i have my vpn server at home and here i have only a static line (20Mbps download and only 1Mbps upload)....probably the problem is the 1Mmbps pseed in upload that reduce the request speed of the websites.....

**Comment by redfast00** [comment]
Yes, indeed, on your VPN, your bandwidth will be limited to the minimum of your upload and download bandwidth (since all outbound trafic has to go twice over the internet). Keysize should have almost no influence here, so you might as well have 4096bits keys. Closing this since I don't see any way to fix this apart from increasing bandwidth: compression is enabled by default and the size of your keys don't influence bandwidth after the initial negotiation.

**Comment by ducarpit** [comment]
Thanks a lot....

**Comment by ohdude** [comment]
![](http://i1.kym-cdn.com/photos/images/facebook/000/229/291/db9.jpg)
