### ISSUE TITLE
Question: Route only specific ip throught tunnel

### ISSUE THREAD

**Issue by xmicks** [pivpn/pivpn#268]
Is it possible to manage the routed traffic through the tunnel with the pi?

I want to place a pivpn box 'elsewhere' and set up a client on my homenetwork to the pivpn server but only allow a specific host through on the pivpn local network.

**Comment by cfcolaco** [comment]
I don't think if I understand exactly what you need however I don't see any use for such thing since each client has to have it's own certificate unless you allow the usage of the same certificate. 

only the client with the certificate will be able to access the OpenVPN network, others that don't have the generated certificate won't be able to access the network. However, if you want your OpenVPN port accessible only to a given IP address, you can limit it in the firewall by matching the port only to a specific IP address, but it won't limit the access to all the computers behind that IP address. 

let's say, on your home network you have 5 computers.
In your pi, you limit the OpenVPN port only to your home network public IP address, only the computers in your home network would be able to access the OpenVPN server in the pi since they all share the same public IP address. 
A further restriction is applied through the certificate as I have mentioned before, and only clients with the correct certificate will be able to access the OpenVPN network.

Hope this helps you, please ask here if you need further help.

**Comment by xmicks** [comment]
Sorry for not being clear. The pi with server is at my parents home, on my homenetwork I have a pfsense router on which I will create a client to connect to the pi at my parents home. (at least, that's how I think is the way to go)

For security reasons I only want  1 specific host(a dvr-streamer) to be able to access my home network from the server(pi) side through the tunnel. (if that's possible). 

I can't have that host to connect to my homevpnserver, because it isn't able to do that. (so reverse client and server). Is that even possible? For the pi to be client and route traffic from that other host(dvr-streamer) to my homevpnserver? So that host is accessible from my home network?

**Comment by cfcolaco** [comment]
hmm that's quite hacky! never thought of something like this ... 

let me see if I understood so I can think about it, basically, you need the DVR-Streamer ( that is unable to directly connect to a VPN )  which is in your parents home to connect to your home network? 

seems to be no easy solution, and it might not be even possible due to OpenVPN limitations or even equipment, it is possible that you will probably need a bridge VPN, however since I don't know all the details of equipment and networking traffic involved and can't assure you! 

( hope some1 more experienced come over and helps out with this! ;) ) 

but your concept, might work, never thought of it, but it is worth trying, however, and at this early stage I wouldn't concern with security or limiting hosts whatsoever ... first, I would try the concept and see if it works .. then you worry about security! ;) 

Give feedback as you try out, please! I would like to know about it! :P

**Comment by xmicks** [comment]
yea some good advice, thank you!

meanwhile I've thought of another solution. I had some old miniitx board laying around. I can put rancheros+docker on that box. So I can put other docker containers like plex, openvpn etc on that board. (on my homenetwork I want my plex server to receive the dvr-stream.) So would also be a backup solution to have a plex server at my parents home and let that plex server send it to my plex server. I would need this powerful box at my parents because i read plex server(transcoding) is at the pi's limits.

A other solution, involving the pi :) , might be to just create the connection and worry about security later. I can set some firewall rules at my side to only allow incoming traffic to just the plex-server(at my home) and not to anything else in my home network. Or maybe only allow outbound traffic and block all the inbound traffic. 

i'll post my progress here.

**Comment by cfcolaco** [comment]
@xmicks any news about this?

**Comment by 4s3ti** [comment]
Closing, 
If you want to keep this discussion please take it to our subreddit.
