### ISSUE TITLE
[Enhancement] - VPN Gateway / Pihole Compatibility

### ISSUE THREAD

**Issue by rmclellan** [pivpn/pivpn#273]
I've always had an idea of privacy "proxy" which can be run from a VPS.  You're traffic would be encrypted to the proxy and outbound traffic would be encrypted to a paid VPN service.  This would allow you to connect to your home network from anywhere in the world and ensure all outbound traffic was encrypted. 

It would appear that this project may be part of the way there; ideally layer into the auto install feature the ability to include the vpn-gateway project here: 

https://github.com/mr-canoehead/vpn_client_gateway

and maybe eventually the PIhole functionally as well 

https://github.com/pi-hole/pi-hole

Note, the above two projects are already compatible.  I'll be looking to add some pull requests for this in my free time in the next little while but if anyone was interested in working on this in the mean time I just wanted to put it out there.

**Comment by redfast00** [comment]
Why not directly connect to the (paid) VPN service instead of putting another node in between? The extra step will result in less bandwidth, more latency and maybe even less security: you now have to worry about the node in the middle.

**Comment by cfcolaco** [comment]
Don't see any benefit in that! 

Since your talking about privacy, from the time you connect to a VPN all the traffic gets encrypted between booth nodes, and all the traffic to the world will be forwarded through the VPN, having this said, the world will see the VPN IP address instead of your home IP address, and no one inside your home will be able to understand what's going out from your computer! 

why add a "privacy proxy" between the client and the VPN? why would you want to hide your IP address so badly from your own VPN? or even from a paid VPN service? unless you're doing something nasty it's pointless, you have already enough privacy with a VPN between your PC and the World, and even if you're doing something nasty that you would want to hide your IP address so badly, the setup as you describe will always lead to you! 

having this said, again, I don't see any benefit in adding an extra proxy in-between Client and VPN and as @redfast00 stated, will be an extra worry, and surely extra privacy concern, and (I am not sure about this), it could possibly weaken the encryption between nodes!! 

if there's such big privacy concern... just buy a VPS, throw Ubuntu or Debian on it and fire PiVPN ... and there you have your privacy! your server, your rules, your logs! and one sees what you're doing unless you want to do something nasty that will lead to an investigation, which either way will lead to you anyway! there are other ways of properly getting "privacy" for such things.

**Comment by redfast00** [comment]
@cfcolaco: indeed. The encryption probably won't be broken, but the server in the middle might get compromised. @rmckellan: if you need anonymity, there are other options such as TOR or a VPN provider who doesn't keep logs. Closing this for now, please reopen or comment if you have a valid reason to consider this approach.
