### ISSUE TITLE
Public IP cannot be used to connect pivpn

### ISSUE THREAD

**Issue by sc231997** [pivpn/pivpn#290]
my router is using PPPoE protocol to connect to ISP. So, now the issue i am facing right now is that if i use my PPPoE(Gateway IP) in the .ovpn file then it work fine if the client is under same isp provider otherwise it show timeout error. I even tried to use public ip but then nothing was working.

**Comment by cfcolaco** [comment]
Can't understand exactly what you are asking, and think this issue is a bit outside of the scope and completely unrelated with PiVPN. However ... 

You should always connect to the VPN with your public IP which you can get ( for example ) here:
http://www.whatsmyip.org/ or with a domain name. 

PPPoE tends to have dynamic IP address which means it will be changing over connections ( depending on ISP policy ), so you will have to use something like DynDNS or noIP and instead of your public IP address ( which changes frequently ) you should use your DynDNS or noIP domain which will be always forwarding to the correct IP address.  could it be the case the IP changed between the time you installed PiVPN and tried to connect? 

I could also happen that your ISP has you behind a NAT which makes things more complicated to have any kind of server at home, but this is a bit beyond my knowledge as I don't know exactly how ISP NAT works =/

**Comment by cfcolaco** [comment]
@redfast00 And this one, please?
