### ISSUE TITLE
Apple devices can't import private key

### ISSUE THREAD

**Issue by hari-bo** [pivpn/pivpn#304]
Currently i'm testing to get this setup working with several Appel devices, but i receive the following error:
PolarSSL: error parsing config private key : PK - Bad input parameters to function [ERR]

The private key is generated encrypted from the PiVPN, is there an possibility to decrypt this for Apple devices

**Comment by jellemdekker** [comment]
Into what program are you trying to import the private key?

**Comment by hari-bo** [comment]
OpenVPN for IOS.

**Comment by jellemdekker** [comment]
And just to verify; you are trying to import the .ovpn file that you made using the command `pivpn add`?

**Comment by hari-bo** [comment]
That's correct.

**Comment by jellemdekker** [comment]
Does your <key> block begin with `-----BEGIN ENCRYPTED PRIVATE KEY-----` or `-----BEGIN PRIVATE KEY-----`?

If it's encrypted, can you try making a new client profile without encrypting the private key by using `pivpn add nopass`? See if that works. It could be that the OpenVPN iOS client doesn't support encrypted private keys.

**Comment by hari-bo** [comment]
It begins with -----BEGIN ENCRYPTED PRIVATE KEY-----
can i create a new profile with the following syntax:
pivpn add nopass [user] ?

**Comment by jellemdekker** [comment]
Okay, so your private key is encrypted. No, just use the command `pivpn add nopass`. You will be asked for the client details after that.

**Comment by jellemdekker** [comment]
Were you able to fix your problem?

**Comment by hari-bo** [comment]
This solution works great, thanks!

**Comment by jellemdekker** [comment]
Alright, thank you for letting us know. Please mark this issue as resolved.

**Comment by MatthewVance** [comment]
A good way to solve this is to remove the key from the profile and import it directly into iOS. iOS supports importing encrypted private keys. Plus, you get the added benefit of hardware protection (secure enclave) on devices that support it. Once imported into iOS, point the OpenVPN app to it.

A few additional notes:

1. Your must convert your key to PKCS#12 format:
`openssl pkcs12 -export -inkey client.key -in client.crt -certfile ca.crt -caname "My CA" -out client.p12`

2. Next, you need to extract the CA list from the PKCS#12 so CA can also be imported to iOS (versus embedded in profile using ca directive). To do so:
`openssl pkcs12 -in client.p12 -cacerts -nokeys -out my-ca.crt`

3. Be sure to remove `<key>`, `<cert>`, and `<ca>` entries from your ovpn profile since those are contained in iOS. You should keep the key between the `<tls-auth>` tags if you're using the OpenVPN static key for additional protection (i.e., a kind of "HMAC firewall" per the man page).

To get the files to your device, you can use AirDrop, Safari (serve files on intranet http server), email, or iTunes.

Reference: https://docs.openvpn.net/docs/openvpn-connect/openvpn-connect-ios-faq.html

**Comment by cgbarnwell** [comment]
I've hit the problem of creating profiles for an Apple device (in my case an iPad).  I got it working in the end with help from this thread, but what I did differs slightly from this.  I created an ovpn12 file that contained just the crt and key files and then left the <ca> key within the ovpn file.
It would be useful to allow the add command to specify that the profiles are for an Apple device.  I'm happy to write some code.  Would that be helpful?

**Comment by antiabed** [comment]
I want to do this too, but I don't know where to find the client.key, client.crt or ca.crt on the server. Could someone help me out?
And I'm also wondering why @cgbarnwell did something slightly different, is it more secure like that?

**Comment by cgbarnwell** [comment]
> I want to do this too, but I don't know where to find the client.key, client.crt or ca.crt on the server. Could someone help me out?
> And I'm also wondering why @cgbarnwell did something slightly different, is it more secure like that?

My understanding of this has changed since I made the post.  I tried to import an OVPN file into OpenVPN on an iPad and it didn't work, it said that the file was in the wrong format.  So I imported an OVPN12 file and an OVPN file.  Since then I have been able to import OVPN files, so I don't know why the original didn't work.

To create the OVPN12 file I used the command above, but did not include the ca.crt file.  That remained in the OVPN file.

The client.crt file is in /etc/openvpn/easy-rsa/pki/issued/ and has the name you gave when creating the ovpn file.  The key file is in /etc/openvpn/easy-rsa/pki/private/ and has the same name.

The reason I did slightly differently is that I left the ca.crt in the ovpn file.  I do not know which is better.
