### ISSUE TITLE
Access my home devices through vpn

### ISSUE THREAD

**Issue by joejoe2017** [pivpn/pivpn#306]
Hello, you cannot imagine how I love pivpn, very stable, fast and reliable vpn. I used it to rung a VOIP service through my home internet whic work flawlessly, 
I am not a programming expert, so I need you help how can access my home LAN computers shared drives from an outside computer that run on the same VPN.

I hope you can help me with the computers (one the lan and the remote) IP configuration.

Here is my setup scenario
1- OPenvpn setup with TCP 443, GOOGLE DDNS, Rasp pi ip is 10.8.0.1
2- DDNS update installed on the DD-WRT router with open port 443
3- All my computers run Windows 10 

Thank you for your reply in advance

Thank you so much and I really appreciate your miracle work

**Comment by cfcolaco** [comment]
Are the shares on your windows 10 machines? 
Are you accessing the shares from a windows machine? 

if this is the case I believe that you only need to 
WindowsKey + r 
and then
  
\\xxx.xxx.xxx.xxx ( machines IP address )  or \\xxx.xxx.xxx.xxx\path\to\share

it should get you on the way.
you won't be able to use machines hostnames since you are using google DNS directly on the pi. 
to be able to use computers hostnames you should replace the 

`push "dhcp-option DNS 8.8.8.8"`

with 

`push "dchp-option DNS XXX.XXX.XXX.XXX" ( your router IP address ) `

so far is the best way we found to use hostnames.

**Comment by joejoe2017** [comment]
Thank you so much for your reply, it worked.
one last request, can you guide me through to assign static ip address to the windows 10 computers connected to the VPN ? one of them is my file server

**Comment by 4s3ti** [comment]
if you still need assistance with this, please look through other similar issues or open a thread on our subreddit.

**Comment by joejoe2017** [comment]
No, is working now

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
