### ISSUE TITLE
Changing Server's Netmask

### ISSUE THREAD

**Issue by Geffers** [pivpn/pivpn#323]
Folks,

I've posted 2 messages recently (319 & 307) both referring to connecting clients appearing to have full access to Server's filesystem.

May have narrowed it down, my private network is 10.19.44.0 which I know is a class A network. When the PiVPN script ran it set my fixed IP fine and gateway etc but ifconfig shows netmask as 255.0.0.0

I assume I need to change this to 255.255.255.0 but if I use 

`sudo ifconfig eth0 netmask 255.255.255.0`

the server hangs at the command.

Probably some VPN security so question is; how do I change netmask?

Other than this my PiVPN is working great.

Geffers

**Comment by Geffers** [comment]
Managed to change my netmask to 255.255.255.0 but client still has full access to server's network.

Obviously has to know any passwords.

Geffers

**Comment by cfcolaco** [comment]
@Geffers you are quite insistent with this!! stop being paranoid! 

You don't want the clients to have access to the network? Just do what I have told you in #319 
hash the `push route `YOUR NETWORK` and clients will stop to have access to other devices withing the network. 

of course, they will still have access to 18.8.0.1 ( the Pi internal IP address ) because they HAVE TO!! So as long as you are not using your pi for anything less appropriate, and as long as you keep your client certificates secure, and you have good passwords, and you set an IPtables to drop every SSH connection from the 18.0.0.0 network. you will be perfectly fine!! 

don't see where you want to get with this issues.
So please be more explicit or in the meanwhile, I will just ask to redtasft00 to close this issue also.

**Comment by cfcolaco** [comment]
@Geffers closing this issue. 

If you need further help regarding this, just shout! =)
