### ISSUE TITLE
[Need guide]Add TCP connection without re-run pivpn from beginning

### ISSUE THREAD

**Issue by ttpro1995** [pivpn/pivpn#327]
Hi, I would like to add TCP option (because some network block UDP VPN). However, I am newbie and do not how to config setting file (I do not know where is it) .

I test with vpnbook and confirm that UDP are block, but TCP still work on the network (at school)

**Comment by Kavaho** [comment]
@ttpro1995 First of all, I would recommend getting notepad++, because it's way better organised when editing files, even though you can edit the files with notepad or another simple text editor. 

I would also recommend to reinstall the PiVPN running the script and choosing TCP, it's gonna be more simple. If you decide to edit the files, you will have to edit both the serve and the client files. Server file location is /etc/openvpn/server.conf -> you will have to change UDP to TCP here. Client files that are generated using "pivpn add" can be found at /home/pi/ovpns. 

I would also like to add that you will have to change the port forwarding too. As of running both TCP and UDP at the same time, I don't think it can be done, but I'm not a developer, just a newbie trying to help others struggling.

**Comment by cfcolaco** [comment]
@Kavaho I think it can be done, you just need to have two different config files. 

for example /etc/openvp/server.conf and /etc/openvpn/utpserver.conf each with it's own config, for example one can be for port 443 UTP and other for port 443 TCP

Then just open and forward both ports on the router.... however this config is not supported by OpenVPNm you are on your own. 

pivpn add will basically add only for the setup it was configured to. 

Please consider that everything i am saying here, is purely theoretically as I know it is possible and that you need different config files that OpenVPN will run both, but I have never use such kind of setup

**Comment by redfast00** [comment]
I am running the exact config @cfcolaco described and it works great! Ping me if you need exact config details.

**Comment by cfcolaco** [comment]
Closing as no more comms regarding this .. assuming the provided information helped out. 

if further help needed, comment out and will gladly help.

**Comment by TheMardy** [comment]
@redfast00 I would like the config details. 
I tried running the config described above and my laptop successfully connects using both the (original) UDP certificate and the (new) TCP certificate, but I cannot access the internet. When I remove the TCP .conf my UDP certificate works fine again.
I would like to know how you managed to do it.

**Comment by redfast00** [comment]
@TheMardy unfortunately, I had to reinstall and lost the config details.
