### ISSUE TITLE
DNS problem on Mac Os X

### ISSUE THREAD

**Issue by adrianmihalko** [pivpn/pivpn#338]
I successfully installed pivpn on my rPi Zero and I can connect from my iPhone without any problem. I can browse internet, I can access my LAN devices.

The problem is with Mac OS X client, the nameservers are not be set (pinging ip's are working like ping 8.8.8.8, or my internal LAN). I don't know if it's is a Tunnelblick problem or not, but here is the output:

```
After connecting to xy, DNS does not appear to be working.
This may mean that your VPN is not configured correctly.

```

Output:

https://pastebin.ca/3857090

**Comment by InnovativeInventor** [comment]
Could you look at the server config files (at /etc/openvpn/server.conf) and look for `push dhcp-option DNS`? In addition, could you go to System Preferences > Advanced > DNS to see what your current DNS servers are? That would be helpful in diagnosing your issue. Tunnelblick is most likely not the problem here.

**Comment by cfcolaco** [comment]
closing issue as no answer to @InnovativeInventor questions.
