### ISSUE TITLE
MAC address unchanged when swapping SD card to a new PI

### ISSUE THREAD

**Issue by New-PiVPN-User** [pivpn/pivpn#357]
Hi I installed PiVPN on a Raspberry PI 2 on Jessie Lite using the instructions here

http://kamilslab.com/2017/01/22/how-to-turn-your-raspberry-pi-into-a-home-vpn-server-using-pivpn/

It worked perfectly and I am very happy. I transferred the SD card to a Raspberry Pi 3 and noticed the MAC address of the new Pi 3 seemed to be exactly the same as the Raspberry Pi 2 is was originally installed.

How do I fix

Many thanks

**Comment by redfast00** [comment]
This isn't an issue with PiVPN, so I am closing this issue.

**Comment by New-PiVPN-User** [comment]
Oh ! :(

**Comment by redfast00** [comment]
Now that this is closed, are you sure it's the same mac address? How did you show the mac address? What is it?

**Comment by cfcolaco** [comment]
@New-PiVPN-User that's a raspbian thing!! ( don't know about other distros )

If you install on a device and then move the SD Card to another one, you will have to change the mac address manually in every networking config file otherwise it will be expecting the mac address from the frist device and won't work!!

I learned that in the worst possible way ... Installed raspbian 3 times in 3 different sdcards for 3 differend rpis 3 ... aaaaand ..... no joy!
