### ISSUE TITLE
Merge test branch

### ISSUE THREAD

**Issue by redfast00** [pivpn/pivpn#360]
Test branch should be 'test-merged' into the master branch and tested, then 'legit-merged' (for all users) into the master branch (several commits have landed into the test branch, but haven't been tested or merged yet).

**Comment by jellemdekker** [comment]
I'm in the process of opening a few pull requests to add functionality and fixes. Would you like me to hold off on this or shall we look at those first?

**Comment by redfast00** [comment]
I guess we could do your fixes first so we don't have to test twice. What do you have in mind when adding functionality? It would be a shame if you went trough all the trouble to add a feature that wouldn't be merged.

**Comment by jellemdekker** [comment]
I have the following ready or almost ready to go:
- [Security] Generate CRL during installation, not until whenever the user revokes a client profile for the first time
- [Security] Add random suffix to the server certificate CN so that the verify-x509-name check is actually useful
- [Security] Improvements to the selection menu of Diffie-Hellman parameters
- [Cleanup] Resolving typos and inconsistencies
- [Cleanup] Removing excess code

I'm currently still working on this:
- [Security] Specify TLS options such as ECDH curve, allowed TLS- and NCP-ciphers

I have this ready to go, but in the past you declined it because it might be too advanced or a novelty feature:
- [Feature] Implemented option to disable logging

**Comment by redfast00** [comment]
This all looks great (except the feature I declined ofcourse). Awsome that you'll weed out dead code. Two questions about specifying TLS options: will you pick sane defaults (recommended) or will the user need to do this? Do OpenVPN clients support these options (Android, Linux, iOS)?

**Comment by jellemdekker** [comment]
I'll definitely pick the defaults (or at least suggest them in my PR and then they're up for debate). I don't think the user should be able to do this. 

Whether all clients support these defaults is a different story. Up until recently, I thought PiVPN only supported Raspbian Jessie. Therefore the version of OpenVPN would always be 2.3.3 or higher and gave me a good direction for the defaults. However, I discovered that PiVPN also supports Ubuntu 14.04 which runs on OpenVPN 2.3.2 and therefore needs more loosely defined defaults for the client and the server. So that's what I'm currently researching.

**Comment by jellemdekker** [comment]
You can begin testing if you'd like, I've submitted all my work that was ready. The rest I'm still working on or testing.

**Comment by cfcolaco** [comment]
@redfast00 @0-kaladin how the status of this?  
has any merge to master branch been made in the meanwhile? I might have got a bit lost with all this time away!

**Comment by redfast00** [comment]
No merge has been done yet. Wanna test if the test branch is stable enough?

**Comment by cfcolaco** [comment]
@redfast00 Will add support for Stretch and then I make some tests on it! =)

**Comment by cfcolaco** [comment]
Closing as per Merge #376
