### ISSUE TITLE
Wonderful but...

### ISSUE THREAD

**Issue by doizece** [pivpn/pivpn#38]
Hey, Im a newbie to this so..yeah

First of all thank you for the script. Everything works fine from outside my home network but while inside my network clients can't connect.

**Comment by doizece** [comment]
Forgot to mention that once I change the ip on my client config file to 192.168.1.11(the rpi ip) it works..but that's not really a fix

**Comment by 0-kaladin** [comment]
you don't need to connect from inside your home, there is no purpose to that.  you need to put the IP back to your public IP that is port forwarded in your router.  The purpose is to encrypt your traffic when you are NOT at home so that it is not able to be sniffed or inspected at untrusted locations.

**Comment by PenguinDUB** [comment]
doizece, that is the right fix. I know this is closed but you're SUPPOSED to change the internal IP to the same IP as the openVPN server (i.e. your Raspberry Pi) in the *.ovpn file. However, connecting from the inside, like Kaladin said, is not the intended use for this project.. unless you're trying to troubleshoot or something..
