### ISSUE TITLE
pivpn  and upnp

### ISSUE THREAD

**Issue by kakitogit** [pivpn/pivpn#416]
hi

i´m installing and using pivpn in a rpi3 without any problem but i have also installed Kodi with and addon to watch live tv on that rpi3, after installing the pivpn kodi stopped to work sohwing errors  about upnp; everything works well if i stop the openvpn service but something is fighting when trying to run openvpn and kodi with this addon. any idea about waht could it be? any port need to be opened??? any iptable to be added? how could i troubleshoot this?

Error from kodi log:
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Core was generated by `/usr/lib/arm-linux-gnueabihf/kodi/kodi_v7.bin --lircdev /var/run/lirc/lircd -fs'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x5fd051d0 in upnp::Process() () from /home/pi/.kodi/addons/MovistarTV.Server.rpi/Kodi_MovistarTV_Server.pvr

thanks a lot.
Carlos.

**Comment by cfcolaco** [comment]
@kakitogit unless someone here in the pivpn community knows how to help you ( which seems not to be the case ) you should try to reach out the OpenVPN community, via GitHub or IRC Channel because this is more related to Kodi or OpenVPN then PiVPN as PiVPN is merely an OpenVPN Installer as we mention in the Project readme and wiki. 

I am sorry .. I will leave this open for a while just in case someone pops up and knows how to help you out.

**Comment by cfcolaco** [comment]
As per issue #410 I think upnp needs briged mode See issue #45 ... so you might be out of luck in the meanwhile!
