### ISSUE TITLE
Unable to resolve local https

### ISSUE THREAD

**Issue by varsilence** [pivpn/pivpn#427]
Hello,

After some configurations, I am able to connect to my vpn reaching WAN and LAN.

However, I host Unifi 5 for network management and I am unable to resolve the local IP address through https, while being able to access a web service with out ssl from the same server (which happens to be a pi3). 
As soon as I am on my actual LAN again, I can access it so I know it is working, I just can't access it while connected through VPN.

I also host Octopi from a dedicated Pi3 for my 3d printer, while I can access its web-based UI (not secured SSL) but I can't view the live webcam broadcast that uses mjpeg-streamer.

Does anyone have any insight to this issue?

**Comment by cfcolaco** [comment]
@varsilence I am sorry but I cannot help you with that =/ don't know if someone else can .. its the kind of thing that to be able to help you I would need to have access to it in order to play with it! =/ will leave the issue open in case someone comes by and can help you better with that! 

What do you have serving DNS inside your home network? Is That the same DNS you provided to setup PIVPN?

**Comment by cezar97** [comment]
DNS translates domains to IP's, so I don't think it's the reason you can't access HTTPS services...

**Comment by 4s3ti** [comment]
if this still a thing, please open discussion thread on Reddit.
