### ISSUE TITLE
only using 1 core ?

### ISSUE THREAD

**Issue by terminalcat** [pivpn/pivpn#428]
Hello,
recently i was testing the speed of my pivpn with the rpi 3.
and was watching the cpu usage with ''Htop'' and i saw that only 1 core was being used and was maxed out
can i enable more cores so i can get more performance ?

may thanks,
Joris

**Comment by cfcolaco** [comment]
@terminalcat that's not PiVPN Related but yes OpenVPN related ..

I wonder how exactly you evaluated this ... since you clearly misunderstanding the relationship between PiVPN and OpenVPN ... 

anyway ... the best place to ask this kind of questions are in OpenVPN IRC Chanel, in OpenVPN GitHub page and so on ...
