### ISSUE TITLE
Speed performance on user with pass and “nopass”

### ISSUE THREAD

**Issue by badanas** [pivpn/pivpn#435]
Hello

I have 2 raspberry pi 3, both with pivpn, on in my home country with optical fiber internet 100/10 and another one on country that I am working with optical fiber 100/100.

On my home country I created an user with command “nopass” because I was with some problems on authentication on my iOS device (now I know that I need to convert my key to 3des encryption), and I get from internet speed when I connect from my work country to home country 55mb download / 11mb upload.

On my work country I have created with Pass like it should , and I have 35mb download / 25mb upload, making the test on same country, and connected with same Wi-Fi, so using a vpn to connect to same internet that I was without vpn.

This is a normal behavior using pass and nopass? The extra layer will take the internet speed down when connected on vpn?

Thank you for your time and excellent program, I was able to create a vpn server on my raspberry in less than 5 minutes !!

**Comment by orazioedoardo** [comment]
Question is not clear to me. Is this the scenario?

work country(100/100) --VPN--> home country(100/10) = speed: 55/11

home country(100/10) --VPN--> work country(100/100) = speed: 35/25

By the way using pass or no pass should not slow down the connection since there is no extra layer of encryption on the tunnel. The password is only used by the client to decrypt his private key upon authentication.

**Comment by badanas** [comment]
The situation was

work country(100/100) --VPN--> home country(100/10) = speed: 55/11

Work country(100/100) --VPN--> work country(100/100) = speed: 35/25

But now seems to be fixed . Today I can get 55mb/40mb , that I think is a decent speed for a raspberry pi 3 using openvpn 2048 bytes
