### ISSUE TITLE
Dangers of 1024-Bit encryption?

### ISSUE THREAD

**Issue by terminalcat** [pivpn/pivpn#451]
Hello,
I am using 1024 Bit encryption because the privacy of my VPN does not concern me that much. I mainly use the fact that I can bypass firewalls(I am using port 443), and of course, I want the most speed so 1024 bit was good enough for me. And I'm kinda hoping that I am less of a target because this extra layer adds more hassle.
But what power do hackers have when they break the key? can they only see the data I am sending or do they have more power than that? (like, connect and hack my router for say or get banking info?)
if anyone can explain that would be great. I know this is not a real issue but I couldn't find info online.

Many thanks

**Comment by orazioedoardo** [comment]
1024 bit encryption is good against casual attackers but it’s considered deprecated as of now, most modern browsers won’t even allow you to connect to a website that uses such encryption.

I strongly suggest you to switch to 2048 bit, reinstalling pivpn is the fastest way to do it. You will also need to regenerate the .ovpn files.

Consider that there is a little to none drawback in using 2048 bit or higher because the certificates are only used during autentication (ank key renegotiation, which occurs every hour), not during VPN usage.

If you feel you should get more speed out of your connection you could lower the symmetric cipher from AES-256-CBC to AES-128-CBC which is still very secure.

If your certificate is cracked (because of weak encryption or stolen config file), they can impersonate you, thus having an entry point inside your local network, where they could try to attack other computers or sniff/tamper/hijack traffic.

**Comment by terminalcat** [comment]
Wow thanks for expaining! 
I will try 2048 bit, but if i get a speed drop over 20% i will come back here and ask how i can lower down to AES-128-CBC.

Many thanks!

**Comment by terminalcat** [comment]
Hello,
I went from 63 Mbps/s to 50 Mbps/s which to be honest is fine, but if it is still as secure i woulden't see a con in switching to AES 128 Bit sooo. Could u explain XD

Many thanks!

**Comment by orazioedoardo** [comment]
Well, that is [unexpeced](https://community.openvpn.net/openvpn/wiki/HOWTO#LargerRSAkeys) Double check your home network, if you have local clients using bandwidth, you will clearly get lower speed over the tunnel.

**Comment by terminalcat** [comment]
hello,
I just realized that my sister was back from vacation and she was using Skype and watching movies so that would explain the speed drop. But what u are saying is that if my VPN speed is Slower than my internet speed I should change to AES-128-BIT? because my internet speed without VPN is 120 down and with VPN 50? are there any cons to using 128 Bit. because of the sentence: if u really want to change it. sounds a bit like it has some downsides XD

many thanks!

**Comment by orazioedoardo** [comment]
Suppose your internet speed at home is 100 down - 50 up. When you connect to the VPN and run the speedtest your client download/upload speed will be at most 50.

When your client downloads something, the server has to send (upload) such data to you and can do it as 50 Mb/s max. When your client uploads something, the server has to upload your data as well and can do it as 50 Mb/s max.

BUT, if your server is configured with compression (pivpn is), sometimes you can get even better speed with vpn.

Second scenario, same home speed but (for example) 20 Mb/s via the VPN. There are plenty of reasons for the speed drop:
1) Far away server
2) Slow client speed (weak wifi network, low signal cellular connection).
3) Not so powerful server

If reasons 1 and 2 have been excluded, then you may think that your Raspberry Pi cannot sustain such encryption requirement at the aforementioned speed. If that’s the case, you can lower the cipher size -> lower CPU requirement and check if the throughput is higher.

Since you have 50 MB/s with VPN you are perfectly fine with AES-256 (and RSA 2048).

**Comment by cfcolaco** [comment]
couldn't explain it better!! thanks a lot @orazioedoardo

**Comment by terminalcat** [comment]
Hello,
Wow, that made so much sense!
I guess that is the best speed I can get out of my VPN because my home internet is 20 MBP/S upload and I'm getting around 60 Mbps/s with my VPN
but I think the pi is still bottlenecking because I am getting 100% usage on 1 core.
so I will try the 128 Bit and post the results!

many thanks.

**Comment by orazioedoardo** [comment]
One more note: compression relies on redundancy, a chunk of data that looks like this “AAAAAAAAAAAAAAA” is very easy to compress, just send “15 As”. On the other and, if your data look like this “AHBJDBDFHQWUHIF” it’s harder to spot a patter, result is that compression will not be very effective and you won’t get such a huge gain.

Take for example https traffic, which is already encrypted from server to client. Modern ciphers have the property to “look” like random noise from an observer’s point of view. As mentioned above random data does not compress well, so less benefit. Standard http traffic, instead, should compress more.

**Comment by terminalcat** [comment]
Hello,
I tested with 128 Bit and with 256 Bit on the same server and just minutes away from each other.
The speed difference was zero, I am still getting ~55 Mbp/s. But the CPU usage was not locked at 100% but at 80%. also the ping improved by 3MS. so I am going to use 128 bit just so my raspberry pi has
little less struggle, and there might be a speed boost when more then 1 client is using the raspberry pi.
the VLC file downloaded in 4-5 seconds when using the VPN.

many thanks.

**Comment by cfcolaco** [comment]
@terminalcat just to give you my experience ... My server is at home in the North of Europe and right now I am in the UK, My connection at home is 100 / 100... I have my wife at home watching streams, IPTV, watching youtube, porn or whatever she likes to do on the web,  while I have one of my Rpis as torrent client, ... and I am 90% of my time VPN'ed home from hotels connections and I can easily watch my movies and series all this with the default OpenVPN setup from pivpn, ssh into my cloud servers, do my day-to-day life ... so .. that shouldn't actually be an issue tbh...

**Comment by cfcolaco** [comment]
closing ... seems the discussion ended. nothing more to add.
