### ISSUE TITLE
PiVPN and Fail2ban: Failed connections don't appear in log

### ISSUE THREAD

**Issue by chazLnerd** [pivpn/pivpn#453]
Hello!

I've set up PiVPN on Raspbian Stretch Lite. So far, everything has been working and I can connect from remote IPs. Now I want to set up Fail2ban in order to secure the open port. 

After following Fail2ban's OpenVPN tutorial, Fail2ban failed to block my remote test connections (after multiple incorrect password attempts). https://www.fail2ban.org/wiki/index.php/HOWTO_fail2ban_with_OpenVPN

When I checked "/var/log/openvpn.log", I noticed that PiVPN was not making note of any of my failed authentications. I've changed verbosity level in "/etc/openvpn/server.conf" to "verb 9", but I still don't see failed connections in my logs.

Am I looking in the wrong place for these logs? And how secure is PiVPN without Fail2ban?

**Comment by terminalcat** [comment]
Hello,
did u change the port in OpenVPN or not?

many thanks

**Comment by cfcolaco** [comment]
@chazLnerd and @terminalcat  you are clearly misunderstanding concepts here!! I will try to make this a bit clear for you, 

PiVPN is not a piece of software by itself!! Is just a script that automates the installation of **OpenVPN** having also a collection of scripts that helps you out to manager your **OpenvPN** Server

So ... you have to check on how to config **Fail2Ban With OpenVPN** ALSO, you have to be aware that for a hacker to be able to hack your OpenVPN server there's the need for A LOT of permisses

1 - Outdated Software with unfixed security bugs
or 
1 - The Attacker needs to have a Valid Certificate
2 - The Attacker needs to know the password to Decrypt the certificate

Without any of these combinations, no joy! Having this said ... hackers don't usually lose their time banging directly to a VPN server ... the time consumed VS reward is just not worth it ... it is like being a fly banging against a window! 

Long story short, Fail2Ban is made to protect you against brute force attacks, but there is no way ( at least that I know ) to brute force a VPN. Why? 

Short answer because I am not much into the encryption scene and AFAIK the password you provide when generating the certificate is not made for authentication on the server but to open the certificate that will encrypt your traffic! So if a hacker manages to get his hands on any of your certificates ... he still needs to be able to open it, and for that he needs the password, and to test for weak passwords, the "brute-force" is done locally in the Hacker machine and there my friend .. there is no Fail2Ban to save you! 

Bottom Line ... AFAIK Fail2Ban is useless with OpenVPN!


Hope This Clears you a bit! 

@redfast00 @0-kaladin you guys clearly understand this topic better than me ...so if I am wrong at any point please correct me!

**Comment by redfast00** [comment]
OpenVPN doesn't really need fail2ban since it uses a certificate to authenticate. These certificates can't be bruteforced. Another layer of protection we use is a password on the certificate: even if an attacker obtains the certificate, he then still needs to crack the password in order to connect to the VPN server. Fail2ban is useful for securing SSH though: since SSH can use a password, it can be vulnerable to bruteforcing. Fail2ban can then ban an IP address that tries to login too much. A better solution for this vulnerability is to only allow public key authentication for SSH.

**Comment by redfast00** [comment]
Closing this since it is unrelated to PiVPN
