### ISSUE TITLE
Server only accessible through outside network

### ISSUE THREAD

**Issue by isnes2000** [pivpn/pivpn#459]
# PiVPN Issue Template
 i installed pivpn no problem, and when I try connecting to it from my phone on 4g, I can get a connection, but if I change to my home's wifi network, or use my desktop connected via Ethernet, it just holds for a minute and until it timeouts. I don't really know where to start with this. I believe My ports are forwarded, and I was able to have my router set my ip.
Here's my debug output, hopefully this helps
`::: Generating Debug Output
:::					:::
::		PiVPN Debug		 ::
:::					:::
::	Latest Commit			 ::
:::					:::
commit abdce6c333bb982965990298d4a3d4b3c49a745b
Merge: 72b3dc2 93e4ba5
Author: Carlos Colaço <cfcolaco@gmail.com>
Date:   Wed Jan 17 21:04:45 2018 +0000

    Merge pull request #441 from peterlewis/patch-1
    
    Update README.md to correct 'thier' to 'their'
:::					:::
::	Recursive list of files in	 ::
::	/etc/openvpn/easy-rsa/pki	 ::
:::					:::
/etc/openvpn/easy-rsa/pki/:
ca.crt
cole.ovpn
crl.pem
Default.txt
dh2048.pem
index.txt
index.txt.attr
index.txt.attr.old
index.txt.old
issued
phone.ovpn
private
serial
serial.old
ta.key

/etc/openvpn/easy-rsa/pki/issued:
cole.crt
phone.crt
server_A6LYT0daQCp6tFEx.crt

/etc/openvpn/easy-rsa/pki/private:
ca.key
cole.key
phone.key
server_A6LYT0daQCp6tFEx.key
:::					:::
::	Output of /etc/pivpn/*		 ::
:::					:::
:: START /etc/pivpn/DET_PLATFORM ::
Raspbian
:: END /etc/pivpn/DET_PLATFORM ::
:: START /etc/pivpn/INSTALL_PORT ::
1194
:: END /etc/pivpn/INSTALL_PORT ::
:: START /etc/pivpn/INSTALL_PROTO ::
udp
:: END /etc/pivpn/INSTALL_PROTO ::
:: START /etc/pivpn/INSTALL_USER ::
pi
:: END /etc/pivpn/INSTALL_USER ::
:: START /etc/pivpn/NO_UFW ::
1
:: END /etc/pivpn/NO_UFW ::
:: START /etc/pivpn/pivpnINTERFACE ::
eth0
:: END /etc/pivpn/pivpnINTERFACE ::
:::					:::
:: /etc/openvpn/easy-rsa/pki/Default.txt ::
:::					:::
client
dev tun
proto udp
remote 204.14.185.217 1194
resolv-retry infinite
nobind
persist-key
persist-tun
key-direction 1
remote-cert-tls server
tls-version-min 1.2
verify-x509-name server_A6LYT0daQCp6tFEx name
cipher AES-256-CBC
auth SHA256
comp-lzo
verb 1
:::					:::
::	Debug Output Complete		 ::
:::					:::
::: 
::: Debug output completed above.
::: Copy saved to /tmp/debug.txt
::: 
`

**Comment by jcstill** [comment]
I as well have this (issue??). I put question marks because it isn't really an issue. Even if it worked, you probably don't want to connect to the VPN from the same network.

Here goes my best to explain why: (assuming the connection would work in the first place)

Lets say you have gigabit internet, on your phone/laptop you get 1Gb/s.
Lets also say that you get 750Mb/s on the pi. (pi is slower just because I said so, but could potentially be faster in real life)

When you try to connect to a website through the VPN from the laptop (both VPN and laptop on the same network);
- Your laptop encrypts all the packets being sent
- All packets of data from the laptop go out onto the wilderness that is the World Wide Web (looking for your router's public IP)
- When your router's public IP is found, the packets come in and appear to your router as if they were from anywhere else on the planet (with an internet connection, of course)
- Your router sends (forwards) the packets to the pi
- The pi decrypts them 
- The pi then sends them back out through the router and onto the internet

You see, connecting to the VPN from the same network is kind of counter-productive. Not only because you loose connection speed (due to the pi's slower connection, mentioned before) but because your packets have to be encrypted, go out to the internet, come back, get decrypted, and sent back out. (also since your packets are decrypted here, it is as if you were sitting at home browsing the internet.)

Even in ideal, laboratory controlled, circumstances, you wouldn't even get a connection speed as that of the pi because of the time spent processing the data (mentioned above). While I cannot say for sure, it would be dramatically less than the pi's claimed 750 Mb/s. maybe it would be down in the 500Mb/s? but who knows? Definitely would be less than the original 1Gb/s.

**Comment by orazioedoardo** [comment]
@jcstill is right, not only is counter-productive but it may not work at all (as in you case) because of NAT loopback. Basically some routers do not support or do not allow lan clients to connect to another lan client via the public ip of the router.

**Comment by cfcolaco** [comment]
There is no use to connect to VPN server that is inside the same network as we do!
It can work, but it will most likely fail for a wide variety of reasons! 

thanks @orazioedoardo for your help on that one, being your comment one of the reasons. 

Closing issue.
