### ISSUE TITLE
PiVpn not hiding my IP

### ISSUE THREAD

**Issue by briansdough** [pivpn/pivpn#478]
# PiVPN Issue Template

## Have you searched for similar issues and solutions? 
    (yes/no / which issues?) 
  

## Console output of `curl install.pivpn.io | bash`
```
  Output Here
```

## Console output of `pivpn add` or `pivpn add nopass`
```
  Output Here
```

## Console output of `pivpn debug`
```
  Output Here
```

## Console Output of `sudo iptables -t nat -S`
```
  Output Here
```

## Console Output of `sudo iptables -S`
```
  Output Here
```

## output of `sudo netstat -uanp | grep openvpn`

```
  Output Here
```

## Have you taken any steps towards solving your issue? 
     which?

**Comment by briansdough** [comment]
Sorry Im new to this and not even sure how to open this request.

I setup OpenVpn on my raspberry pi 3 and it's connected to my windows 10 computer and Android phone though it's not hiding my IP. Any thoughts?

Thanks

**Comment by d0nlab** [comment]
So you have a pi3 with pivpn installed. You have a win10 and Android client with ovpn files & clients installed. When you are connected from phone through vpn and you go to whatismyip.com it displays the ip from your phone carrier or home internet ip?

**Comment by briansdough** [comment]
Yes, exactly as you described.

**Comment by briansdough** [comment]
Yes, exactly as you described.

On Feb 24, 2018 4:31 PM, "d0nlab" <notifications@github.com> wrote:

So you have a pi3 with pivpn installed. You have a win10 and Android client
with ovpn files & clients installed. When you are connected from phone
through vpn and you go to whatismyip.com it displays the ip from your phone
carrier or home internet ip?

> On 24 Feb 2018, at 19:33, briansdough <notifications@github.com> wrote:
>
> Sorry Im new to this and not even sure how to open this request.
>
> I setup OpenVpn on my raspberry pi 3 and it's connected to my windows 10
computer and Android phone though it's not hiding my IP. Any thoughts?
>
> Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pivpn/pivpn/issues/478#issuecomment-368261859>, or mute
the thread

**Comment by d0nlab** [comment]
Well, which is it? The IP from your phone carrier or home ISP?

**Comment by briansdough** [comment]
When WiFi is on his my home IP, when 4g is on it's the phone companies.

**Comment by cfcolaco** [comment]
@briansdough let's try to solve some misconceptions first. 

1) PiVPN does not hide your IP address Neither does OpenVPN ... PiVPN Installs OpenVPN, OpenVPN is a VPN Server. 
2) Not every article on the internet is right, and very often they lead people to think an OpenVPN server is an internet Privacy and Security Miracle that will make you vanish on the web and no one will know who you are ... That's not true.

Let's try to fix this then.

Whenever you connect to your VPN the IP address the "internet" is going to see is the Public IP address of your OpenVPN server Network. Does this make sense? 

Let's Give a practical example: 

You are in a Hotel room in a different country of yours, The Ip address the internet is going to see is the HOTEL Network Public IP address. OK? 
Now as a concerned user, you have a VPN at home, so you can get better privacy on your traffic and to avoid prying eyes in public networks such hotels and so on, while in the hotel you connect to your OpenVPN server (installed by PiVPN), from now on, no one inside the Hotel can "understand" the traffic going from your computer (because it is encrypted) and the Internet will see your Home IP address instead of the hotel IP address. 

Was this clear enough? 


Now that we solved the misconception issue..... Your VPN Server is Working, right? you can connect to it, and access the internet correct?

**Comment by briansdough** [comment]
Thanks for the info that is very helpful. So if I understand correctly PIVPN hides what i'm doing on the internet but anyone looking can see its my traffic, correct? 

Yes, everything else is working correctly though my download/upload speeds are down about 50%, is that normal too?

**Comment by cfcolaco** [comment]
@briansdough It """"Hides""""" what you are doing between your Computer and VPN server. 
This means that no one in the same local network as you can understand the traffic because it is encrypted, however, from the VPN server to the internet works exactly the same as any other place, was that clear? 

Let me give you a practical and clear example.... 

you are at a Hotel, you connect to your VPN at home, you hack an NSA // FBI /// Sex Shop Website .... they will be able to track exactly what you done and know that you are the guy hacking them, they will request your ISP the info on who was using that IP address in that given time and will knock on your door! got it? 

And yup having such drops are expected! it can be even worse! 
What will influence? 
1 - The Bandwith of network you are connecting to
2 - Upload speed of your connection ( if you have 50 Mbits up at home, and downloading from a 100Mbis network, you will only get """"""50 Mbits""""""" )
3 - The route between the network you are into and your Home
4 - RPI nic  is only 100Mbits which will suffer losses as well. 

AAAND Much more!

**Comment by briansdough** [comment]
Yes, very helpful thanks. Great analogies too!

**Comment by cfcolaco** [comment]
As everything seems to be working I will be closing this issue... feel free to come back with any questions in the future

**Comment by stasky15** [comment]
> @briansdough let's try to solve some misconceptions first.
> 
> 1. PiVPN does not hide your IP address Neither does OpenVPN ... PiVPN Installs OpenVPN, OpenVPN is a VPN Server.
> 2. Not every article on the internet is right, and very often they lead people to think an OpenVPN server is an internet Privacy and Security Miracle that will make you vanish on the web and no one will know who you are ... That's not true.
> 
> Let's try to fix this then.
> 
> Whenever you connect to your VPN the IP address the "internet" is going to see is the Public IP address of your OpenVPN server Network. Does this make sense?
> 
> Let's Give a practical example:
> 
> You are in a Hotel room in a different country of yours, The Ip address the internet is going to see is the HOTEL Network Public IP address. OK?
> Now as a concerned user, you have a VPN at home, so you can get better privacy on your traffic and to avoid prying eyes in public networks such hotels and so on, while in the hotel you connect to your OpenVPN server (installed by PiVPN), from now on, no one inside the Hotel can "understand" the traffic going from your computer (because it is encrypted) and the Internet will see your Home IP address instead of the hotel IP address.
> 
> Was this clear enough?
> 
> Now that we solved the misconception issue..... Your VPN Server is Working, right? you can connect to it, and access the internet correct?

Clearest explanation ever seen. Thanks!
