### ISSUE TITLE
Can't revoke certificate

### ISSUE THREAD

**Issue by homerybart** [pivpn/pivpn#517]
Hi

  I have a certificate, that I have not generated, and I can not revoke it, 

 # pivpn -r server_6iK5GG2iRHgZnF5Z
 # You passed an invalid cert name: 'server_6iK5GG2iRHgZnF5Z'!

How can I delete this certificate?

Thanks in advance.

**Comment by justinamcafee** [comment]
That certificate is your server's certificate. It will generate this file on any server you create. The output of ````$: pivpn -l ```` should show this certificate along with a note that "The first entry should always be your valid server." It would make senses that your server needs a certificate in order to sign other certificates and acting as a CA. 

@redfast00 Can we resolve this?

**Comment by redfast00** [comment]
Yup, don't revoke the server cert.
