### ISSUE TITLE
Tomato Shibby VPN Client Setup

### ISSUE THREAD

**Issue by billsteiner** [pivpn/pivpn#519]
I have a router setup with Tomato Shibby and I would like to set it up to be able to connect to my Pivpn as a client. In order to accomplish that I need the following keys:
Certificate Authority

Client Certificate

Client Key

If I edit the ovpn file I can see what I believe maybe those keys but I am not sure, can anyone tell me if those keys are in the file and which ones would tie to the proper keys listed above?
Thank you

**Comment by orazioedoardo** [comment]
- Copy the content between`<ca></ca>` tag to a file named `ca.crt`
- Copy the content between `<cert></cert>` tag to a file named `client.crt`
- Copy the content between `<key></key>` tag to a file named `client.key`
- You should also copy the content of `<tls-auth></tls-auth>` (or `<tls-crypt></tls-crypt>`) to a file named `ta.key`
- Remove the tags and the content from the original file.

**Comment by billsteiner** [comment]
Thank you, got it going with your help. It connects but doesn't seem to route through the VPN. When I query the local pc's ip address using whats my ip it still shows the local ip address not the connected VPN's ip address. Can you give me some guidance?

**Comment by orazioedoardo** [comment]
Post the server log (omit the client ip): `cat /var/log/openvpn.log`

**Comment by orazioedoardo** [comment]
Username/Password Authentication: Checked or Unchecked (Checked)
Username: xxxxxx
Password: xxxxxxxxxxx
User Authen Only: Checked or Unchecked (Checked)

I'm not sure if usernmane password authentication should be enabled or not (the above) because we don't login with username but only with a certificate and a password (if you generated a certificate with a password). So you should try several combination of those, or create a configuration without password.

Extra HMAC authorization tls-auth (Enabled)
Compression: Disabled, None, Enabled, Adaptive (Enabled)

tls-auth is enabled in the conf, same with compression. However your router doesn't seem to support tls-crypt so if it doesn't connect you could also try uninstalling pivpn and reinstalling without 2.4 features.
We should be able to tell more with the server logs, however you forgot to post them.

**Comment by billsteiner** [comment]
Sorry, send wrong file, here is the server log
[openvpn.log](https://github.com/pivpn/pivpn/files/1943230/openvpn.log)

**Comment by orazioedoardo** [comment]
As i expected the router doesn’t connect because the pi doesn’t find the hmac header, enable those option and try again:

> Extra HMAC authorization tls-auth (Enabled)
Compression: Disabled, None, Enabled, Adaptive (Enabled)

**Comment by orazioedoardo** [comment]
You uploaded the file "Router VPN Client Settings.txt" where you showed me the settings you applied on your router. The above two are the ones you should change (from disabled to enabled).

**Comment by billsteiner** [comment]
Extra HMAC authorization (tls-auth) choices are "Bi-directional or Incoming (0) or Outgoing (1)"
Compression choices are "Disabled or None or Enabled or Adaptive"
So I have set Compression to "Enabled"  and tried each of the HMAC authorization settings and results were all the same, connected but still no change in my client ip address.

**Comment by billsteiner** [comment]
Here is a copy of the PiVPN log file after I made the changes to the client and used each of the each of the HMAC settings.
[openvpn.log](https://github.com/pivpn/pivpn/files/1948057/openvpn.log)

**Comment by orazioedoardo** [comment]
Thats weird, with hmac set to outgoing (1) on the router it should work. It’s a bit hard at this point, considering that the router should automatically pick up the settings from the config file. Perhaps you could post the client config (without the certificates, ecc.) and some screenshot of the router vpn settings.

**Comment by billsteiner** [comment]
Here are shots of the router settings and a copy of the client config. Thanks again for all this help.
[client config.txt](https://github.com/pivpn/pivpn/files/1951726/client.config.txt)
[VPN1.pdf](https://github.com/pivpn/pivpn/files/1951727/VPN1.pdf)
[VPN2.pdf](https://github.com/pivpn/pivpn/files/1951728/VPN2.pdf)
[VPN3.pdf](https://github.com/pivpn/pivpn/files/1951729/VPN3.pdf)
[VPN4.pdf](https://github.com/pivpn/pivpn/files/1951730/VPN4.pdf)
[VPN5.pdf](https://github.com/pivpn/pivpn/files/1951731/VPN5.pdf)

**Comment by orazioedoardo** [comment]
Your VPN is not actually running because your raspberry pi expects a valid hmac, and your router is missing it because you forgot to fill the content of `tls-auth` In the `Static Key` form of the `Keys` subsection.

In the `Advanced` subsection enable `Redirect internet traffic` and set `Accept DNS configuration` to `Exclusive`.

If still doesn’t work, post the server log again.

**Comment by billsteiner** [comment]
Made the changes but still no luck, I can connect with my PC using OpenVPN Gui through the same router without a problem. Here is the latest server log, note the last connection was using my PC not the router.
Thanks again.
[PiVPN Server Log.txt](https://github.com/pivpn/pivpn/files/1953277/PiVPN.Server.Log.txt)

**Comment by 4s3ti** [comment]
Closing this, old topic, and seems to be unrelated with PiVPN at all.
