### ISSUE TITLE
Make static IP setup optional

### ISSUE THREAD

**Issue by cpoetter** [pivpn/pivpn#536]
Hi, 

thanks for making this awesome project! It works really great on my Raspberry Pi 3. I only have one little feature request:

Would it be possible to make the setup of the static IP during the installation option? 

Something like this must be easily possible if I see this function: `avoidStaticIPv4Ubuntu`

I may make a pull request myself if I find the time.

Thank you and continue your awesome work.

Best, 
Chris

**Comment by cfcolaco** [comment]
I don't think this is a feature we should add, will cause more issues for users without that much knowledge. 

the device will be a server, so it should have a static IP address, that's common sense, if you require a dynamic IP address you should do it by yourself manually, this way whoever needs that is sure of what is doing. otherwise, I can easily see a flood of users, "heey my VPN was working, now it isn't!!" 

What you thing @0-kaladin @redfast00 ??

**Comment by redfast00** [comment]
I explained it in the pullrequest, this is indeed not a thing we want in PiVPN because it's too specific.
