### ISSUE TITLE
Ports closed after install

### ISSUE THREAD

**Issue by RobertHosking** [pivpn/pivpn#559]
Steps Taken on Ubuntu 16.04 Digital Ocean droplet: 

1. Open ports in ufw `ufw allow 22`, `ufw allow 80`, etc

2. `ufw enable`

All specified ports are open and working fine.

3. install pivpn 

Ports appear closed. Websites are unreachable, ssh attempts fail, etc.

4. `ufw status`

shows that specified ports are still open and reachable from anywhere. New additions from the pivpn install are visible as well. 

Note: I am not sure if the install succeeded since I revert soon after noticing that these ports are unreachable. 

Any thoughts?

**Comment by 4s3ti** [comment]
hi @RobertHosking 
Sorry for the late reply. 

this is not really clear what you are attempting. 
if this issue is still a thing, please make a post at our subreddit and we will try our best to help you out. 
When requesting for help // support please try to be as clear as possible in order to help us help you by using our Issue template. 

https://github.com/pivpn/pivpn/blob/master/ISSUE_TEMPLATE.md


Closing this thread. 
Kind regards.
