### ISSUE TITLE
Failing to connect on ubuntu

### ISSUE THREAD

**Issue by epikgamerwmpp** [pivpn/pivpn#576]
I can not connect on ubuntu and the connection times out.

**Comment by soydepr** [comment]
Show log and reads

https://github.com/pivpn/pivpn/issues/567

**Comment by devZer0** [comment]
ubuntu network manager does not yet support tls-crypt, see https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/1749562?comments=all  and complain there. they need to fix their network manager

**Comment by devZer0** [comment]
you did not tell which ubuntu version. apparently network manager is already fixed in ubuntu 18.04 - but the problem remains in kubuntu 18.04 as kubuntu is using it's own kde based network manager which suffers from the (former) same problem of not being able to import tls-crypt zert from .ovpn file
