### ISSUE TITLE
Possible to have connected users be on the same Private IP Range as the router?

### ISSUE THREAD

**Issue by talormanda** [pivpn/pivpn#650]
I was wondering if at all possible, which file I could edit to make the connected VPN Users be on the same Private IP Range that my router hands out. Currently my router is set to 192.168.1.0/24 and the IP I get when connected to the pivpn is 10.8.0.2.

**Comment by LMS235** [comment]
In "/etc/openvpn" there is the file "server.conf" and the config "server 10.8.0.0 255.255.255.0" 

So the Server is 10.8.0.1 and the first client ist 10.8.0.2

But why do you want the same address range? Normally you work with corresponding routes between the networks.

**Comment by talormanda** [comment]
@LMS235 I wanted to try and have VPN clients see chromecast devices.

**Comment by LMS235** [comment]
you have to push the route for the internal adress range to the clients

for example via (in the server.conf):
push "route 192.168.1.0 255.255.255.0"

and if you wanna use your internal dns server:
push "dhcp-option DNS 192.168.1.1"

**Comment by talormanda** [comment]
@LMS235 While I can ping devices on 192.168.1.* ,  while my IP is 10.8.0.2, I am still unable to see "chromecast" devices. I suspect something else going on.

**Comment by atiti** [comment]
Chromecast uses mDNS and SSDP for discovery, which relies on multicast. Routing multicast over vpn is not an easy feat :)

**Comment by Danzig69** [comment]
you can ping 192.168.1.* because there is routing done by the PiVPN server

the command i had to use to edit the file server.conf on a Raspberry Pi 3 B+ is : 
sudo nano /etc/openvpn/server.conf
to exit CTRL-X
done directly on the Raspberry Pi in a terminal windows or with putty using SSH IF SSH is enabled on the Raspberry Pi
After editing the file server.conf you need to reboot the openvpn server with this command: 
sudo systemctl restart openvpn@server

In all the explication bellow, i'm using the LTE network
pivpn work great with my Google PixelBook but my Samsung Galaxy s9+ SM-G965W do not work. Same server configuration but not the same result. On the S9+ i can ping the device but unable to access theyr web page. I have multiple object with a web page and none work with the S9+, but all work with the PixelBook.

The push "route 192.168.x.x 255.255.255.0" change nothing for both device. PixelBook continu to work with or without but the S9+ never work. It connect, received an ip 10.8.0.x but Internet Web page (www.cnn.com) or 192.168.x.x web page do not work! 

The only way OpenVPN and pivpn are able to work on the S9+ is if the S9+ is connected to my wifi. But it's useless as i need the VPN when i'm outside my home using LTE/4G.
Clearly a routing problem in the S9+

**Comment by reinisb** [comment]
> Chromecast uses mDNS and SSDP for discovery, which relies on multicast. Routing multicast over vpn is not an easy feat :)

Yes, it seems that this is the reason. Do you know if anyone has managed to "repeat" those multicast "broadcasts" over to the OpenVPN server subnet so that the OpenVPN clients could see those multicast "broadcasts"?

**Comment by 4s3ti** [comment]
Multicast broadcasts don't work over L3 VPN ... for that, you will need L2 VPN aka bridged mode and PiVPN doesn't support setting up OpenVPN as bridged. 

Also ... setting the VPN subnet to the same subnet as your local network will result in routing issues, therefore, VPN will stop working properly. 

PiVPN already sets up all the routing you need so you can reach devices on your local network. 

Closing this issue.
