### ISSUE TITLE
[HELP] Access NAS / Other Network Devices while Connected Remotely

### ISSUE THREAD

**Issue by uber1geek** [pivpn/pivpn#714]
Everything is working as expected, can connect and browse the internet, also can connect to local devices with their IP (eg:192.168.0.1) but I cannot see any network devices, like my Synology NAS on the network section.

Is there a workaround this?

**Comment by devZer0** [comment]
please explain what's "the network section" ?

**Comment by uber1geek** [comment]
@devZer0  My bad, I mean to say the network devices list.

**Comment by devZer0** [comment]
that behaviour is quite normal if you are on a different/remote subnet like vpn. 

not an pivpn issue

**Comment by barbequesauce** [comment]
Without a wins server configured, smb shares are only advertised on the local subnet. Wins ‘ role is to accumulate those advertisements and provide them to disparate networks...

**Comment by uber1geek** [comment]
Is there a way around this issue?

**Comment by barbequesauce** [comment]
Not sure if Syno offers a WINS server package? It might be an option under the CIFS/SAMBA server config too, not sure as I don’t run Synology.

**Comment by devZer0** [comment]
i think there is no easy way to resolve this.

**Comment by 4s3ti** [comment]
This is not PiVPN related. 

Devices that connect to  OpenVPN are in a different subnet and the reason why you can access to your home subnet is because OpenVPN is setup with the route to reach out that network. 
The network devices section on widows only works with shares // devices under the same network which is not the case when you connect to OpenVPN, which as stated has no wins and samba shares and ll those bells ans whistles. 

One thing you can do to make your life easier is to use your router as DNS Server and that way you can reach devices trough their hostnames instead of IP addresses. 

If you want to keep this thread discussion please take it over subreddit.
https://www.reddit.com/r/pivpn/
from now on github issues should be used only for pivpn and code related issues, and i will be closing out any threads that are not directly related. 


having this said i am closing this thread. 
Thanks for the understanding.
