### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by soydepr** [pivpn/pivpn#718]
Unable to install 

Your system is up to date! Continuing with PiVPN installation...
Can't call method "set" on an undefined value at /usr/share/perl5/Debconf/FrontEnd.pm line 126, <GEN0> line 5.
Use of uninitialized value $ret in scalar chomp at /usr/share/perl5/Debconf/Client/ConfModule.pm line 132, <STDIN> line 4.
Use of uninitialized value $ret in split at /usr/share/perl5/Debconf/Client/ConfModule.pm line 133, <STDIN> line 4.
Use of uninitialized value $ret[0] in string eq at /usr/share/perl5/Debconf/Client/ConfModule.pm line 134, <STDIN> line 4.
Use of uninitialized value $ret[0] in string eq at /usr/bin/debconf-apt-progress line 350, <STDIN> line 4.

**Comment by richard-scott** [comment]
I get this on Ubuntu:

```
+ command -v debconf-apt-progress
+ grep -q https /etc/apt/sources.list
+ debconf-apt-progress -- apt-get --yes --no-install-recommends install openvpn git tar wget grep iptables-persistent dnsutils expect whiptail net-tools
Can't call method "set" on an undefined value at /usr/share/perl5/Debconf/FrontEnd.pm line 126, <GEN0> line 5.
Use of uninitialized value $ret in scalar chomp at /usr/share/perl5/Debconf/Client/ConfModule.pm line 132, <STDIN> line 4.
Use of uninitialized value $ret in split at /usr/share/perl5/Debconf/Client/ConfModule.pm line 133, <STDIN> line 4.
Use of uninitialized value $ret[0] in string eq at /usr/share/perl5/Debconf/Client/ConfModule.pm line 134, <STDIN> line 4.
Use of uninitialized value $ret[0] in string eq at /usr/bin/debconf-apt-progress line 350, <STDIN> line 4.
```

**Comment by devZer0** [comment]
you both did not tell what distro version you are using.

pihole installer seems to have a similar problem:  https://www.reddit.com/r/pihole/comments/6n9e0w/cant_install_pihole_get_these_errors_tried/

**Comment by soydepr** [comment]
> you both did not tell what distro version you are using.
> 
> pihole installer seems to have a similar problem: https://www.reddit.com/r/pihole/comments/6n9e0w/cant_install_pihole_get_these_errors_tried/

Using  raspbian stretch

**Comment by huongminh** [comment]
I came across the same error when reinstall pivpn. I tried this and it fixed the issue.
apt-get install --reinstall debconf

**Comment by delgardoxx** [comment]
I got the problem after installing, uninstalling and reinstalling pivpn.
The directory /opt/pivpn does not exist. The pivpn command ist not available.
What can I do to clean the system so that a new installation is possible?

:::
::: You are root.
::: Verifying free disk space...
:::
::: Checking apt-get for upgraded packages.... done!
:::
::: Your system is up to date! Continuing with PiVPN installation...
::: Static IP already configured.
::: Using User: pi
:::
::: Checking for existing base files...
:::    Checking /etc/.pivpn is a repo... OK!
:::     Updating repo in /etc/.pivpn... done!
:::
::: Stopping OpenVPN service... done.
      
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
::: Install Complete...
::: Restarting services...
Synchronizing state of openvpn.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable openvpn
::: done.
:::
::: Installation Complete!
::: Now run 'pivpn add' to create an ovpn profile for each of your devices.
::: Run 'pivpn help' to see what else you can do!
::: It is strongly recommended you reboot after installation.
:::
::: The install log is located at: /etc/pivpn/install.log

**Comment by 4s3ti** [comment]
Please give it a shot again as a couple of issues have been fixed in the meanwhile. 

I'd recommend reinstalling raspbian and running PiVPN again. 

then if you still see the same issue please comeback and fill the issue template the best you can please.

Kind Regards.
