### ISSUE TITLE
re-generate .OVPN file

### ISSUE THREAD

**Issue by felixjmm** [pivpn/pivpn#726]
hello guys.

do you know how to generate again a ovpn file for an existing pivpn user??
i moved my pivpn server backup, but i lost the ovpn files for the users. how do i re-issue them?

thanks.

**Comment by devZer0** [comment]
did you notice there is a copy in /etc/openvpn/easy-rsa/pki/ ?

**Comment by mwoolweaver** [comment]
wonder how hard it would be to implement a way to grab them via the `pivpn` command?

**Comment by devZer0** [comment]
sorry, but please let's not discuss a non issue (i think it is one). 

if you loose files and have no backup - no compassion. 

since you need that file for import on the client side anyway - you can always easily recreate that files by deleting and re-adding appropriate users. 

why do you need files for users which they should already have? and if they don't have the files - just recreate them and you're done.

**Comment by orazioedoardo** [comment]
Also, you can just revoke the user and create a new one with the same name.

**Comment by 4s3ti** [comment]
just a quick tought ... re-creating user certificate seems to be something we should never be possible! 
If certificate was lost for whatever reason ... then Just revoke and regenerate a new one!

Even having a copy of it for me seems to be a very unreasonable thing to do! but that goes up to anyone ... i'd never store any copy of my or any user certificates. if it dies .. then just revoke and create a new one! if the old one is lost.. who knows who can be using it? maybe me being to paranoid. 

Closing this, 
if you wanna keep the discussion please take it up to reddit. 
https://www.reddit.com/r/pivpn/

Kind Regards,
