### ISSUE TITLE
Correct FAQ - Allow Clients to connect but block their access to the internet

### ISSUE THREAD

**Issue by lukasszz** [pivpn/pivpn#776]
[https://github.com/pivpn/pivpn/wiki/FAQ](https://github.com/pivpn/pivpn/wiki/FAQ)

> **Allow Clients to connect but block their access to the internet**
>
> push "192.168.2.0 255.255.255.0"

*Should be:*

**Allow Clients to connect but block their access to the internet**

```
push "route 192.168.2.0 255.255.255.0 10.8.0.1 1"
          route network/IP [netmask] [gateway] [metric]
```

**Comment by orazioedoardo** [comment]
From the manual:

> gateway default — taken from –route-gateway or the second parameter to –ifconfig when –dev tun is specified.

ifconfig is not used in server.conf but `server 10.8.0.0 255.255.255.0` is:

> if dev tap OR (dev tun AND topology == subnet):
   ifconfig 10.8.0.1 255.255.255.0

So you don't need to specify the gateway, not sure about the metric though, you are specifying 1 instead of the default 0. By the way, I have always used `push "192.168.2.0 255.255.255.0"` without issues.

**Comment by 4s3ti** [comment]
The FAQ is correct, or at least it has been working for quite a while now. 
closing.
