### ISSUE TITLE
Why do I see my home IP when connecting to the VPN?

### ISSUE THREAD

**Issue by RikGIT1** [pivpn/pivpn#78]
I installed fresh Raspbian Lite image, and then installed piVPN.
On a client laptop i installed a client vpn.

When I am home in my own LAN, I prefer to connect to the PIVPN direct via the LAN to go out to the internet, and when Im outside on a public WIFI i like to use the public IP.. (by copying the .opvn file in the client, and change the IP to local and external)

But what I find weird is that the VPN service is active, my client VPN is connecting (to local and public (2 profiles)), but when I browse to a website that shows your Ip, I still see my IP address. Isn't VPN suppose to make everything anonymous?

so I guess my questions are:
1. why after connecting to VPN i can see my own IP address on the internet?
2. How to force all local devices on the LAN through the VPN server.

**Comment by guydeke** [comment]
"When I am home in my own LAN, I prefer to connect to the PIVPN direct via the LAN to go out to the internet, and when Im outside on a public WIFI i like to use the public IP.. (by copying the .opvn file in the client, and change the IP to local and external)"

When you are home, and connect to your VPN at home, yopu'll get a error onconnection because you're going in and out several times from thesmae address.

I dont know if I understand your queastion, but of course, when the PIVPN is at your home, you always see your home IP address. If you want to surf anonymously You need a VPN client service like PIA: https://www.privateinternetaccess.com/.

**Comment by karlpokus** [comment]
@RikGIT1 @guydeke Actually. It's very [possible](https://openvpn.net/index.php/open-source/documentation/howto.html#redirect) but seems to come with quite the penalty

> Redirecting all network traffic through the VPN is not entirely a problem-free proposition. Here are some typical gotchas to be aware of: - Many OpenVPN client machines connecting to the internet will periodically interact with a DHCP server to renew their IP address leases. The redirect-gateway option might prevent the client from reaching the local DHCP server (because DHCP messages would be routed over the VPN), causing it to lose its IP address lease. - Issues exist with respect to pushing DNS addresses to Windows clients. - Web browsing performance on the client will be noticably slower.
