### ISSUE TITLE
auth-user-pass won't read credentials from auth.txt

### ISSUE THREAD

**Issue by thisismyusernamerighthere** [pivpn/pivpn#812]
My PiVPN server works great, but I'm not able to automate connections with adding auth-user-pass auth.txt to the ovpn-file and then saving my credentials to auth.txt file. Do I need to change something else in the ovpn-file as well for this to work?

**Comment by 4s3ti** [comment]
Closing. 

1 - its not a PiVPN Server, its OpenVPN .. PiVPN its only the installer and provides some scripts to make the openvpn server management a bit easier. 
2 - This issue is not PiVPN related
3 - Issue template not properly filled, no logs, no information that we can use to help with your issue
4 - thread too old without any answers
