### ISSUE TITLE
Windows GUI- Saving Client password

### ISSUE THREAD

**Issue by MohammedHoosen** [pivpn/pivpn#84]
Is there a way to save the client password on the windows GUI? 

I tried this guide which suggests adding a line "auth-user-pass auth.txt" to the config file and saving the username & password to a text file "auth.txt" in the config folder, but it doesn't work. Also when I manually connect, it only asks for a password, not a username.
https://vpn.ac/knowledgebase/40/How-to-save-Username-and-Password-in-OpenVPN-GUI-Windows.html 

Also is there a way to create a client profile without a password, to avoid adding it to the client config?

**Comment by 0-kaladin** [comment]
it isn't a user pass which is why you can't save it.  its a pass to decrypt the certificate.
you can create the certificate with no pass as detailed here http://www.pivpn.io/ look at the pivpn command.  the add subcommand takes an optional nopass argument.  if you use that you won't be prompted for anything.  To be clear it is still rather secure.  you are using certificate auth instead of user/pass.  the default is to use the certificate auth that is encrypted with a password.  in your case you can just use the certificate after you create with the nopass options.

**Comment by 0-kaladin** [comment]
Closing as there is a `pivpn add nopass` option now as well.
