### ISSUE TITLE
Installation stops at call to debconf-apt-progress

### ISSUE THREAD

**Issue by Mausy5043** [pivpn/pivpn#846]
I'm using [raspberrypi-ua-netinst](https://github.com/FooDeas/raspberrypi-ua-netinst) (currently on Buster) and when installing on a Raspberry Pi 3B the installer quits mid-installation.  

This looks and feels exactly like these issues: 
  - [`pihole` #2934](https://github.com/pi-hole/pi-hole/pull/2934) 
  - [`pihole` #1756](https://github.com/pi-hole/pi-hole/issues/1756)

So, I checked the script and lo-and-behold:

https://github.com/pivpn/pivpn/blob/d0c10db6ec391961b7201fb564055c1176ca73e3/auto_install/install.sh#L497

Removing `debconf-apt-progress --` from this line makes the script work for me...
So, I'm guessing the same solution may apply here that the `pihole` team is conjuring up for the bug in their code.

**Comment by mbologna** [comment]
Same problem. I resolved it by installing `debconf`.

**Comment by mwoolweaver** [comment]
There’s a p/r for removing the dependency completely 

https://github.com/pi-hole/pi-hole/pull/2962

**Comment by 4s3ti** [comment]
this seems to be fixed here: https://github.com/pivpn/pivpn/blob/master/auto_install/install.sh#L1104-L1109

please reopen if this is still an issue.

**Comment by MichaIng** [comment]
@4s3ti 
Please consider to completely remove `debconf-apt-progress` from the installer, like it has been done for Pi-hole: https://github.com/pi-hole/pi-hole/pull/2962

Actually the problem is not only that an initially missing debconf or whiptail/dialog package can make it fail, but whenever dpkg asks for interactive input, it will wait forever. Obvious case is that one manually edits a config file, which is listed in any packages `conffiles`. dpkg will then prompt a question whether to keep the modified file or use the new one and some other options. In case of `debconf-apt-progress`, it will simply halt forever. APT and dpkg can be configured to answer this questions non-interactively, but this might be not always wanted, breaking user choice/configs, and the simple fact that `debconf-apt-progress` breaks any interactive prompt + input, while it cannot force dpkg to be non-interactive itself, makes it unusable. Basically this is something that needs to be fixed on debconf side, but until then it should not be used, as long as any installed package has or can have a declared config file at least.

It increases installer output quite a lot, but it can be reduced a bid: https://github.com/pi-hole/pi-hole/pull/3205
