### ISSUE TITLE
How to speak with my LAN?

### ISSUE THREAD

**Issue by chrbar11** [pivpn/pivpn#883]
Hi,

I've set pivpn on my Pi2 under DietPi.
I can etablish an VPN session but I can speak with devices on my LAN.
I can ping the IP Address of my Pi2 (VPN IP 10.8.0.1 and LAN IP 192.168.1.x), but I can't ping my router (192.168.1.x) or others LAN devices!

I use a DynDNS (No-IP) to join my VPN, it works great.
My network is 192.168.1.0 and the router IP Address is 192.168.1.1

I use these setting inside server.conf :
server 10.8.0.0 255.255.255.0
push "route 10.8.0.1 255.255.255.255"
push "route 192.168.1.0 255.255.255.0"
push "redirect-gateway def1"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"

Could you help me to be able to speak to my LAN devices?

Thanks,
Chris

**Comment by 4s3ti** [comment]
What is the subnet of the network you are connecting from? 

192.168.1.0/24 its a quite common subnet and if the network you are at has the same subnet you wont be able to reach the devices on your home network due to routing conflicts. 

For example: 

You are at a starbucks coffee shop and their subnet is: 192.168.0.0/24
Your Home: 192.168.0.0/24

you will be able to connect to your home but not access home devices.

**Comment by 4s3ti** [comment]
No answers. 
Closing.
