### ISSUE TITLE
Unable to create a profile with the name of an earlier  revoked (and renewed) one

### ISSUE THREAD

**Issue by sebelk** [pivpn/pivpn#894]
## In raising this issue, I confirm the following: 

`{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
Cannot add profile with the name of an already revoked profile with a renewed certificate

**To Reproduce**
1. pivpn add nopass
2. choose profile name, for exampple: **jdoe**  and expiration days (eg: 1)
3. cd /etc/openvpn/easy-rsa && ./easyrsa --days=1 renew  jdoe nopass
4. pivpn revoke
5. Choose **jdoe**
6. Repeat steps 1 and 2, then you will see:

```
!! This name is already in use by a Valid Certificate.
Please choose another name or revoke this certificate first.
```

**Expected behavior**
It should be allowed to create a new profile if en earlier one with the same name was revoked.

**Comment by orazioedoardo** [comment]
Works for me even though you are not supposed to do step 3 manually. If you do 1,2,3, then jdoe will show up as revoked on `pivpn list` and you won't be able to revoke again (steps 4 and 5) but you can add a new one with name jdoe.

**Comment by sebelk** [comment]
thanks @orazioedoardo , I meant "renew" not "revoke", I've edited it, please could you test it?

**Comment by orazioedoardo** [comment]
When you renew a certificate a new entry with the same name but different serial is created inside `/etc/openvpn/easy-rsa/pki/index.txt` and the client key and certificate is overwritten. So when you revoke a certificate with `pivpn revoke` it only revokes one entry (the newest). If you try to revoke again, it won't work since certificates had already been remove, and you can't add a new client because pivpn still sees the other valid entry.

**Comment by orazioedoardo** [comment]
This is more of a feature request than a bug, since renewing a certificate has never been taken into account. I'm not sure how would this be useful though: you would still need to copy new keys and certificates to an .ovpn file and transfer to the client but at that point you could just revoke the client and create a new one.

**Comment by sebelk** [comment]
That is not true. The easyrsa renew enables you to keep using the same client certificate. However, I've found the problem, the revoke command does not work out of the box with renewed certificates, that can be read in the file **easyrsa**:
```
# FIXME: Modify revoke() to also work on the renewed certs subdir
```

So it's a openvpn issue. I will report it there.

**Comment by TinCanTech** [comment]
Just a heads up to PiVPN devs, renewing a certificate is still a work in progress. There **may** be a new option which allows _either_ a new key or the old key to be used.

We are also aware of a minor _bug_ between versions (3.0.0 -> 3.0.5) vs 3.0.6 which is also related to renewal.
