### ISSUE TITLE
[BUG] master and test branches have diverged

### ISSUE THREAD

**Issue by garrettheath4** [pivpn/pivpn#896]
## In raising this issue, I confirm the following: 

- [X] I have read and understood the [contributors guide](https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting can be *is* directly related to the pivpn installer script.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pivpn/pivpn/wiki/FAQ), [closed issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed), and [open issues](https://github.com/pivpn/pivpn/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen)).

**Describe the bug**
Important fixes have been committed to the _test_ branch but not the _master_ branch. And features have been committed to the _master_ branch but not the _test_ branch. In other words, the two branches have diverged. According to the repo's [Network Graph](https://github.com/pivpn/pivpn/network), the branches have not merged with each other since Oct 14, 2019. 

**Expected behavior**
The _master_ branch should always be production-ready and the _test_ branch should be directly based on the _master_ branch (unless hotfixes need to be applied directly to the _master_ branch). When unit tests pass and/or it is decided that a new version of _PiVPN_ should be released/created, the _test_ branch should be merged into _master_ (ideally as a fast-forward merge) and any new features or improvements should be made on new branches that are based on the _test_ branch, not _master_.

**Comment by garrettheath4** [comment]
Depending on this project's maintainers' preference, a maintainer should merge _test_ into _master_ themself. Or if that is a daunting task (with a lot of merge conflicts) I can try my hand at merging the conflicts myself and then create a fork/pull request. I'd like to help.

**Comment by orazioedoardo** [comment]
Actually the test branch has both _new features_ and _fixes_ and while the master branch diverged by 16 commits, those are small changes. We have not yet decided when to merge test into master but If you want to help you can test... the test branch (all combinations wireguard/openvpn). Specifically on untested version like raspbian/debian stretch and ubuntu 16.04.

**Comment by 4s3ti** [comment]
@garrettheath4 thanks for your issue and for your concern. 

We are well aware of the divergence,

Under normal circumstances our policy is to never push anything to master directly, it always goes trough test first and then merged to master, if a urgent hotfix needs to go to master its then cherry picked. 

however due to the nature of the upcoming major changes that is expected and it should get back to normal as soon as test branch is ready to be Production ready. 

all changes to master as far as am aware have been also commited to test branch. 

Contributors should always PR from their form into test branch. 
PR into Master are rejected. 

Having this said I am closing this one, if there is any other concerns, please feel free to reopen or revert back. 

Kind Regards.
