### ISSUE TITLE
Allow setup as a client

### ISSUE THREAD

**Issue by 0-kaladin** [pivpn/pivpn#9]
~~After Issue #7 is completed,~~ I'd like to add the ability to configure openvpn as a client.  The installer should ask this first.  OR the client install curl's a different URL.  
The reason is that if an Amazon server is your openvpn server than a raspberry pi can be an openvpn client on your home network giving you a tunnel there all the time without the need to install an ovpn profile on every client device in your house.  Basically a Lan to Lan tunnel.

**Comment by guydeke** [comment]
You better do that this way: https://github.com/pivpn/pivpn/issues/73

**Comment by fmjensen** [comment]
[This](https://wiki.debian.org/openvpn%20for%20server%20and%20client) might be usefull inspiration for this issue.

I like the idea of having RPi's at both ends of the LAN to LAN VPN tunnel but i think it might be useful with some kind of web-interface on the RPi running as VNP Client & Router, so the VNP can be disabled in order to permit traffic to and from the Internet without the bottleneck that i imagine RPi VPN would be to large downloads that you would like to utilize all your available bandwidth, as example when installing say Fallout 4 ;-)

**Comment by mlacayoemery** [comment]
I really appreciate all the effort put into PiVPN! It has saved me so much time.

Related to this issue is [this post](http://alphaloop.blogspot.ch/2014/01/raspberry-pi-as-vpn-wireless-access.html) that shows how to setup a RPi as a wireless access point that moves all traffic over a VPN client. In that case there would be no need to choose between doing a VPN client or server as you could have both on one machine. I had the client part working, but when I installed PiVPN the client tun is no longer created, so it seems there is some sort of incompatibility.

**Comment by saqibshakeel035** [comment]
I have a query, can we setup a client using pivpn to access a remote vpn server which is not  pivpn based but cisco based shrew server ??

**Comment by 4s3ti** [comment]
Closing, 
Moving this to: 
https://github.com/pivpn/pivpn/issues/468
