### ISSUE TITLE
server down?

### ISSUE THREAD

**Issue by Loogard** [pivpn/pivpn#910]
just got a pi4 today and was eager to get the pivpn installed, but I don't seem to get any response from pivpn.dev. website/server seems down. Any alternative addresses to install from or should I expect pivpn.dev to be up and running shortly/looking for an alternative?

**Comment by 4s3ti** [comment]
Nope.. servers are up and running.
I get response from it.

**Comment by Loogard** [comment]
hmm, I can't visit https://pivpn.dev
nore run the install command. wird

**Comment by 4s3ti** [comment]
```
$curl -L -o /dev/null -s -w "%{http_code}\n" install.pivpn.dev
200
```

There are also other install alternatives from here: 

https://github.com/pivpn/pivpn/tree/test#installation


Can you give me the output of 

`dig pivpn.dev` or `nslookup pivpn.dev`
And
`dig install.pivpn.dev` or `nslookup intsall.pivpn.dev`

**Comment by Loogard** [comment]
hmm have to say tho. this is extremely weird, just tried open it on my phone when disconnected from my wifi. and it opens. but cant ping the server through the terminal or anything from within my local network.. first time that has ever happened with anything i think

**Comment by 4s3ti** [comment]
that is something on your network side ... 
check dns resolution as i have stated before.

**Comment by Loogard** [comment]
yeah as I said its weird, never had it before. Will have to look in my router see whats there:
this is how it looks currently:
C:\Users\bjorn>nslookup pivpn.dev
Server:  254.red-80-58-61.staticip.rima-tde.net
Address:  80.58.61.254

Non-authoritative answer:
Name:    pivpn.dev
Addresses:  88.198.194.195
          88.198.194.194


C:\Users\bjorn>ping pivpn.dev

Pinging pivpn.dev [88.198.194.195] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.

**Comment by 4s3ti** [comment]
hmm .. its resolving .. check your router, 
there might be a weird rule somewhere.

**Comment by Loogard** [comment]
I dont really know what i did to resolve the matter, but changed the DNS servers in the router and i could all of a sudden open the webpage and do the install. so up and running and working splendid to have access to my office from home. cheers for the replies and leading me down a path to success since i was basically just waiting for servers to pop online prior to getting to know they wee online and the issue was at my end.

**Comment by nowakommunikation** [comment]
Interesting, it seems I'm not the only one who cannot open pivpn.dev from my home network.

I looked around and it seems that other people, too, have problems calling .dev sites in general. (Although I can open web.dev just fine.) 
This

https://superuser.com/questions/1374892/dev-domains-dont-resolve

and this

https://superuser.com/questions/1413402/i-cant-visit-websites-that-have-dev-domain

didn't help me, though, because I don't have an /etc/resolver folder or file on my Raspberry Pi installation.

I then disconnected the Pi and set a regular DNS on my router and, lo and behold, I can open up pivpn.dev just fine. 

So it must have sth to do with my Raspberry Pi and/ or Pi Hole installation, but I don't know what. 

Any ideas?

Also: I recently had to restore a backup of the whole installation (Pi Hole & Pivpn). The Pi Hole works just fine, but I can't connect to the Pivpn anymore. 
Creating a new client ovpn profile didn't work either. 
I fear I might have to install it all over again (and creating the key takes ages on the old Pi). But I guess I first have to resolve the DNS issue with the pivpn.dev or otherwise it won't be able to curl.

Best regards

**Comment by 4s3ti** [comment]
That is a new to me ... but lets take care of one thing at a time ... 

for other issues please open an issue and feel the issue template so we can help troubleshooting. 

also install.pivpn.io still works. 
and you have the other methods.

**Comment by 4s3ti** [comment]
NP @Loogard this actually gave me an idea .. and i will see how can i share some of my monitoring and integrate it here so people can actually see the servers status.

**Comment by nowakommunikation** [comment]
As for the PiVPN, I re-installed it and now everything works as before. Why it broke, I don't know. I assume it has sth to do with upgrading/dating the Raspberry Pi, Pi Hole and dependencies.
From the PiVPN log I couldn't figure out what's wrong. After connecting via Tunnelblick, a few KBs were exchanged (i. e. password was correct) and then nothing happened. 
Tried to search the internet with this message from the log

"Tunnelblick[21003] runTunnelblickd: no data available from tunnelblickd socket; sleeping"

but didn't find any useful help. 

Perhaps I should mention that I use Tunnelblick with OpenVPN  version 2.3.18 rather than 2.4.4. Maybe that was a problem after the upgrade/date. 
But 2.4.4 doesn't seem to work when I install PiVPN. It tells me that the version on the Pi is 2.4.0 and not 2.4.4 (as my Tunnelblick program requests) and I couldn't be bothered to update OpenVPN on the Raspberry Pi by hand. Version 2.3.18 has worked fine so far.
