### ISSUE TITLE
Upgrade wiki used old domain

### ISSUE THREAD

**Issue by menzo2003** [pivpn/pivpn#938]
The wiki page about upgrading still lists the .io extension instead of the new .dev

**Comment by 4s3ti** [comment]
@menzo2003 pivpn.io is getting back to usage again as it is now pointing to the servers hosting the website therefor is now able to use SSL 

 ... if you check ... pivpn.dev is already redirecting to pivpn.io  ... so stuff will be moving back to pivpn.io ... i am truly sorry about this back and forth with the domain but the reason why we moved ot pivpn.dev was due to not being able to provide https on pivpn.io. 

both domains belong to the project and both are being served form same servers.

**Comment by 4s3ti** [comment]
```
$dig pivpn.io

; <<>> DiG 9.14.9 <<>> pivpn.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51519
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;pivpn.io.			IN	A

;; ANSWER SECTION:
pivpn.io.		171	IN	A	88.198.194.195
pivpn.io.		171	IN	A	88.198.194.194

;; Query time: 5 msec
;; SERVER: 10.130.182.1#53(10.130.182.1)
;; WHEN: Wed Feb 05 14:26:31 CET 2020
;; MSG SIZE  rcvd: 69

$dig pivpn.dev

; <<>> DiG 9.14.9 <<>> pivpn.dev
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40248
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;pivpn.dev.			IN	A

;; ANSWER SECTION:
pivpn.dev.		1798	IN	A	88.198.194.194
pivpn.dev.		1798	IN	A	88.198.194.195

;; Query time: 24 msec
;; SERVER: 10.130.182.1#53(10.130.182.1)
;; WHEN: Wed Feb 05 14:26:33 CET 2020
;; MSG SIZE  rcvd: 70

```

**Comment by 4s3ti** [comment]
I am just waiting on the creation of test.pivpn.io to fully change back to pipn.io. 

this said i will keep this open just in case more people notices it 
also i have posted about this on reddit .. but apparently my account has been shadow banned .. seems that my updates about pivpn pissed some bots!

**Comment by 4s3ti** [comment]
here: https://github.com/pivpn/pivpn/pull/940

We have now fully reverted to pivpn.io
as mentioned before, pivpn.dev will still exist and can be used as well. 

closing.
