### ISSUE TITLE
[ERR] Iptables MASQUERADE rule is not set, attempt fix now? After every reboot

### ISSUE THREAD

**Issue by Bob-I** [pivpn/pivpn#951]
Currently running: 
Linux raspberrypi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
This one rule mentioned in the topic is not persistent. 
I followed tips from e.g.
https://linuxconfig.org/how-to-make-iptables-rules-persistent-after-reboot-on-linux

But after every reboot I have to run pivpn -d again.

I also tried to follow some tips mentioned here with no solution.

**Comment by 4s3ti** [comment]
Dear user, even though we love the fact you are using pivpn, the maintainers of this project keep answering the same thing over and over again.

They keep spending time not only on the project that makes your life so great but also on documentation that you not to read at all therefore this issue is being closed. 

Don't know why your issue got closed? 

You can start by reading here: https://www.pivpn.io/#contrib
And here: https://github.com/pivpn/pivpn/blob/master/README.md
And here: https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md

and the first lines on the issue template that appeared after you have pressed all those green buttons to open up this issue: 

```
<!-- 
# PiVPN Issue Template
PLEASE READ THIS TEMPLATE CAREFULLY BEFORE OPENING AN ISSUE! 
Any Issue opened that doesn't follow this template will be removed.
```

Still not happy? 

Feel free to express yourself but most likely our position won't change, and hopefully you have now learned how to open an issue anywhere in the opensource community! 


Wish you a great day, feel free to reopen this issue but this time make sure it follows the rules!

**Comment by Afterschnitzel** [comment]
Same here

**Comment by adastx** [comment]
I experienced the same issue on [DietPi](https://dietpi.com/).

I believe the issue is somewhere with the pivpn installer failing to run `iptables-save`. The iptables rules are never made persistent.This is why they are gone after every reboot and you have to re-run `pivpn -d`.

I followed [this tutorial](https://linuxconfig.org/how-to-make-iptables-rules-persistent-after-reboot-on-linux) to manually save the iptables rules. 
DietPi is based on Debian so I just followed the tutorial's Debian method.

After these steps everything works as expected. The rules persist after reboots.

**Comment by 4s3ti** [comment]
do not necro posts. locking.
