### ISSUE TITLE
RDP, Windows > Windows

### ISSUE THREAD

**Issue by Bagel2sR** [pivpn/pivpn#965]
Hello,

I have PIVPN with wireguard installed on my PI.

I can successfully get my windows machines to connect to it over a 4g connection.

The machines can ping each other but they cannot connect to each other via the remote desktop app.

Please help :).

**Comment by 4s3ti** [comment]
Dear user, even though we love the fact you are using pivpn, the maintainers of this project keep answering the same thing over and over again.

They keep spending time not only on the project that makes your life so great but also on documentation that you not to read at all therefore this issue is being closed. 

Don't know why your issue got closed? 

You can start by reading here: https://www.pivpn.io/#contrib
And here: https://github.com/pivpn/pivpn/blob/master/README.md
And here: https://github.com/pivpn/pivpn/blob/master/CONTRIBUTING.md

and the first lines on the issue template that appeared after you have pressed all those green buttons to open up this issue: 

```
<!-- 
# PiVPN Issue Template
PLEASE READ THIS TEMPLATE CAREFULLY BEFORE OPENING AN ISSUE! 
Any Issue opened that doesn't follow this template will be removed.
```

Still not happy? 

Feel free to express yourself but most likely our position won't change, and hopefully you have now learned how to open an issue anywhere in the opensource community! 


Wish you a great day, feel free to reopen this issue but this time make sure it follows the rules!

Also if your VPN with Wireguard is working then its not pivpn issue. 
Also this is not a windows support group.
Also if you have had read the documentation you would find that there is a more appropriate place for this kind of things: https://www.reddit.com/r/pivpn/  .

Might take a bit till some one answers you .. but this is not the place where you going to get your answers.
