### ISSUE TITLE
Unconnected WireGuard clients shown in pivpn -c

### ISSUE THREAD

**Issue by AABatteries** [pivpn/pivpn#986]
The command 'pivpn -c' returns the list of connected clients as expected. However, the clients are still show when user calls 'pivpn -c' after the clients have already disconnected. Is this a limitation of WireGuard or am I missing something? 

Expected behavior: 'pivpn -c' returns only currently connected clients, not disconnected ones.

**Comment by FrostyMisa** [comment]
I think this behavior is OK for me, because it's show when the client was seen connected last time where you can see the time. Maybe, but I have only two clients, but if there is many of them, maybe sort them by this last seen time, but like I said for me it's OK because you can see when they was connected with server last time.
After help command they write show connected clients, this can be little bit misleading, but I like to see the time last connection and statistics like it works now.

**Comment by orazioedoardo** [comment]
That's how WireGuard works. There is not a concept of a "connection", more a "handshake on demand". A client will perform the hanshake with the server when it has to send data. It you don't send data you can't tell if the client is off or it has nothing to send. You will see those clients in `pivpn -c` until you reboot or restart the wireguard interface.

**Comment by AABatteries** [comment]
Thanks for the clarification. I was used to the way OpenVPN handled things hence my hesitation. Closing the issue now.
