### ISSUE TITLE
[FR] Periodically reboot

### ISSUE THREAD

**Issue by bellingeri** [pivpn/pivpn#995]
Hello.

In relation to the request of the installation script to perform periodic restarts, it may be useful to activate a weekly scheduled operation, perhaps asking for day of the week and time.

Thanks.

**Comment by 4s3ti** [comment]
@orazioedoardo did you introduced any preiodic restart request? or did i got this part wrong: 

> In relation to the request of the installation script to perform periodic restarts


I don't think we should offer this at all!

We do not know what things are running on users pis, and i can see a lot of incoming issues 

"my pi restarted now my service X doesnt work anymore"

Maintaining systems should be user responsibility not pivpn team / script, we offer to unattended updates because that is a debian feature, not at all related with pivpn. 

Our job is to make VPN instalation easier and offer the best out of the box settings regarding security.

**Comment by orazioedoardo** [comment]
@4s3ti There is [suggestion](https://github.com/pivpn/pivpn/blame/9f20f50e6168d4d24d40e938cbb9b48c2f4ee383/auto_install/install.sh#L507) to reboot periodically to apply kernel upgraded.

> We do not know what things are running on users pis, and i can see a lot of incoming issues
>
> "my pi restarted now my service X doesnt work anymore"

Agree, too dangerous to schedule an automatic reboot.

**Comment by 4s3ti** [comment]
> @4s3ti There is [suggestion](https://github.com/pivpn/pivpn/blame/9f20f50e6168d4d24d40e938cbb9b48c2f4ee383/auto_install/install.sh#L507) to reboot periodically to apply kernel upgraded.

Phew!! Well having this said closing this one. 

don't thing this should be something we should do ... 

Users that actually want scheduled reboot ... shout just add, for example  a cron job which is fairly easy to do :)
